### ISSUE TITLE
Currently failing in Firefox - v1.0+

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-browser-extension#104]
Due to connectivity issues (sending information between components), the browser extension does not work in firefox.

**Comment by perry-mitchell** [comment]
Seems it might be a false alarm.. Proceeding.

**Comment by julianpoemp** [comment]
It still fails using firefox on Windows and MacOS.

ButterCup Version: 1.05
Firefox: 57.0.4 (64-Bit)

### Description:

#### 1. Problem

I installed the ButterCup Extension and connected Owncloud with it. The connection was successfull. But when I click on the ButterCup Icon on the right beside the password field it says "No unlocked archives, No archives are currently available/unlocked. Why not get started by adding one?". But the archive is unlocked for sure.

#### 2. Problem
After closing Firefox and reopening the browser my connected archive got lost.
