### ISSUE TITLE
No unlock archive

### ISSUE THREAD

**Issue by moulip** [buttercup/buttercup-browser-extension#108]
Hi,

Since the last update of the extension, I cannot use use it any longer. I have unlocked my archive, but when I'm prompted for my credentials by a website, it keeps telling me that there is no unlocked archive.
I'm using Firefox 57 under Debian.

**Comment by perry-mitchell** [comment]
Hi @moulip - Can you confirm that you're using the latest version of the extension? I believe it should be 1.0.7. We fixed some communication issues recently for Firefox.

**Comment by moulip** [comment]
Hello Perry,

Actually it has begun to work all of a sudden !
Cheers,
