### ISSUE TITLE
Injected Buttercup buttons change forms tab index

### ISSUE THREAD

**Issue by sallar** [buttercup/buttercup-browser-extension#117]
The Buttons that are injected in the page are changing forms' tab indexes. So for example if I press tab after entering my username, password field wont be focus, instead buttercup button will be focused. I think we should change the tab index on Buttercup buttons to minus values so they dont get focused automatically.

![image](https://user-images.githubusercontent.com/768052/35801491-47f24f4e-0a75-11e8-84c4-d254c95bbfe3.png)

**Comment by perry-mitchell** [comment]
Thoroughly agreed!
