### ISSUE TITLE
Unable to load file

### ISSUE THREAD

**Issue by jbvioix** [buttercup/buttercup-browser-extension#123]
Hello, thanks for your work Buttercup is a great application.
I'm using buttercup extension 1.3.1 with Firefox 58.0.2 and I can't load my file on a Nextcloud server. Using the desktop application all it's OK. Firefox plugin can browse file on the server an find the buttercup file but when I click on nothin happens. Do you have an idea ?

**Comment by perry-mitchell** [comment]
Hi @jbvioix - Are you able to open the devtools next time you get a chance to try this? It'd be interesting to see if there are any failures in the network logs. Please consider the contents of any data you post here, as we don't want to see any login credentials of yours 😊

**Comment by jbvioix** [comment]
Are this kind of message you want ?
``The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
setup.html
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« script-src moz-extension://aaec01fb-299f-4db5-8bd0-2bad7f8adc1f »). Source: call to eval() or related function blocked by CSP.
setup-index.js:1
[info] Received full state update from background 
Object { app: {…}, archives: {…}, dropbox: {…}, searching: {…} }
setup-index.js:1:134207
[info] Sending state update to background 
Object { type: "addArchive/setSelectedArchiveType", payload: "nextcloud", actionSync: 0 }
setup-index.js:1:134207
[info] Sending state update to background 
Object { type: "addArchive/setConnecting", payload: true, actionSync: 1 }
setup-index.js:1:134207
[info] Creating WebDAV connection to: https:/************.***/remote.php/webdav
setup-index.js:1:134207
[info] Testing WebDAV connection...
setup-index.js:1:134207
[info] WebDAV connected successfully
setup-index.js:1:134207
[info] Connection to WebDAV service succeeded
setup-index.js:1:134207
[info] Sending state update to background 
Object { type: "addArchive/setConnected", payload: true, actionSync: 2 }
setup-index.js:1:134207
[info] Sending state update to background 
Object { type: "remoteFiles/directory/setLoading", payload: {…}, actionSync: 3 }
setup-index.js:1:134207
[info] Sending state update to background 
Object { type: "addArchive/setConnecting", payload: false, actionSync: 4 }
setup-index.js:1:134207
[info] Received webdav directory contents: / 
Array [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
setup-index.js:1:134207
[info] Sending state update to background 
Object { type: "remoteFiles/directory/setContents", payload: {…}, actionSync: 5 }
setup-index.js:1:134207
[info] Sending state update to background 
Object { type: "remoteFiles/directory/setLoading", payload: {…}, actionSync: 6 }
setup-index.js:1:134207
[info] Sending state update to background 
Object { type: "remoteFiles/directory/setLoading", payload: {…}, actionSync: 7 }
setup-index.js:1:134207
[info] Received webdav directory contents: /Perso 
Array [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
setup-index.js:1:134207
[info] Sending state update to background 
Object { type: "remoteFiles/directory/setContents", payload: {…}, actionSync: 8 }
setup-index.js:1:134207
[info] Sending state update to background 
Object { type: "remoteFiles/directory/setLoading", payload: {…}, actionSync: 9 }
setup-index.js:1:134207
[info] Sending state update to background 
Object { type: "addArchive/remoteFile/select", payload: "/****/****.bcup", actionSync: 10 }
setup-index.js:1:134207
``
Thank for your help.

**Comment by perry-mitchell** [comment]
Sorry for the delay @jbvioix - So it seems that the front-end (tab) is working correctly, based upon your output. If you get a chance to try again, you could debug the background tab to see what happens when it tries to add it to Bcup. I think Firefox has something like `about:debugging` where you can debug extensions.

**Comment by jbvioix** [comment]
Hello, after an update of Firefox all is OK! I don't know why...

**Comment by perry-mitchell** [comment]
Hmm.. weird.. Keep us posted if something occurs again!
