### ISSUE TITLE
Simplify save screen: Default selections for archive and group

### ISSUE THREAD

**Issue by D3N14L** [buttercup/buttercup-browser-extension#125]
When saving a password it is quiet tedious to always select the archive and group where the password should be stored. Although in the most cases the "last used" archive will be a good guess. Also the last used group within the archive should be a good default selection for this step. Adding default selections here would strip down two more interactions from saving a password.

**Comment by daeh** [comment]
I would really appreciate the auto-selection of the last used archive & group

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
