### ISSUE TITLE
"Use last generated password" option for the context menu

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-browser-extension#136]
Add the ability to input the last generated password via the context menu.

**Comment by flohw** [comment]
Having the option "generate password" directly in the context menu would be a better option. It would prevent to open the desktop app, generate password, wich requires to create a new entry.

**Comment by perry-mitchell** [comment]
It’s already available from the menu. The issue is how we can make it easy to enter the same password twice - like with confirm inputs.

**Comment by flohw** [comment]
Ho I didn't notice the contextual menu. I expected to find this option in the menu available through the icon next to the password field. Is there an open issue for this or may I create one ?

**Comment by perry-mitchell** [comment]
Of course, please create one.. 😊

**Comment by perry-mitchell** [comment]
Will go out in 1.11
