### ISSUE TITLE
Can't close "Save New Login" popup in Chrome

### ISSUE THREAD

**Issue by tamashiisama** [buttercup/buttercup-browser-extension#137]
Since Last update, i can't close "Save New Login" popup in Chrome.

Chrome Version : 65.0.3325.181
Buttercup Version : 1.6.0

Error details :
![error_buttercup](https://user-images.githubusercontent.com/13869992/38176444-5c5980ce-35ef-11e8-8da5-1ebd1ea837a9.jpg)

**Comment by perry-mitchell** [comment]
Thanks @tamashiisama - I've fixed this and am releasing now. Sorry!

**Comment by tamashiisama** [comment]
You're welcome.
