### ISSUE TITLE
"generate password" in context menu not shown

### ISSUE THREAD

**Issue by pleswi** [buttercup/buttercup-browser-extension#139]
I have problem with extension - only about menu show in context menu in chrome extension. 

![context menu](https://user-images.githubusercontent.com/6407598/38794932-f8f7ef20-4156-11e8-83ff-e49e777b7892.jpg)

Win 10 Pro, Chrome 65, buttercup extension 1.6.1

**Comment by perry-mitchell** [comment]
Thank you for reporting. This is weird behaviour because it was working, and has since shown more issues like this. Buttercup tells the browser to show the “generate password” option for all *editable* fields and it does it itself - we don’t show/hide the button ourselves.

**Comment by perry-mitchell** [comment]
Seems that this is worse than I expected.. I'll try to look at it soon.

**Comment by perry-mitchell** [comment]
This should be fixed in 1.6.2.
