### ISSUE TITLE
[1.6.2] Chrome, Firefox: Owncloud Sync does not work 

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-browser-extension#140]
After I synchronized buttercup with owncloud successfully on Android and desktop, I wanted to use Buttercup Browser Plugin & Owncloud using Chrome and Firefox. Both don't work (months ago it worked fine). When I try to add a new archive via Owncloud I get this error:

````Failed connecting to 'owncloud' resource A connection attempt to '<owncloud>' has failed: Connection failed to WebDAV service: https://<owncloud>/remote.php/webdav````

It seems that for owncloud sync webDav is used, too.

I tried:

- Firefox and Chrome on MacOS and Windows
- Owncloud Sync with different URLs (http, https, only domain)
- WebDav Sync
- Delete all Browser Cache and Cookies

Info:

- Buttercup 1.6.2
- Owncloud 10.0.7.2

**Comment by perry-mitchell** [comment]
Hi @julianpoemp - Dang! Thought we'd solved it. I'm not actually on v10 of ownCloud yet, so I'll try this soon. Please be aware that this is also covered by our goal not to try and debug connection issues - If the problem is easily reproducible on a version of owncloud/nextcloud or the exact cause of a bug is found we'll deal with it then.

I'll see if I can confirm that there's an issue once I update.

**Comment by julianpoemp** [comment]
Hi @perry-mitchell , I know that this bug doesn't have high priority. But I would like to let you know, that I found debug messages that could help you to solve this issue (in the future). The reason why I don't give up to help solving this issue is that I believe very much that a lot of owncloud users are searching for something like buttercup + Browser addon in combination with owncloud.

### System Info:
Buttercup 1.7.0 Addon on Firefox, Chrome
Owncloud: 10.0.8.5

### Assumption:

Perhaps this issue is solved if you change the "Authorization Basic" on your HTTP requests?
It seems that you add an "authorization" header with a small letter "a" instead of "A". Perhaps owncloud is validating this as invalid?
Please have a look on the owncloud debug messages below. The network entry from the webconsole says that I get an 500 server error whenever I try to authenticate via webdav.

### Owncloud log:
        {
           "reqId":"Wytq4OKQ659FroYdblbi1AAAAA8",
           "level":0,
           "time":"2018-06-21T09:07:44+00:00",
           "remoteAddr":"<remoteaddr>",
           "user":"--",
           "app":"webdav",
           "method":"GET",
           "url":"\/remote.php\/webdav",
           "message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/remote.php(165): require_once('\\\/www\\\/htdocs\\\/w01...')\\n#6 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}"
        }{
           "reqId":"WytrS74ISAg6AngMamlvzgAAAA8",
           "level":0,
           "time":"2018-06-21T09:09:31+00:00",
           "remoteAddr":"<remoteaddr>",
           "user":"--",
           "app":"webdav",
           "method":"GET",
           "url":"\/remote.php\/webdav",
           "message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/remote.php(165): require_once('\\\/www\\\/htdocs\\\/w01...')\\n#6 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}"
        }{
           "reqId":"WytrVAJnmy2BW0C16Z6EkgAAAA8",
           "level":3,
           "time":"2018-06-21T09:09:40+00:00",
           "remoteAddr":"<remoteaddr>",
           "user":"--",
           "app":"remote",
           "method":"PROPFIND",
           "url":"\/remote.php\/webdav",
           "message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Only http based URLs supported\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/public\\\/Util.php(805): OCP\\\\Util::getFullDomain('moz-extension:\\\/...')\\n#1 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/CorsPlugin.php(71): OCP\\\\Util::isSameDomain('moz-extension:\\\/...', 'https:\\\/\\\/upload....')\\n#2 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(407): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\CorsPlugin->initialize(Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Server))\\n#3 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ServerFactory.php(104): Sabre\\\\DAV\\\\Server->addPlugin(Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\CorsPlugin))\\n#4 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ServerFactory->createServer('\\\/remote.php\\\/web...', '\\\/remote.php\\\/web...', Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth), Object(Closure))\\n#5 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/remote.php(165): require_once('\\\/www\\\/htdocs\\\/w01...')\\n#6 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/public\\\/Util.php\",\"Line\":781}"
        }{
           "reqId":"WytrjcC17UbzLEKHj0ykUwAAAA8",
           "level":3,
           "time":"2018-06-21T09:10:37+00:00",
           "remoteAddr":"<remoteaddr>",
           "user":"--",
           "app":"remote",
           "method":"PROPFIND",
           "url":"\/remote.php\/webdav",
           "message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Only http based URLs supported\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/public\\\/Util.php(805): OCP\\\\Util::getFullDomain('moz-extension:\\\/...')\\n#1 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/CorsPlugin.php(71): OCP\\\\Util::isSameDomain('moz-extension:\\\/...', 'https:\\\/\\\/upload....')\\n#2 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(407): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\CorsPlugin->initialize(Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Server))\\n#3 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ServerFactory.php(104): Sabre\\\\DAV\\\\Server->addPlugin(Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\CorsPlugin))\\n#4 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ServerFactory->createServer('\\\/remote.php\\\/web...', '\\\/remote.php\\\/web...', Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth), Object(Closure))\\n#5 \\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/remote.php(165): require_once('\\\/www\\\/htdocs\\\/w01...')\\n#6 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/username\\\/oc.domain.net\\\/owncloud\\\/lib\\\/public\\\/Util.php\",\"Line\":781}"
        }


### Web console output (network entry):

     {
      "log": {
        "version": "1.1",
        "creator": {
          "name": "Firefox",
          "version": "60.0.2"
        },
        "browser": {
          "name": "Firefox",
          "version": "60.0.2"
        },
        "pages": [
          {
            "startedDateTime": "2018-06-21T11:29:30.313+02:00",
            "id": "page_1",
            "title": "Buttercup v1.7.0",
            "pageTimings": {
              "onContentLoad": -20248,
              "onLoad": -20186
            }
          }
        ],
        "entries": [
          {
            "pageref": "page_1",
            "startedDateTime": "2018-06-21T11:29:30.313+02:00",
            "request": {
              "bodySize": 0,
              "method": "PROPFIND",
              "url": "https://upload.domain.net/remote.php/webdav",
              "httpVersion": "HTTP/2.0",
              "headers": [
                {
                  "name": "Host",
                  "value": "upload.domain.net"
                },
                {
                  "name": "User-Agent",
                  "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0"
                },
                {
                  "name": "Accept",
                  "value": "*/*"
                },
                {
                  "name": "Accept-Language",
                  "value": "de,en-US;q=0.7,en;q=0.3"
                },
                {
                  "name": "Accept-Encoding",
                  "value": "gzip, deflate, br"
                },
                {
                  "name": "depth",
                  "value": "1"
                },
                {
                  "name": "authorization",
                  "value": "Basic anVsaWFuOkRyYWNoZW5mZXVlcjg="
                },
                {
                  "name": "origin",
                  "value": "moz-extension://20dfcfd6-7a81-7e4e-a447-0243912a4ce1"
                },
                {
                  "name": "DNT",
                  "value": "1"
                },
                {
                  "name": "Connection",
                  "value": "keep-alive"
                }
              ],
              "cookies": [],
              "queryString": [],
              "headersSize": 406
            },
            "response": {
              "status": 500,
              "statusText": "Internal Server Error",
              "httpVersion": "HTTP/2.0",
              "headers": [
                {
                  "name": "date",
                  "value": "Thu, 21 Jun 2018 09:29:30 GMT"
                },
                {
                  "name": "server",
                  "value": "Apache"
                },
                {
                  "name": "set-cookie",
                  "value": "544b7e5e62a92=e8b4e6cd431ff2eee12446ca7ba8e650; path=/; HttpOnly"
                },
                {
                  "name": "expires",
                  "value": "Thu, 19 Nov 1981 08:52:00 GMT"
                },
                {
                  "name": "cache-control",
                  "value": "no-store, no-cache, must-revalidate"
                },
                {
                  "name": "pragma",
                  "value": "no-cache"
                },
                {
                  "name": "set-cookie",
                  "value": "oc_sessionPassphrase=eQtDDLnlKrwRcOl%2B3Lsvf5sao58eDRmRRvp29u06%2BOfuIRNKU06jpQqV5aecqIHBhrm%2FMj1ouzKT9vdV8326EGwl70Ocf5g5ols1b9tl7z8NTgaNd%2FPi20%2BJU2Er%2F3qV; path=/; secure; HttpOnly"
                },
                {
                  "name": "x-xss-protection",
                  "value": "1; mode=block"
                },
                {
                  "name": "x-content-type-options",
                  "value": "nosniff"
                },
                {
                  "name": "x-frame-options",
                  "value": "SAMEORIGIN"
                },
                {
                  "name": "x-robots-tag",
                  "value": "none"
                },
                {
                  "name": "x-download-options",
                  "value": "noopen"
                },
                {
                  "name": "x-permitted-cross-domain-policies",
                  "value": "none"
                },
                {
                  "name": "content-security-policy",
                  "value": "default-src 'none';"
                },
                {
                  "name": "strict-transport-security",
                  "value": "max-age=15552000"
                },
                {
                  "name": "content-type",
                  "value": "text/html; charset=UTF-8"
                },
                {
                  "name": "X-Firefox-Spdy",
                  "value": "h2"
                }
              ],
              "cookies": [
                {
                  "name": "544b7e5e62a92",
                  "value": "e8b4e6cd431ff2eee12446ca7ba8e650"
                },
                {
                  "name": "oc_sessionPassphrase",
                  "value": "eQtDDLnlKrwRcOl+3Lsvf5sao58eDRmRRvp29u06+OfuIRNKU06jpQqV5aecqIHBhrm/Mj1ouzKT9vdV8326EGwl70Ocf5g5ols1b9tl7z8NTgaNd/Pi20+JU2Er/3qV"
                }
              ],
              "content": {
                "mimeType": "text/html; charset=UTF-8",
                "size": 8181,
                "text": "<!DOCTYPE html>\n<html class=\"ng-csp\" data-placeholder-focus=\"false\" lang=\"de\" >\n\t<head data-requesttoken=\"\">\n\t\t<meta charset=\"utf-8\">\n\t\t<title>\n\t\townCloud\t\t</title>\n\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n\t\t<meta name=\"referrer\" content=\"never\">\n\t\t<meta name=\"viewport\" content=\"width=device-width, minimum-scale=1.0, maximum-scale=1.0\">\n\t\t<meta name=\"apple-itunes-app\" content=\"app-id=543672169\">\n\t\t<meta name=\"theme-color\" content=\"#1d2d44\">\n\t\t<link rel=\"icon\" href=\"/core/img/favicon.ico\">\n\t\t<link rel=\"apple-touch-icon-precomposed\" href=\"/core/img/favicon-touch.png\">\n\t\t<link rel=\"mask-icon\" sizes=\"any\" href=\"/core/img/favicon-mask.svg\" color=\"#1d2d44\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/styles.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/inputs.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/header.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/icons.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/fonts.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/apps.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/global.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/fixes.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/multiselect.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/mobile.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/vendor/select2/select2.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/jquery-ui-fixes.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/tooltip.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/share.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/apps/files_versions/css/versions.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/core/css/jquery.ocdialog.css?v=8e006f642a066795e8d8cede5b8d6b23\">\n\t\t\t\t\t\t\t\t\t<script src=\"/core/vendor/jquery/dist/jquery.min.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/vendor/jquery-migrate/jquery-migrate.min.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/vendor/underscore/underscore.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/vendor/moment/min/moment-with-locales.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/vendor/handlebars/handlebars.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/vendor/blueimp-md5/js/md5.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/vendor/bootstrap/js/tooltip.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/vendor/backbone/backbone.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/vendor/es6-promise/dist/es6-promise.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/vendor/davclient.js/lib/client.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/vendor/clipboard/dist/clipboard.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/vendor/bowser/src/bowser.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/jquery.ocdialog.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/oc-dialogs.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/js.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/l10n.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/l10n/de.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/octemplate.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/eventsource.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/config.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/search/js/search.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/oc-requesttoken.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/apps.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/mimetype.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/mimetypelist.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/vendor/snapjs/dist/latest/snap.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/oc-backbone.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/placeholder.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/jquery.avatar.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/shareconfigmodel.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/sharemodel.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/sharescollection.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/shareitemmodel.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/sharedialogresharerinfoview.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/sharedialoglinklistview.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/sharedialoglinkshareview.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/sharedialogmailview.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/sharedialoglinksocialview.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/sharedialogexpirationview.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/sharedialogshareelistview.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/sharedialogview.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/share.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/files/fileinfo.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t<script src=\"/core/js/files/client.js?v=8e006f642a066795e8d8cede5b8d6b23\"></script>\n\t\t\t\t\t</head>\n\t<body id=\"body-login\">\n\t\t<noscript>\n\t<div id=\"nojavascript\">\n\t\t<div>\n\t\t\tDiese Anwendung benötigt zum ordnungsgemäßen Betrieb JavaScript. Bitte <a href=\"http://enable-javascript.com/\" target=\"_blank\" rel=\"noreferrer\">aktiviere JavaScript</a> und lade die Seite neu.\t\t</div>\n\t</div>\n</noscript>\n\t\t<div class=\"wrapper\">\n\t\t\t<div class=\"v-align\">\n\t\t\t\t\t\t\t\t\t<header role=\"banner\">\n\t\t\t\t\t\t<div id=\"header\">\n\t\t\t\t\t\t\t<div class=\"logo\">\n\t\t\t\t\t\t\t\t<h1 class=\"hidden-visually\">\n\t\t\t\t\t\t\t\t\townCloud\t\t\t\t\t\t\t\t</h1>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t<div id=\"logo-claim\" style=\"display:none;\"></div>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</header>\n\t\t\t\t\t\t\t\t<span class=\"error error-wide\">\n\t<h2><strong>Interner Serverfehler</strong></h2>\n\t\t<p>Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.</p>\n\t\t<p>Bitte wende dich an den Serveradministrator, sollte dieser Fehler mehrfach auftreten und füge deiner Anfrage die unten stehenden technischen Details bei.</p>\n\t\t<p>More details can be found in the <a target=\"_blank\" rel=\"noreferrer\" href=\"https://doc.owncloud.org/server/10.0/go.php?to=admin-logfiles\">server log</a>.</p>\n\t<br>\n\n\t<h2><strong>Technische Details</strong></h2>\n\t<ul>\n\t\t<li>Entfernte Adresse: 77.47.102.54</li>\n\t\t<li>Anforderungskennung: Wytv@p9vecT03TVJLH@IFQAAABE</li>\n\t\t\t</ul>\n\n\t</span>\n\t\t\t\t<div class=\"push\"></div>\n\t\t\t</div>\n\t\t</div>\n\t\t<footer role=\"contentinfo\">\n\t\t\t<p class=\"info\">\n\t\t\t\t<a href=\"https://owncloud.org\" target=\"_blank\" rel=\"noreferrer\">ownCloud</a> – Ein sicherer Speicherplatz für deine ganzen Daten.\t\t\t</p>\n\t\t</footer>\n\t</body>\n</html>\n"
              },
              "redirectURL": "",
              "headersSize": 802,
              "bodySize": 8983
            },
            "cache": {},
            "timings": {
              "blocked": 0,
              "dns": 0,
              "connect": 0,
              "ssl": 0,
              "send": 0,
              "wait": 234,
              "receive": 0
            },
            "time": 234,
            "_securityState": "secure",
            "serverIPAddress": "<serverip>",
            "connection": "443"
          }
        ]
      }
    }

**Comment by perry-mitchell** [comment]
Hi @julianpoemp, thanks a lot for keeping on this.. I really appreciate the information.

Interesting that ownCloud would complain when the header is clearly there - case shouldn't matter, as you can see by the other headers (mix of cases). That being said, my core library webdav-client actually sets it in the [correct case](https://github.com/perry-mitchell/webdav-client/blob/master/source/factory.js#L75), so I don't know how it's getting changed as of yet.

**Comment by perry-mitchell** [comment]
@julianpoemp Would you happen to have the opportunity to test the `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` addition to your server, as mentioned [here](https://andre-hoeche.de/blog/tag/no-authorization-basic-header-found/)?

If this doesn't help, it's also possible that we need to change the WebDAV endpoint from `remote.php/webdav` to something else starting from v10.

**Comment by julianpoemp** [comment]
@perry-mitchell unfortunately, I can't set such attribute because I only have a webspace without root access... But I will try to find an alternative. Perhaps I can do something via PHP or htaccess file. If I find some workaraound, I let you know.

**Comment by perry-mitchell** [comment]
Thank you! I really should get around to upgrading to version 10 of owncloud.. 😅

**Comment by julianpoemp** [comment]
Finally found the source of this problem.

When I try to connect via the Plugin (latest version) it still does not work (505 Propfind). But if I remove the origin header from the request made by the plugin it works fine!

Is there any way that you can remove the origin header from the requests made to an owncloud installation?

I created an issue on the owncloud repository here:
https://github.com/owncloud/core/issues/32090

**Comment by perry-mitchell** [comment]
We don't set the `Origin` header - it's set [by the browser](https://tools.ietf.org/id/draft-abarth-origin-03.html):

> The Origin header is added by the user agent to describe the security contexts that caused the user agent to initiate an HTTP request

It'd be really weird if this _were_ the issue, as I use ownCloud and Chrome/Firefox and haven't seen such an error with CORS myself. We use [this library](https://github.com/perry-mitchell/webdav-client) to make WebDAV requests.. any chance you could give this a go with your setup to see if you still get errors? In the CLI you won't as there is no Origin and no browser, but it's worth a look at.

**Comment by julianpoemp** [comment]
@perry-mitchell thanks for your fast response!

I tested it. It works all fine using the cli and a test script!

**Comment by julianpoemp** [comment]
@perry-mitchell I tried to change the manifest.json file as the guy from ownlcoud said. It didn't work for me.

The problem is definitely with the origin header. But because it can't be set in code I don't know how to solve this issue. I think the buttercup extension doesn't work with any owncloud version >= 10 on each browser. I tried it also with a fresh installation.

owncloud seems to block web-dav requests with "wrong origin headers" and there is no way to set this in the owncloud configuration.

Perhaps as a workaround a PHP file on the server could be created that redirects the webDAV request without an origin header to the remote.php file of owncloud...

**Comment by perry-mitchell** [comment]
Ok, based on that conversation on the ownCloud repo, I believe that [this](https://github.com/owncloud/core/issues/32090#issuecomment-406644277) is the issue. We'll try to migrate to using XHR in the browser, but let's see.

**Comment by perry-mitchell** [comment]
The [webRequest](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest) API might also help.

**Comment by julianpoemp** [comment]
Thanks to DeepDiver1975 from owncloud, this bug will be fixed soon for firefox on server-side. For Chrome and Opera the Buttercup extension sends a "Origin: null" header. According to DeepDiver1975 this is not a valid value for the origin header. Allowing "null" seems to be no option if there could be a way to send a valid header on client-side. You can find the discussion here: https://github.com/owncloud/core/pull/32120

In my point of view the easiest way would be to allow "null" responses on server-side. Otherway all browser extensions need to implement additional stuff to make an owncloud connection work. 

Nevertheless I will set this workaround in my owncloud installation and can finally use owncloud and buttercup in Chrome and Firefox.

### workaround

As a workaround owncloud users can copy and replace this file to their owncloud installation:
https://github.com/owncloud/core/pull/32120/commits/97ac5100cada78d7a26231c6890249e5e239b4e6

After that in order to allow "null" responses, the line 163 should be changed to 

    if (empty($originHeader) || $originHeader == "null") {

After that Buttercup should work with owncloud on Chrome, Firefox and Opera.

**Comment by perry-mitchell** [comment]
This should be solved when perry-mitchell/webdav-client#99 is completed.

**Comment by julianpoemp** [comment]
the guy from owncloud commited a bug fix that fixes this problem on the server side. I assume that it's coming with the next owncloud release.

**Comment by julianpoemp** [comment]
@perry-mitchell this issue is fixed now in Owncloud 10.0.10. Buttercup extension works now in combination with owncloud on all browsers.

**Comment by perry-mitchell** [comment]
@julianpoemp Amazing! Thank you so much for following that through - Cheers, really.

I've been terrible and haven't yet updated my owncloud 😅 (I have a lot of people connected to it).. but I'll try to do it soon to test. Good to hear this went well.

**Comment by julianpoemp** [comment]
@perry-mitchell thank you for support and your amazing work!
