### ISSUE TITLE
Login form not recognized: Twitch.tv - Chrome

### ISSUE THREAD

**Issue by gertsonderby** [buttercup/buttercup-browser-extension#146]
The login dialog does not receive the Buttercup icons in its inputs, on any page that I've found. Also tried with dev tools open, no change.

**Comment by perry-mitchell** [comment]
Seems password is now working, but not the username..

![image](https://user-images.githubusercontent.com/3869469/44547647-7ea1e300-a724-11e8-9587-2926471479dd.png)

**Comment by perry-mitchell** [comment]
Moved to Locust: buttercup/locust#27
