### ISSUE TITLE
Can't open browser extension's settings

### ISSUE THREAD

**Issue by AntoninCamus** [buttercup/buttercup-browser-extension#147]
Hello, an strange issue here. I was searching for the settings of the extension on google chrome on windows, clean and without any other extensions.
When I open the extension clicking on the icon and then on the hamburger button, and then on Settings with the gear icon, nothing appens. 

It is a bug or something not implemented ? 
If the second, shouldn't it be more ergonomic to have the icon greyed and unclickable (to represend the fact that it is disabled)

**Comment by perry-mitchell** [comment]
Sorry @AntoninCamus - It isn't actually implemented yet. It was an oversight to leave it in the extension, unfortunately. We'll most likely remove it temporarily until we have something to show there.
