### ISSUE TITLE
Provide login prompt for an archive instead of showing "no unlocked archives" messages

### ISSUE THREAD

**Issue by antonincms** [buttercup/buttercup-browser-extension#148]
Hello !
Each time I open my browser I forget to log in into my archive. 
Could it be possible to have a Opt-in checkbox to permit that
- 1st possibility -> when we open our browser, open a pop-up to login
- automatically when we entered / have to enter a login, instead of saying "no archive opened", like here 
![capture](https://user-images.githubusercontent.com/9219052/40606274-237e0ffc-6265-11e8-8617-a224643be973.PNG)
![capture2](https://user-images.githubusercontent.com/9219052/40606278-257f1260-6265-11e8-9f05-44dc09e971bb.PNG)

pop-up a field to enter password of our main archive

**Comment by perry-mitchell** [comment]
Hi @AntoninCamus - Great suggestions. Your first is already noted here: #130, so I'll update the title of this issue to reflect the other (login input for main archive). That's a great idea!

**Comment by AntoninCamus** [comment]
I tried to fix it alone but at the moment, i'm not really able to since I've never dev' webextentions by myself. Is there a guide to contribute / a documentation of the functionnement or not at all ?

**Comment by perry-mitchell** [comment]
Well it's a bit complicated.. but I'm sure you'd figure it out with a little fiddling of course 😊

The problem is that the user may have more than 1 archive, so we can't just provide 1 link in that case. We *could* have a generic unlock page where we can select which archive to unlock. If such a page were created, by yourself or one of us for instance, we could simply link to that when messages about "no unlocked archives" appear.

It could read, for instance: "No unlocked archives were found. Click here to unlock one."

**Comment by pleswi** [comment]
Some update? It's strange click to login form -> no unlocked vaults -> must go up to extension icon and unlock. Some button in the text which open unlock page or same  popup as from extension icon will be better.

**Comment by perry-mitchell** [comment]
In #243 I've added an extra button to reduce clicks, but it doesn't exactly solve this issue. I think that it's a step in the right direction but we still need to consider what the best option is here.

**Comment by pleswi** [comment]
@perry-mitchell thumbs up, but I miss the same button on popup from login form, look to the picture below.  
![buttercup popup](https://user-images.githubusercontent.com/6407598/54279625-d35c5c80-4595-11e9-9aa2-5934c3122427.jpg)

**Comment by perry-mitchell** [comment]
@pleswi Good point! I don't have time to add it right now so I'd be happy if someone could submit a PR.

**Comment by ldexterldesign** [comment]
I think this issue should be closed

If vaults are locked then an unlock CTA button appears in extension and form tooltips now

Regards

**Comment by perry-mitchell** [comment]
@ldexterldesign I think the intention behind this was to add a password input in the dialog itself to save opening a new tab to unlock etc..
