### ISSUE TITLE
[Firefox] Layout issue on iZettle login page

### ISSUE THREAD

**Issue by moimael** [buttercup/buttercup-browser-extension#153]
On iZettle login page, the layout is messed up by the extension. Disabling it fixes it.

![screenshot from 2018-07-12 11-43-20](https://user-images.githubusercontent.com/1479859/42625880-2354ffb8-85c9-11e8-974e-dcdb2f86fb21.png)

Thanks !

**Comment by perry-mitchell** [comment]
Will go out in 1.11

**Comment by moimael** [comment]
I still have the same issue in v2.0.0

**Comment by perry-mitchell** [comment]
Sorry @moimael! I'll look into it.
