### ISSUE TITLE
Credentials mapping faillure

### ISSUE THREAD

**Issue by EagleEnergy** [buttercup/buttercup-browser-extension#155]
Hi,

Today I have had a newer entry automatically generated by the firefox extension.
After that I was unable to open my vault from the desktop Application on Fedora 28 due of a mapping failure for number of credentials.
Fortunately I was able to open my vault on firefox extension and on the android application.

A few minutes after this bug, I have just edit off this new entry from the android application and after that I'm able to open my vault from the Desktop application.

FYI my vault is synchronized between my phone and my laptop by a Nextcloud server.

Kind regards

**Comment by perry-mitchell** [comment]
Hi @EagleEnergy - we'd need to see this error to be able to start debugging it. Would you be able to open your browser's devtools to copy+paste the error here? Even a screenshot would do. If you can't see it immediately, it could be in the background tab. If you're using chrome, you can get to that by: Menu > More Tools > Extensions > Inspect background page:

![image](https://user-images.githubusercontent.com/3869469/42906086-b1798a5c-8ae2-11e8-9028-4fc132d4550b.png)

If not Chrome, can you please let us know what browser you're using?

**Comment by EagleEnergy** [comment]
Hi @perry-mitchell 
There is the differents steps of the bug.
First step i'm loggin to web site not registrated in my Buttercup vault so i'm asked to save it whit the firefox extension, what I do.
![first](https://user-images.githubusercontent.com/28734497/42925875-f3e96266-8b2f-11e8-93fe-fe3bd211b297.png)

Then to the second step I try to open my vault on Fedora desktop application.
There is the failure
![failure](https://user-images.githubusercontent.com/28734497/42925874-f3aedca4-8b2f-11e8-81ae-727614b55420.png)

Third step I edit my password and save it from the Android application.
![screenshot_20180719-084025](https://user-images.githubusercontent.com/28734497/42926137-cae2ebc0-8b30-11e8-9837-0f875f57c7ed.jpg)

To finish now I'm able to open my vault from the Fedora desktop application
![resolved](https://user-images.githubusercontent.com/28734497/42925877-f4216206-8b2f-11e8-8165-f77cb68b80c5.png)

**Comment by perry-mitchell** [comment]
It sounds like your desktop application may be out of date. Can you please update it to the latest version and confirm that you’re running 1.8.0?

**Comment by EagleEnergy** [comment]
I have update the desktop version to 1.8.0 

Now i'm not able to save new credential by using Firefox extension (version 1.10.0)
![unable to save](https://user-images.githubusercontent.com/28734497/42935356-bb3e740a-8b49-11e8-88c1-2b73e33752e4.png)
I have search for updates and try to open my vault twice to refresh nothing has change.

**Comment by perry-mitchell** [comment]
That error isn’t related to our extension, but implies that your file storage host refused your login. The 401 error means that your login details were most likely incorrect.

**Comment by EagleEnergy** [comment]
Ok nice I don't know why but I have remove and add again the vault in the browser extension and now all working fine! 

Thanks for help

**Comment by perry-mitchell** [comment]
Hey good to hear! Sorry about the issue..

**Comment by EagleEnergy** [comment]
It's not your fault, just an update missed.

There are a stable repository to check updates with yum?

**Comment by perry-mitchell** [comment]
@EagleEnergy Unfortunately no, there's no repo for Buttercup releases yet. Update notices will come from the UI, and will direct linux users to the deb/rpm download page. I'm also a linux user, and this is an inconvenience, but there aren't any better options really for electron apps (what we're using).

**Comment by perry-mitchell** [comment]
I'll close this now as the issue was resolved.

**Comment by EagleEnergy** [comment]
I understand I have just asked to verify that I have not miss an information about it 😉
I will check for updates to the futur. Thanks you so much to you, Sallar and contributors for this app it's so cool manage passwords with a private cloud 👍
