### ISSUE TITLE
Copy/Paste credentials

### ISSUE THREAD

**Issue by mgohin** [buttercup/buttercup-browser-extension#156]
Hi there,

just come back from a conversation on Twitter and filling a feature request that you probably have in your todos ;)

I'd like to be able to copy/paste a login or a password. Sometimes the form-fill does not work and I don't have the buttercup icon to select a combination login/password.

There is this option in LastPass and I really miss it because I waste too much time for local website with no form-fill.

Thanks ;)

**Comment by perry-mitchell** [comment]
I like the idea. Thanks!

**Comment by perry-mitchell** [comment]
Done and available in 2.0.
