### ISSUE TITLE
Adding archive failed: t is null

### ISSUE THREAD

**Issue by cwmke** [buttercup/buttercup-browser-extension#164]
Firefox Linux - 61.0.2 (64-bit)
Buttercup Extension - 1.11.0
Nextcloud Server - 13.0.5

I successfully login to Nextcloud but I receive the below `t is null` error after selecting the file and entering the password. I checked Nextcloud's logs and everything looks good. The bottom block shows some warnings when the extension page first loads. 

I attempted the below in a fresh Firefox profile with no other extensions installed.
- Login using both Nextcloud and Webdav options
- Attempted to login and create a new archive, also failed with the same error
- Attempted to have webdav point directly to the existing archive

``` Error: "Adding archive failed: t is null"
makeArchiveAdditionRequestmoz-extension://096f3139-b84a-4752-aeae-9296ed68b301/setup-index.js:1:29105 setup-index.js:1:90329
onChooseWebDAVBasedArchive/</<
moz-extension://096f3139-b84a-4752-aeae-9296ed68b301/setup-index.js:1:90329
```

```
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. setup.html
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: call to eval() or related function blocked by CSP.
```

**Comment by perry-mitchell** [comment]
Hi @cwmke - Thanks for the detailed report. Regarding the `t is null` error, do you have the full stack by any chance, including the full error message?

On the topic of nextcloud, can you reproduce the issue on [Nextcloud's Demo account](https://demo.nextcloud.com/)? If not, it is either:
 * An issue with your Nextcloud server setup
 * A bug that isn't present in the demo servers but only between Nextcloud production servers and Buttercup

When you tried adding an existing archive, was it one created using the Desktop application? Was the error the same?

**Comment by fmommeja** [comment]
Hi @perry-mitchell, 
the error also occurs on Firefox 61.0.2 (64 bits) & Chrome 68.0.3440.106 (Build officiel) (64 bits)
with Buttercup v. 1.11.0 on 
Windows 10 Pro Version 10.0.17134 Numéro 17134

First logging without error on Owncloud,
Choosing Buttercup file on Owncloud,
Error message appears after typing Name and Master Password and clicking on SAVE ARCHIVE:

on Firefox : 
Failed selecting owncloud archive
An error occurred when adding the archive: Adding archive failed: t is null

on Chrome : 
Failed selecting owncloud archive
An error occurred when adding the archive: Adding archive failed: Cannot read property 'getValue' of null

Firefox console attached...
HTH

Kind regards
Frederic
[FirefoxConsole20180826.txt](https://github.com/buttercup/buttercup-browser-extension/files/2321833/FirefoxConsole20180826.txt)

**Comment by SysLunix** [comment]
same thing on Arch Linux, Firefox Buttercup Extension V1.11.0 , Nextcloud instance installed over SSL on Debian 9 server

**Comment by perry-mitchell** [comment]
I was able to reproduce, and I've made a patch. Very sorry about the inconvenience!

The patch will come out as 1.11.1.
