### ISSUE TITLE
Support for Vivaldi (Chrome based)

### ISSUE THREAD

**Issue by awlx** [buttercup/buttercup-browser-extension#169]
I tested the standard Chrome extension on Vivaldi. And it always fails to fill in the username or some times to fill in anything at all. 

So it seems there is some adjustment needed.

**Comment by perry-mitchell** [comment]
Hi @awlx - Thanks for posting. Vivaldi is not on our support schedule at the moment, so I'll have to close this issue. We don't have the bandwidth right now to support addition browsers outside the most popular ones.. for instance:

![image](https://user-images.githubusercontent.com/3869469/45213277-c20d5d00-b29f-11e8-9719-ae53e990489a.png)

Seeing how Vivaldi is Chrome based, however, I don't suspect that what you're experiencing is limited to Vivaldi only. If you can replicate the detection problem in Chrome, or if it's a select group of sites that still have problems with form recognition, you should consider making an issue [here](https://github.com/buttercup/locust) - this is our login form detection library. It could just be an issue with recognition there.

We will eventually support more browsers like Vivaldi, possibly, but we'd want full-time quality assurance personnel beforehand.
