### ISSUE TITLE
Auto-lock after configurable time

### ISSUE THREAD

**Issue by awlx** [buttercup/buttercup-browser-extension#171]
It would be nice to have a timer which auto-locks Buttercup after time X. And asks for the Archives password next time you are accessing it.

**Comment by Zjemm** [comment]
is there any idea on when this will be implemented? it is kinda insecure to allways have the vault unlocked

**Comment by perry-mitchell** [comment]
Completed in #231

**Comment by perry-mitchell** [comment]
Released in 2.4.0
