### ISSUE TITLE
Credit card saving

### ISSUE THREAD

**Issue by jookk** [buttercup/buttercup-browser-extension#172]
Possibility to save credit card informations, such as number, date, cvv code.

**Comment by neojp** [comment]
This is now possible through the new **Managing Vault** feature. There is currently a bug that prevents this feature from saving to the archive though. https://github.com/buttercup/buttercup-browser-extension/issues/253

![image](https://user-images.githubusercontent.com/127994/61168161-5a531e80-a50f-11e9-8a4d-b7c87e46ba08.png)

![image](https://user-images.githubusercontent.com/127994/61168151-34c61500-a50f-11e9-9e66-09c4e04375d8.png)
