### ISSUE TITLE
Unable to access via WebDav (Seafile)

### ISSUE THREAD

**Issue by imkwx** [buttercup/buttercup-browser-extension#174]
Hi ! 👋🏼

I experience some trouble to add a new vault with webDAV.

Some background: Running an instance of seafile with seafdav(webdav module) enabled and an nginx reverse proxy in front of it, I can access it from my browser without trouble and add a vault from this source.

NOW : I run a second instance, exactly the same, configuration of both nginx and seafile is the same, login via browser not a problem but this time unable to add a vault from this source!

Tried everything I could, debugged via CURL (and I could access the webdav without trouble on the "faulty" instance), I'm not able to make it work. Meeh.

Oh, yeah, I'm using Firefox and Firefox Nightly to test this, browser side.

The only error I get in the browser is this:

```
[error] WebDAV failed to connect: getValueForKey(...) is undefined; can't access its "filter" property setup-index.js:1:85071
[error] Failed establishing WebDAV connection: https://domain.tld/seafdav
```

If you think this does not have anything to do with the extension please feel free to tell me and to close the issue !

Have a great day and thanks for the awesome project !

**Comment by perry-mitchell** [comment]
Hi @imkwx - Sorry for the long delay! Can't say for sure if it's us or not.. The error is quite vague.

Is there any way we could test against your second instance ourselves? Is it public or available as an image?

**Comment by imkwx** [comment]
Hi,

No worries !

Hmmm, I could create you an account on the instance for you to try things out ! It is accessible online.
Do you mind if we see this in private ?

Thanks !

**Comment by perry-mitchell** [comment]
Hi @imkwx - So I've tested this and can confirm that it's not working, of course. I've also checked on the desktop app and it breaks there as well. I believe this is due to the core WebDAV client module [webdav-client](https://github.com/perry-mitchell/webdav-client) not being able to parse the response. The request looks correct, and your host does indeed return a webdav-like response.. but it just doesn't seem to be parseable by that library (which I wrote). I'll make an issue there.

**Comment by perry-mitchell** [comment]
Depends on perry-mitchell/webdav-client#109

**Comment by perry-mitchell** [comment]
@imkwx Version 1.12.0 is out with the updated WebDAV version - Can you please:

1. Confirm you have this version
2. Check to see if this issue is gone?

Thanks!

**Comment by imkwx** [comment]
Hello !
Sorry for the delay !
For now, I don't have the 1.12.0 version ! Do I have to force the install? or like manually install it ?

Thanks !

**Comment by perry-mitchell** [comment]
@imkwx It seems that Mozilla have not yet reviewed our 1.12 release. I'm used to Chrome's release process which only takes an hour. Let's see when it goes live :)

**Comment by perry-mitchell** [comment]
@imkwx Just received a notification from Mozilla - 1.12.0 should be live. Please give it a moment to update :)

**Comment by imkwx** [comment]
Hey @perry-mitchell !

I can confirm that it is now fully working !

Thank you so much for your help !

**Comment by perry-mitchell** [comment]
@imkwx Thanks for being super helpful and patient! It made this much easier. And now we have Seafile support, thanks to your issue. Cheers mate!
