### ISSUE TITLE
some usability improvements

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-browser-extension#178]
I didn't know, if I should create different issues, but I hope it's ok this way, too.

## Suggestions:

- [x] don't show "Save new login?" if all vaults are locked or if no vaults exist. It's very disturbing for people who unlock their vaults only when needed or didn't have added any vaults.
- [x] don't open the tab for unlocking vaults automatically on browser startup or make an entry in settings to opt-out this behaviour.
- [x] the workflow would be more fluently if some forms could be submitted by pressing the enter key. One example is the "add vault page" after the user has typed a password for the vault into the textbox.

**Comment by perry-mitchell** [comment]
Hi @julianpoemp! Sorry for the long delay.

> the workflow would be more fluently if some forms could be submitted by pressing the enter key. One example is the "add vault page" after the user has typed a password for the vault into the textbox.

Agreed, I've created issue #179 for it.

> don't open the tab for unlocking vaults automatically on browser startup or make an entry in settings to opt-out this behaviour.

Already an issue for this - #159

> don't show "Save new login?" if all vaults are locked or if no vaults exist. It's very disturbing for people who unlock their vaults only when needed or didn't have added any vaults.

This could be added as an option, as we also support unlocking vaults while the save page is open (in case you forgot to unlock). I've created #180 for this.

**Comment by perry-mitchell** [comment]
Great suggestions!

I'll close this issue now if that's OK, as we have more on-point places to discuss each of your suggested changes.

**Comment by julianpoemp** [comment]
ok, thank you very much!
