### ISSUE TITLE
Problems with field detection in some websites.

### ISSUE THREAD

**Issue by MyNameIsTroll** [buttercup/buttercup-browser-extension#188]
I have problems on some websites login fields are not detected, in other sites (usually with pop-ups to connect) no field is recognized. Sometimes it also displays the buttercup logo on search fields.

Here are some pictures to illustrate my point:

![screenshot_2018-10-30 yggtorrent - 1er tracker bittorrent francophone](https://user-images.githubusercontent.com/31790025/47785357-693acd80-dd00-11e8-8e60-2414adb90f62.png)
![screenshot_2018-10-30 connexion - funkwhale 101](https://user-images.githubusercontent.com/31790025/47785358-693acd80-dd00-11e8-92d6-709fad29ef4c.png)
![screenshot_2018-10-30 reddit](https://user-images.githubusercontent.com/31790025/47785361-69d36400-dd00-11e8-8401-fb4dce126e31.png)
![screenshot_2018-10-30 riot 1](https://user-images.githubusercontent.com/31790025/47785362-69d36400-dd00-11e8-83c8-83c80fe2864c.png)

**Comment by perry-mitchell** [comment]
Hi! I hear you. Every website is built differently, it's not totally practical to think that one implementation will handle every possible occurrence. That being said, we patch broken sites as we see them - please file issues for sites over at the [locust](https://github.com/buttercup/locust) repo.
