### ISSUE TITLE
Dropbox connection never completes UI loading procedure (spinner)

### ISSUE THREAD

**Issue by jokeyrhyme** [buttercup/buttercup-browser-extension#190]
Howdie, thanks for sharing this fascinating and useful project! Yay!

Desktop v1.10.3 connects to Dropbox and create / open vault files just fine
Firefox extension v2.0.0 and Chrome extension v2.0.0 will connect to Dropbox okay, but seem unable to create / open any vault files (or even display them in the list)

The Chrome DevTools shows exactly one message in the Console

> [info] Received dropbox directory contents: / -> Array(0)

And there's the spinner in the "Choose or Create Vault" picker, that's where it stops and I can't seem to get any further

Is Dropbox connectivity working for anyone else? I think I might be doing something wrong, hmmm ...

**Comment by jcrjaci** [comment]
Same here.
My chrome DevTools looks like these:
![image](https://user-images.githubusercontent.com/3009975/48071471-5168bb00-e1d2-11e8-927f-4fa7bd800995.png)

**Comment by Raik0** [comment]
Also getting this issue.

**Comment by perry-mitchell** [comment]
@jokeyrhyme It seems like your dropbox is empty - Can you confirm that there are in fact files in your account?

@jcrjaci Your response looks correct. Can you explain what you saw in the interface?

**Comment by jokeyrhyme** [comment]
@perry-mitchell I did try it with some files in Dropbox, and I got the same behaviour (just a different item count in the console, more like @jcrjaci 's screenshot

However, today it just started working, and I don't know why
It looks like the same version, so I have no idea what changed

**Comment by Raik0** [comment]
This is from firefox:
![capture1](https://user-images.githubusercontent.com/15350298/48337307-848bce00-e65a-11e8-9f65-c7d05058e3d9.PNG)
it allows you to log into Dropbox but then after it hangs:
![capture2](https://user-images.githubusercontent.com/15350298/48337382-b9982080-e65a-11e8-9f5f-1e574bbd41fe.PNG)

**Comment by jcrjaci** [comment]
> @jcrjaci Your response looks correct. Can you explain what you saw in the interface?

An infinite loading..

![image](https://user-images.githubusercontent.com/3009975/48337912-3081e900-e65c-11e8-8f4c-77dad7c45c6b.png)

**Comment by perry-mitchell** [comment]
I can't reproduce this with Firefox or Chrome. @sallar ?

**Comment by Raik0** [comment]
Can confirm I'm still getting the issue on a fresh install of web browsers and a fresh windows 10 in a VM.
Same as above.

**Comment by perry-mitchell** [comment]
Neither @sallar or myself have been able to reproduce this. It'd be super helpful if someone here with the issue would be able to debug the issue and figure out why the results aren't rendering.

You'd want to inspect both the background script for Buttercup and the tab where the connection is taking place.

**Comment by jcrjaci** [comment]
@perry-mitchell here are some screenshots with google errors and the backgrounds debug.
![image](https://user-images.githubusercontent.com/3009975/48424945-b3d63400-e75b-11e8-81d1-23f30ac2a659.png)

![image](https://user-images.githubusercontent.com/3009975/48425539-f51b1380-e75c-11e8-9249-ec9325990b79.png)

**Comment by perry-mitchell** [comment]
Thanks @jcrjaci, but that first image shows no issue (background) and the second image shows regular debugging notifications that come from the state management system we use (no issue there).

For the issue to continue we would need either:
 * A user who has the issue can debug the JavaScript side of things to find out why the component is not completing the load
 * Access to a machine that can reproduce the issue (this is usually much harder as it would require someone to trust us to remote in to their machine to try and reproduce). This is interesting because we have no idea if it's even reproducible with another account.

I'm not sure what else we can do here. Definitely open for suggestions and please to continue to send us screenshots/console messages if you think you've spotted anything that could help 😊

**Comment by perry-mitchell** [comment]
#192 is about to go out.. Hopefully this helps.

**Comment by Meerparkvogels** [comment]
I have the same issue: Windows 10, Firefox 63.0.1 I am not an experienced debugger, so I cannot give anymore details. I am sorry.

**Comment by perry-mitchell** [comment]
This relates to #194 on webdav services, so it seems that it may not be related to dropbox.

**Comment by luisrodriguezmty** [comment]
I try to log in with dropbox and just keep thinking ... I tried everything and the problem continues to present itself. Any solution?

![captura de pantalla 2018-12-12 a la s 7 37 59 a m](https://user-images.githubusercontent.com/45822568/49873473-9390a800-fde1-11e8-9979-a219aeb56482.png)

**Comment by jokeyrhyme** [comment]
I've been fine with 2.1.2 in both Chrome and Firefox browsers for a while now, and even 2.1.1 seemed to eventually fix itself somehow
It may be worth playing around with having different numbers/combinations of files/folders in the root of your Dropbox

**Comment by morojgovany** [comment]
> It may be worth playing around with having different numbers/combinations of files/folders in the root of your Dropbox

Thanks it worked for me, I had the bug reproducible with only one file (pass.bcup) at the root of my webdav, adding one folder and one file and it is gone.

**Comment by luisrodriguezmty** [comment]
> También tengo el mismo problema por un tiempo ahora.
> 
> Para Firefox puedes usar versiones anteriores v1.12.1 funciona perfectamente. 
> https://addons.mozilla.org/en-US/firefox/addon/buttercup-pw/versions/
> 
> No tengo Chrome instalado, pero probablemente también haya una forma de usar una versión anterior en Chrome.



> I also have same issue for a while now.
> 
> For Firefox you can use older versions v1.12.1 works perfectly.
> https://addons.mozilla.org/en-US/firefox/addon/buttercup-pw/versions/
> 
> I don't have chrome installed, but there probably is a way to use older version on chrome as well.



I have manually installed version 1.12.1 and it worked without problem, I hope that soon they will solve the problem in the most recent version. Thanks for the tip!

**Comment by perry-mitchell** [comment]
Available in 2.1.3
