### ISSUE TITLE
WebDAV connector gets stuck after directory listing

### ISSUE THREAD

**Issue by vmsh0** [buttercup/buttercup-browser-extension#194]
Hello,

I'm trying to set up Buttercup v2.0.0 with WebDAV. I have a remote server up and running and it's working fine with the desktop client. However, on both Firefox and Chrome, the plugin gets stuck after getting the directory listing (which, as you can see, it gets just fine - see attached screenshot.)

![screenshot 2018-11-22 13 32 25](https://user-images.githubusercontent.com/1955497/48903295-65135300-ee5b-11e8-98b2-4ed81afadd68.png)

**Comment by perry-mitchell** [comment]
Hi @vmsh0 - This is a known bug. I'll keep this issue open as it relates with webdav and others with dropbox - #190

Currently we've not been able to reproduce this so we're hoping someone can do some further debugging.

**Comment by vmsh0** [comment]
> Currently we've not been able to reproduce this so we're hoping someone can do some further debugging.

Can we maybe establish contact on Telegram or some other form of instant messaging? I'd like to deploy the plugin on ~10 PCs but I need this bug straightened out first, and I'll be glad to help!
I have limited experience in JavaScript development (and Chrome dev tools), but I think it will be enough to pinpoint the issue.

**Comment by perry-mitchell** [comment]
@vmsh0 Sure! I'd really appreciate that. I'm not sure how the debugging would go within the devtools only, and it may be necessary to build a development version of the extension. You'd need nodejs 8 or 10.

With regards to telegram/contact - Sure, we can connect. Are you on twitter or keybase though? Might be easier to do that than share any email etc. here.

**Comment by vmsh0** [comment]
> @vmsh0 Sure! I'd really appreciate that. I'm not sure how the debugging would go within the devtools only, and it may be necessary to build a development version of the extension. You'd need nodejs 8 or 10.
No problem! As long as you can help me out with that.

> With regards to telegram/contact - Sure, we can connect. Are you on twitter or keybase though? Might be easier to do that than share any email etc. here.
Nope, sorry. Drop me an email to this temp address: bula@rsvhr.com, I'll reply from my actual email address.

**Comment by svenvdvoort** [comment]
Hey there, just wanted to say that i'm experiencing exactly the same issue, also with a WebDAV server. My installation of the extension was actually a fresh 2.0.0 install. The server used to work with a old v1.x.x install on another machine. I would be happy to give you some help, i'm a beginning JS developer.

**Comment by vmsh0** [comment]
@perry-mitchell Did you get the chance to send the email yet?

**Comment by perry-mitchell** [comment]
@vmsh0 Sent! Sorry for the delay, busy times lately.

**Comment by fotofiete** [comment]
@perry-mitchell I flicked you a message via twitter just for the case that you need further debug information!

**Comment by gordroid** [comment]
Hi, can someone test if v2.1.3 fixes this issue? Cheers!

**Comment by fotofiete** [comment]
works perfectly! Thanks a lot for the effort!

**Comment by svenvdvoort** [comment]
Yes fix is also working for me. Seems like the issue is gone completely 🎉
