### ISSUE TITLE
Failed reading remote file of home directory on linux

### ISSUE THREAD

**Issue by daniellindemann** [buttercup/buttercup-browser-extension#201]
Hello,

I tried to use the new feature and want to add a key vault from my computer. I'm using linux as OS (elementary OS) and Chrome as browser. After authorizing I want to choose the key vault, but I got this error when opening my home directory:
```
Failed fetching directory contents
Failed fetching the remote contents of '/home/dl': Failed reading remote file: /home/dl
```

Can you help me?

**Comment by perry-mitchell** [comment]
Hmm.. Are the permissions correct for your home directly, as well as the ownership? It sounds as though Buttercup desktop cannot access your home directory when using the secure host.

You could also run Buttercup desktop from the command line so you can see the log output, and try the process again. Please share any errors or warnings you might see.

**Comment by daniellindemann** [comment]
ok, thanks for the info. changed the permissions. now it works. thanks for the input :smile:
