### ISSUE TITLE
Disabled auto unlock vaults not working

### ISSUE THREAD

**Issue by toniobido** [buttercup/buttercup-browser-extension#202]
Hi, 
With Firefox and Chrome on Windows and Linux when the "Vaults Auto unlock" setting is off, the unlock page opens when the browser starts.

is it normal or should I do something more ?

**Comment by perry-mitchell** [comment]
This seems like regression. Sorry!

Something must be wrong with reading the setting.

**Comment by julianpoemp** [comment]
same problem here with Chrome and Firefox on MacOS and Windows.

**Comment by perry-mitchell** [comment]
Released a fix for this in 2.2.0.

**Comment by julianpoemp** [comment]
@perry-mitchell it works very fine, thank you!
