### ISSUE TITLE
Failed Saving Credentials (Dropbox)

### ISSUE THREAD

**Issue by nossus2** [buttercup/buttercup-browser-extension#203]
Failed saving credentials
Failed adding new entry: Request failed with status code 400

Error message when adding a new entry from Buttercup extension to Dropbox through Safari or Chrome, using extension 2.1.1.

![2018-12-01_li](https://user-images.githubusercontent.com/17791240/49331793-b95fb680-f570-11e8-92e0-09874dd800f9.jpg)

**Comment by perry-mitchell** [comment]
Confirmed. Dropbox is quite picky in terms of content type headers:

![image](https://user-images.githubusercontent.com/3869469/49381948-cff74080-f71d-11e8-952e-39ca46436dfb.png)

We're actually performing part of the preflight fixes:

![image](https://user-images.githubusercontent.com/3869469/49382083-21073480-f71e-11e8-8135-93a3bc4db678.png)

But for some reason the content type is wrong. It is actually [implemented to work correctly](https://github.com/buttercup/dropbox-client/blob/master/source/requests.js#L72), so we'll need to check this out.

**Comment by perry-mitchell** [comment]
May be related to https://github.com/axios/axios/issues/362

**Comment by jmvallejo** [comment]
Creating a new vault from the extension is also failing:

![image](https://user-images.githubusercontent.com/14879937/49490573-b12ca300-f81e-11e8-90e0-2e97a47607e1.png)

Got here after listening to the changelog, would be glad to offer some help but just started looking at the code. Nice job guys :)

**Comment by perry-mitchell** [comment]
Sorry everyone! This is a known issue we’re patching now. Apologies for the instability.

**Comment by perry-mitchell** [comment]
Released in 2.1.2

**Comment by perry-mitchell** [comment]
Should be fixed in 2.1.2
