### ISSUE TITLE
Unable to open vault on network shares or drives other than C:\

### ISSUE THREAD

**Issue by stevenhorner** [buttercup/buttercup-browser-extension#206]
I have installed the Windows Desktop version and enabled browser access, but my .bcup archive is saved on a network share. I can not see the network share when trying to browse my computer for the archive in the browser. I tried creating a file link to it but that isn't shown in the the browser either.

Is there no way to access a windows network share from the Browser extension?

Keeping the file on a network share seamed like the best option without saving it to a cloud service, also testing on my Nextcloud but also issues with that.

**Comment by perry-mitchell** [comment]
This is related to buttercup/buttercup-desktop#708 as we need to provide access to other drives. This isn't an issue with Mac/Linux as there's only one root. Windows obviously has drive letters which are a pain. 

Definitely agree that we need to support this. Sorry for the inconvenience!

**Comment by AndreasFurster** [comment]
Do you know when you implement this feature? Or is there a temporarily workaround?

Could it be possible to just add a textbox to paste in the absolute file location instead of a file explorer? Would that solve te problem on the short term?

**Comment by perry-mitchell** [comment]
@AndreasFurster Support would first have to be added here: https://github.com/buttercup/secure-file-host - Once that supports other drive handles, support could be added in this repo after that. Please note that implementation should take great care not to break other operating systems where drive letters are not necessary.

> Could it be possible to just add a textbox to paste in the absolute file location instead of a file explorer?

No, it's not as simple as providing a file path unfortunately.

We'd accept a contribution for this feature, but we don't currently have time to handle it ourselves right now.

**Comment by neojp** [comment]
Once buttercup/secure-file-host#4 lands, you should be able to access network shares as long as you mount them as drives.

**Comment by eandersons** [comment]
Until support for drives other than C:\ on Windows is added some synchronisation tool could be used as a temporary workaround (i.e. Syncthing (SyncTrayzor) or robocopy) if it is not too much trouble to set it up.
For those who store their Buttercup archives on drives other than C:\ and use Nextcloud *Add Folder Sync Connection* (this button is in Nextcloud desktop app account settings window) also may be used as a workaround.

**Comment by andgar2010** [comment]
If they use Owncloud or NextCloud save different drive, I found a solution:
open Buttercup extension in browser, choose WebDAV option:
type url: http://{{domin_ownCloud/nextCloud}}/remote.php/webdav
and enter your ownCloud or nextCloud credentials. 
then open your buttercup file in WebDAV.

**Comment by ZTiKnl** [comment]
What is the status on this?

I have mounted a network share as a drive on Windows 11, and enabled 'Secure File Host' in the Buttercup Preferences.
When going to the Chrome Browser Extension and clicking on Add Vault -> Local File, all I can see is contents on the C: drive and no way to select a different drive.

**Comment by achimismaili** [comment]
Some ideas for workarounds, but please don't close this issue...

- [set up webdav sharing](https://medium.odrive.com/how-to-easily-setup-a-webdav-server-on-windows-and-sync-to-it-8469b9259435) on windows for the buttercup target folder on the other drive.

- if the requirement is just to store the vault on a different hard disk than the system disk on windows, [map the hard disk just as a sub folder instead of an extra drive in windows](https://www.windowscentral.com/how-mount-hard-drive-folder-windows-10).

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
