### ISSUE TITLE
add-vault page: reusable credentials for owncloud, nextcloud, webDAV

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-browser-extension#209]
### Situation
Some people (like me) use more than one vault. For example I use three different vaults hosted on the same owncloud. I set the data for one vault (host, password, name etc.) and add this to my list of vaults. After that I want to add a new vault.

### Problem
After adding the vault before I have to type in all credentials each time I add another vault. If I have three vaults and 4 different browsers (2 each PC), I have to type in the credentials 12 times.

![bildschirmfoto 2018-12-12 um 17 15 13](https://user-images.githubusercontent.com/25926588/49883346-ce6efc00-fe32-11e8-9547-8df81bc557a5.png)

### Solution
It would be really useful to have the credentials saved for e.g. ca. 5 Minutes. In this time the vaults could be added without typing the credentials over and over again. If this is not possible it would be already helpful to have the remote URL and username saved.

**Comment by perry-mitchell** [comment]
Great idea! We could even make it possible to add another vault from the same source if it's unlocked..

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
