### ISSUE TITLE
[Popup] Text overflow layout issues

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-browser-extension#214]
Layout issues occur with items whose archive has a long name.

![image](https://user-images.githubusercontent.com/3869469/50575172-55dfd780-0e01-11e9-93ab-77a9655655ab.png)

**Comment by ttamminen** [comment]
I get this on a long name entry when using the latest (2.3.0) version.

![popup](https://user-images.githubusercontent.com/1038081/51190166-e6c6b080-18e1-11e9-89a3-7668103ae56e.gif)

**Comment by perry-mitchell** [comment]
Woah.. I think the orginal issue got fixed but that's new - @sallar

**Comment by sallar** [comment]
Oh damn, I didn’t think far ahead :(

**Comment by ttamminen** [comment]
You guys are quick on fixing things! Good job!

**Comment by perry-mitchell** [comment]
We won't release immediately as we don't want to continually flood users with updates. It'll either go out with another fix or feature, or it'll be released in a day or two.

**Comment by perry-mitchell** [comment]
Released in 2.3.1
