### ISSUE TITLE
Autofocus extension popover search input upon opening

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-browser-extension#216]
Hi all,

Hope you're well

Thanks for software

As title

Screen shot/cast:

![kapture 2019-01-04 at 12 12 10](https://user-images.githubusercontent.com/1715809/50685609-2821ab00-101a-11e9-8359-583933f0849b.gif)

If you're reading this and:

a) agree, then please up-vote and/or reply +1, or;
b) disagree, then I'd love to know why?

If you have any issues (e.g. questions/queries) happy to help

Keep up splendid work!

Yours hopefully

**Comment by perry-mitchell** [comment]
I agree - This sounds like an obvious feature we should have.

**Comment by perry-mitchell** [comment]
Released in 2.3.1
