### ISSUE TITLE
some input fields are not recognized by buttercup

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-browser-extension#218]
I don't know why this does happen but there are some pages with login forms not recognized correctly by the buttercup addon. There is no buttercup icon next to the input field for the login name.
One example is https://kunde.comdirect.de/lp/wt/login:

![image](https://user-images.githubusercontent.com/25926588/50728488-e59bc380-112a-11e9-9ad5-713f35865108.png)

**Comment by julianpoemp** [comment]
Thank you very much!

**Comment by julianpoemp** [comment]
Thank You! 😄

**Comment by perry-mitchell** [comment]
Unfortunately we weren’t able to detect the submit button, due to how Locust detects them and the language. This might need to be changed in an upcoming version.
