### ISSUE TITLE
Nextcloud connect from Chrome plugin impossible

### ISSUE THREAD

**Issue by htc1977** [buttercup/buttercup-browser-extension#222]
Hello,
I just tried to initiate a first connection from Buttercup Chrome plugin to three different Nextcloud instances.
May latest test was on demo.nextcloud.com and even that one failed

`Failed connecting to 'nextcloud' resourceA connection attempt to 'https://demo.nextcloud.com/thoon3ai/' has failed: Connection failed to WebDAV service: https://demo.nextcloud.com/thoon3ai/remote.php/webdav`

### Version and info
**Version**
2.2.0
**Browser**
name: Chrome
version: 71
fullVersion: 71.0.3578.98
os: Linux

What can I try or do to get this thing working? I tried WebDAV and Nextcloud connect, both without success.

![error](https://user-images.githubusercontent.com/6369358/50956401-da92bb80-14bb-11e9-87d4-0f2cf221ce37.png)

Thanks in advanced,
htc.

**Comment by perry-mitchell** [comment]
Hi!

This is similar to #205, and _may_ be solved by #197. Essentially Nextcloud is broken when it comes to CORS, and being that the browser extension must obey CORS policies, we're stuck right now.

If you can edit your server's Apache or Nginx config to add CORS headers, we'd suggest doing that. If not, I'm afraid you'll have to wait for that feature to be implemented. Unfortunately this is not an uncommon issue and it's forcing us to re-think the Nextcloud integration.

Please watch those issues in the mean time.. Sorry that this isn't working for you.

**Comment by htc1977** [comment]
Unfortunatelly, it doesn't work with those heasers activated, too :(

My config looks like:
```
<IfModule mod_ssl.c>
<VirtualHost _default_:443>
	ServerAdmin webmaster@onex.de

        <IfModule mod_headers.c>
                Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
		Header set Referrer-Policy "no-referrer"
		Header set Access-Control-Allow-Origin "*"
        </IfModule>

	DocumentRoot /var/www/nextcloud/
	<Directory "/var/www/nextcloud">
		Options Indexes FollowSymLinks MultiViews
		AllowOverride All
		Order allow,deny
		allow from all
	</Directory>
[...]

```

**Comment by perry-mitchell** [comment]
@htc1977 I'll reopen this - I'm sorry you're still experiencing an issue with this. I don't currently have time to debug this in detail, but if you're comfortable at all looking around the chrome extension's network requests, we'd really appreciate any additional logging you could provide. If you should share any _non-secure_ information about the requests in action it might help.

**Comment by SamuelNitsche** [comment]
I have the same issues. The nextcloud logs provide no information. Console looks exactly as @htc1977's. I use Nextcloud version 15.0.2

**Comment by htc1977** [comment]
is there anything further I can do to help debugging this issue?

**Comment by perry-mitchell** [comment]
@htc1977 You can try forcibly setting CORS headers on your own host, if you have one. This would help us confirm that it's a CORS issue, and would perhaps help us formulate some instructions for new users.

Unfortunately this isn't an issue with the extension - it's a security problem that remains unaddressed (in my opinion) on both ownCloud and Nextcloud. I'm not up to date on their docs but they _should_ provide access to browser-based clients, like us.

**Comment by bloodsplatter** [comment]
@perry-mitchell I know how to force headers in my nginx server, but I don't know enough about CORS to know which headers I need exactly. Is there an article on this so I can test this for myself?

**Comment by perry-mitchell** [comment]
@bloodsplatter You can read about it here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#The_HTTP_response_headers

Basically, returning `Access-Control-Allow-Origin: *` will do it.

**Comment by bloodsplatter** [comment]
> 
> 
> @bloodsplatter You can read about it here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#The_HTTP_response_headers
> 
> Basically, returning `Access-Control-Allow-Origin: *` will do it.

It sort of works, but I get a basic authentication pop up now from time to time. And sometimes I get it multiple times. It seems that either some behaviour will have to be changed or some more headers are required.

**Comment by boris779** [comment]
Same problem here, in firefox it works, in chrome or chromium not.

**Comment by claystation** [comment]
I have added the Access-Control-Allow-Origin to my Nginx reverse proxy.
Setup is like: Nextcloud docker, reachable through a Linuxserver.io Nginx/Letsencrypt container.

Verified the header is present on response. Still no luck. Any other solutions?

**Comment by reuterbal** [comment]
I am using Firefox 66.0.4 on Ubuntu 16.04/18.04. I am experiencing the same issues when trying to connect to my Nextcloud.

I have added the Access-Control-Allow-Origin Header to my Apache configuration and verified that the header is sent to the client (see screenshot below)
![Screenshot from 2019-05-10 09-47-39](https://user-images.githubusercontent.com/6384870/57511191-fe023180-7308-11e9-82d2-aae75ca1c8bb.png)

**Comment by perry-mitchell** [comment]
@reuterbal I can't see that the `Authorization` header is sent in that request from the client, when it should. Had you entered your username and password before attempting to connect?

**Comment by reuterbal** [comment]
Thanks for your response!

The Authorization header is indeed missing when I am logged in to my Nextcloud instance in another browser tab. Instead, it seems that this cookie was provided instead of sending the authentication details. 
Thus, I tried the following:
1. Logged out of Nextcloud
2. "Add Vault" in Buttercup Browser Extension
3. Selected Nextcloud
4. Provided URL, username, and password
5. Clicked "Connect"
6. I was immediately prompted for credentials again with a Basic Auth window
7. Entered credentials into basic auth window
8. Vault was successfully added

It was unexpected that I had to log out from Nextcloud before I could add the vault.

**Comment by perry-mitchell** [comment]
It's weird, but ownCloud and Nextcloud have typically done similar things on occasion for me too. The basic auth window is hideous and makes integrating a pain. I can't explain why it happens - The credentials should **always** be sent with the request - the [webdav-client](https://github.com/perry-mitchell/webdav-client) library I maintain sees to that. If you take a look you'll see the implementation is quite basic - a username + password are provided and they are attached with each request.

**Comment by reuterbal** [comment]
That is really strange and sounds like a Firefox issue. Unfortunately, I don't know anything about browser plugins etc. thus I have no idea what to do about that.

**Comment by Claywd** [comment]
Having the same issue. Nextcloud is working for iOS and MacOS apps but not the browser extension.

**Comment by perry-mitchell** [comment]
I really don't see this going anywhere unfortunately. Both services have created a huge amount of work for us in terms of integrating and debugging due to CORS issues, and we even deprecated both platforms because of this. I don't, however, really want to leave anyone in the lurch because of this, and we want our existing users to continue using Buttercup with their platform of choice.

The only way around this I can see is via proxy: #276

Once we have such a thing, CORS issues will be a thing of the past (as node will make the requests, not the browser). Closing this in favour.

**Comment by reuterbal** [comment]
In case this helps anyone else: On Firefox I have started to use the [Multi-Account Containers](https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/) extension and put my Nextcloud session in a container. This way it seems to be separated from the "general" cookie and session storage. With that, I haven't had any more log-in problems with the extension or while saving credentials.
