### ISSUE TITLE
[Firefox+Linux] Cannot delete Vaults

### ISSUE THREAD

**Issue by kropveld** [buttercup/buttercup-browser-extension#227]
I created a vault on my home-dir, and later decided to move the vault-file to my owncloud account. I activated the vault there as well. Now I see 2 vaults with the same name, but cannot remove the vault on my home-dir. 
Reinstalling the plug-in did not help. Deleting the file on my home-dir did not help. On my desktop-app I could successfully remove the vault, however.

**Comment by perry-mitchell** [comment]
Are there any error messages? What happens when you try to delete it?

**Comment by kropveld** [comment]
Actually, I moved the vault-file from my experimental owncloud to my production owncloud server. This screencast shows what I did. https://linux020.nl/cld/index.php/s/RDYM2Bk8LqXQYbF/download .

**Comment by perry-mitchell** [comment]
That's very strange. I wonder if it has something to do with the popup? In my firefox (v64) it shows like this:

![image](https://user-images.githubusercontent.com/3869469/51426130-b9824700-1bee-11e9-89d0-9a664eb92dd1.png)

What version of firefox are you using?

**Comment by kropveld** [comment]
**SOLVED**! :) This time I clicked on the name of the vault on the Firefox drop-down menu. Below the passwordfield I noticed a button [Remove Vault]. I clicked on it, confirmed, and now it is gone. Still somebody should find out why it is not possible from the 'Manage Vaults' menu-item...

**Comment by perry-mitchell** [comment]
I might leave this open @kropveld as it's still an issue, I guess. Would you mind commenting with your Firefox version and OS?

**Comment by perry-mitchell** [comment]
For clarity's sake, it seems that when @kropveld "manages vaults" and chooses to remove, the confirmation dialog to delete the vault actually causes the popup menu to close, and the deletion fails (no error but vault remains).

**Comment by kropveld** [comment]
My installation: Ubuntu Mate 16.04, with Firefox 62.0.3 (64-bits). The  vault in question was located on a local network only ownCloud server.

**Comment by perry-mitchell** [comment]
I'm going to close this issue as we've not seen this reproduced in any other environment, nor had anyone else comment that they've experienced the same. 

Please feel free to submit a PR if you can debug/find the issue.
