### ISSUE TITLE
Chose Location of Vault other than on C:

### ISSUE THREAD

**Issue by DerKleineLeif** [buttercup/buttercup-browser-extension#232]
Hello,
it seems that choosing a vault on a different location other than c:\ is not possible. 
Can please add this enhancement.

Thank you advance  
Cheers
Leif

OS: Window 10
Browser: Chrome

**Comment by perry-mitchell** [comment]
This is a duplicate of #206, so I'll close in favour of that. This title is better so I'll update the other issue. Thanks!
