### ISSUE TITLE
chrome has buttercup 2.4.1, but firefox only has 2.4.0

### ISSUE THREAD

**Issue by jokeyrhyme** [buttercup/buttercup-browser-extension#240]
Might be related to #208 

Firefox: 
![image](https://user-images.githubusercontent.com/479816/52842660-e9702c00-3153-11e9-9c89-fc36e740734c.png)

Chrome: 
![image](https://user-images.githubusercontent.com/479816/52842697-04db3700-3154-11e9-861c-9cdfeadf1d73.png)

Oddly enough the Firefox plugin was updated last, but the Chrome plugin is the later version /shrug

**Comment by perry-mitchell** [comment]
It's not related to #208.. I simply forgot to upload it. I'll check this out tomorrow!

**Comment by perry-mitchell** [comment]
This has been taken care of.. Apologies for the lapse!
