### ISSUE TITLE
Issue with Google Drive / Chrome Extension

### ISSUE THREAD

**Issue by sylvainlap** [buttercup/buttercup-browser-extension#244]
Hi,

I installed Google Chrome Extension, and try to get my vaults in my Google Drive.
I authorized Buttercup to access my Google Drive, but, on the "Choose Vault Type" page, when I click on Google Drive, I got this error message: 

Failed fetching directory contents
Failed fetching the remote contents of '/': Cannot read property 'map' of undefined

Google Chrome: Version 72.0.3626.121 (Build officiel) (64 bits)
Buttercup Extension: Version 2.5.0

Regards,
Sylvain

**Comment by perry-mitchell** [comment]
Confirmed.. seems to occur with large Google Drive collections:

![image](https://user-images.githubusercontent.com/3869469/54313806-b9953680-45e2-11e9-977d-d10c4eb9b261.png)

I was not able to reproduce on my personal account, but on my work one (many more files) it broke straight away.

@sylvainlap thanks for reporting.

**Comment by perry-mitchell** [comment]
Released in 2.5.1
