### ISSUE TITLE
Reduced permission for Google Drive

### ISSUE THREAD

**Issue by mykter** [buttercup/buttercup-browser-extension#245]
I was very happy to install this and find Google Drive support - makes using it much lower friction for me.

However it currently requiers full access to Google Drive. This doesn't feel right - the extension should only have access to my vault archive(s), not all my personal documents.

The appropriate [scope](https://developers.google.com/drive/api/v3/about-auth) for this is `https://www.googleapis.com/auth/drive.file`

If buttercup creates the archive I think this is straightforward. But if a user wants to use an existing archive it will require some rework for the flow - I'm not sure how a user gives access to a specific file.

**Comment by perry-mitchell** [comment]
@mykter Well this is no different to how Dropbox access works - We provide access to view the remote as if you were looking at directory contents. It's the same with google drive - we treat it like an actual directory tree.

Our concern with the single-file scope is that:

 * It removes the ability to browse the tree (to my knowledge)
 * It removes the ability to read files that were uploaded manually or previously (bcup files)

I don't think such a scope change would work for us..

**Comment by mykter** [comment]
Thanks for the context. I researched this a little more, and I think it is possible.

The docs reference an example app that uses the drive.file scope plus the drive.install scope, which together allow browsing and reading files that already exist.

> drive.file allows you to either files your app creates or files that the user explicitly opens with your app via the Drive UI or the file picker

refs:
* demo https://zip-extractor.appspot.com/
* https://developers.google.com/drive/api/v3/integrate-open
* https://developers.google.com/drive/api/v3/picker
* https://github.com/gsuitedevs/drive-zipextractor/blob/master/js/zipextractor/config.js & https://github.com/gsuitedevs/drive-zipextractor/blob/master/js/driveapi/driveapi-concat.js
* https://stackoverflow.com/questions/17508212/how-do-i-use-google-picker-to-access-files-using-the-drive-file-scope?noredirect=1&lq=1

**Comment by perry-mitchell** [comment]
The problem with the links you've provided are that they seem to require Google's file picker, which we're not going to use. Apologies if I misunderstand.. We've had enough issues trying to get the auth working across every platform that Buttercup runs on I don't want to try any more of their SDK.

Reducing the permissions would still work fine for files created by us - no problem there, but this still means that files uploaded *manually* to Google Drive will not be visible, which I don't like.

Maybe a switch in the UI could handle this? Users could opt-in for full-perms to browse their full file tree. I can understand that users don't want everything exposed to Buttercup, but this is already the case with Dropbox etc... It's a bit frustrating to have to treat Google Drive as a special case tbh.

**Comment by mykter** [comment]
> Maybe a switch in the UI could handle this? Users could opt-in for full-perms to browse their full file tree.

That sounds like a good option to me.

Regarding Dropbox being different, from their [docs](https://www.dropbox.com/developers/reference/developer-guide) whilst it is a different model, it looks like there is also a better option than asking for full access:

> **App folder**
> A dedicated folder named after your app is created within the Apps folder of a user's Dropbox. Your app gets read and write access to this folder only and users can provide content to your app by moving files into this folder.
> ...
> Your app should use the least privileged permission it can.

**Comment by perry-mitchell** [comment]
I don’t expect we’ll change Dropbox any time soon.. and then again the UI updates everywhere to accommodate such a switch would take a fair bit of effort as we don’t have a common component for it. I think we’ll most likely go with reduced permissions and instruct people to create vaults using google drive via Buttercup - uploaded vault files won’t be supported. Importing would work of course.

**Comment by mykter** [comment]
Oh yes, importing seems like a great alternative to uploading.

**Comment by perry-mitchell** [comment]
Seems this works out of the box. Existing vaults that have been accessed remain accessible to Buttercup:

![image](https://user-images.githubusercontent.com/3869469/71782953-bb543e80-2fe8-11ea-82ec-54def943be6c.png)

_(This was after reducing the permissions scopes)_

This will come out soon. Might even help fix #314.

**Comment by jokeyrhyme** [comment]
Is there an existing issue to track the work on importing existing vaults?

I currently use DropBox as my backend, but was recently trying to switch to Google Drive and found that I cannot get an existing archive to show up in the picker (buttercup extension 2.11.0)

This isn't a blocker for me, and I greatly appreciate and admire all the work that goes into buttercup <3

**Comment by perry-mitchell** [comment]
@jokeyrhyme Hey thanks! We appreciate the sentiment.

You can of course import an exported buttercup CSV, but this is of course rather cumbersome and we definitely need to handle this first-party.
