### ISSUE TITLE
Multiple accounts on same nextcloud-host

### ISSUE THREAD

**Issue by henningjanssen** [buttercup/buttercup-browser-extension#248]
I experienced following problem while adding vault on the same nextcloud-host under different nc-accounts:

I added the first vault on my private nextcloud instance flawlessly. When I tried to add a second vault saved under a different account, I was given the contents of my first account to choose the file. In a private browser window I managed to add the second vault but I was not able to open it with the following error message:
```
Failed unlocking archive
Unable to unlock archive: Unlocking archive source (-sourceid-) failed: Failed unlocking source: -sourceid-: Failed mapping credentials to a source: Request failed with status code 404
```
It looks like sessions are not handled on a per-vault basis to me.

**Version**
    2.6.0

**Browser**
    name: Firefox
    version: 66
    fullVersion: 66.0
    os: Linux

**Comment by henningjanssen** [comment]
I have the same problem in the Android-App by the way, but I think there was a similar issue already open.

**Comment by perry-mitchell** [comment]
I think this is with how Nextcloud stickies accounts in the browser - Once you authenticate with one, even via WebDAV, it seems that it's impossible to use another.

I don't see any solution to this besides #276. We're also no longer tending to Nextcloud/ownCloud issues directly, as they're more often than not an issue with their implementation and not ours. I'll close in favour of that issue.
