### ISSUE TITLE
owncloud: user already logged in on the owncloud's page after unlock

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-browser-extension#249]
### Problem
I unlocked my vault hosted on my owncloud. After I went to my owncloud's web page, a popup asks me about a user name and a password. The ownlcoud page is visible and I see that the user name I entered for the synchronization is already signed in.

### What it should be
The popup should not be opened and the user for the synchronization shouldn't be logged in. Perhaps it has something to do with cookies set in the browser.

### How to reproduce
1. Unlock a vault hosted on an ownlcoud.
2. Go to the owncloud's web page.
3. The Popup should appear and ask about username and password. If you look at the right corner of the owncloud page, you see that the user is already logged in.

### System information

Buttercup Addon: 2.6.0
Browser: Chrome 73.0.3683.103
Owncloud: 10.1.0.4

**Comment by perry-mitchell** [comment]
This is indeed to do with cookies, and it's an issue baked into the core of how ownCloud and Nextcloud work. The only way I see this getting solved is either via #276 (more likely, but requires desktop app), or via #197 (which is more risky/experimental). I'll close in favour of either of those.
