### ISSUE TITLE
Improve horizontal realestate of directory list when adding vaults

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-browser-extension#256]
<img width="1440" alt="Screenshot 2019-07-05 at 08 51 57" src="https://user-images.githubusercontent.com/1715809/60752069-b32b3000-9fc0-11e9-81bc-1a8d1be1b561.png">

Sorry for terseness - new OS install - but wanted to dump this while I remember

Regards

**Comment by sallar** [comment]
Hi @ldexterldesign I transferred your issue to this repository.

**Comment by perry-mitchell** [comment]
Took the liberty of changing the title so it's easier to find later..

**Comment by ldexterldesign** [comment]
@neojp 💯

**Comment by perry-mitchell** [comment]
Released in 2.8.0
