### ISSUE TITLE
Sometimes shows on inputs not meant for logins

### ISSUE THREAD

**Issue by divyanshu013** [buttercup/buttercup-browser-extension#261]
Hi,

I noticed sometimes buttercup button shows up on input fields which are not meant for login (I guess it checks input type `email` which is common in subscription boxes).

Please check the following screenshot:

- From [open collective](https://opencollective.com/):
![Screenshot_2019-07-15 Open Collective - open your finances to your community](https://user-images.githubusercontent.com/6682655/61196674-efac0980-a6ed-11e9-968e-f8fe3f1873eb.png)

Thanks

**Comment by perry-mitchell** [comment]
Hi @divyanshu013 - I've seen this also, but it's something that I've noticed all password managers doing.. And I'd say that it's somewhat deliberate in a lot of cases. For us it's not accidental nor deliberate, but a side-effect of how we detect inputs - like you suggested.

Sure Buttercup is a password manager, but it also remembers all of your accounts. Prefilling an email address could also be done using Buttercup.

I'm not sure if we want to stop this functionality, as attempting to filter certain forms or pages could well do more harm than good. For now we'll keep it as is, but will treat breaking form recognitions on a case-by-case basis. Thanks :)

**Comment by divyanshu013** [comment]
Sounds good, thanks 👍
