### ISSUE TITLE
Password field always visible in popup, not copy-able

### ISSUE THREAD

**Issue by alozacor** [buttercup/buttercup-browser-extension#269]
Hi, I have a problem.
**I am using Chrome browser**. I try to copy the "**user**" or "**password**" data from the Buttercup extension window to paste it into the respective fields of a web page, but the option to paste data does not appear, **I cannot paste the data**.
Sometimes it does let me paste them but the data that sticks does not correspond to the data copied.
I had never had this problem.
In addition, the "password" data is visible in the Buttercup extension window, but should be hidden for added security.
Thanks greetings

In spanish
Estoy usando navegador Chrome. Intento copiar el dato "usuario" o "contraseña" desde la ventana de la extensión de Buttercup para pegarlo en los campos respectivos de una página web, pero no me aparece la opción de pegar dato, no puedo pegar los datos.
A veces sí me deja pegarlos pero el dato que se pega no se corresponde con el dato copiado.
Nunca había tenido este problema.
Además, el dato "contraseña" está visible en la ventana de la extensión Buttercup, pero debería estar oculto para mayor seguridad.

**Comment by ttamminen** [comment]
I have encountered the same problem.

When I hit copy for the password.

![image](https://user-images.githubusercontent.com/1038081/62921327-158e0200-bdb1-11e9-9b45-d5172fb96c9f.png)

The clipboard stays empty, for example, when I try to paste to Notepad.

I use Brave version 0.67.125 with Chromium: 76.0.3809.100 (64-bit)

**Comment by alozacor** [comment]
Thank ttamminen you for exposing it, I thought it was a particular problem of mine.
I also insist that the password is visible when it should not be and that the copy / paste problems are the same in username and password

**Comment by perry-mitchell** [comment]
I've also seen this issue recently, I'll mark it as a critical bug.

**Comment by perry-mitchell** [comment]
This will come out in the next release, most likely tomorrow.

**Comment by perry-mitchell** [comment]
Released in 2.8.2.

**Comment by alozacor** [comment]
now perfect, thanks!!

**Comment by ldexterldesign** [comment]
👋 https://github.com/buttercup/buttercup-browser-extension/issues/338
