### ISSUE TITLE
Feature Request: "Never save password on this site"

### ISSUE THREAD

**Issue by davidfaber** [buttercup/buttercup-browser-extension#272]
It would be awesome if there is a feature like "Never save password on this site" or to have kind of a blacklist, where I can define domain/path-rules that shouldn't save passwords (like *.foo.bar or /wp-admin/*.

This would be so awesome!

**Comment by perry-mitchell** [comment]
I really like the idea. It would, however, need a way to reset this option if a user would like to reset this behaviour.

**Comment by eboye** [comment]
Better yet, I would like to exclude script injection entirely on some websites. Some kind of blacklist.

The problem that I'm having is that on some websites it breaks the input field and/or gets some console error because the website disallows cross origin scripts.

**Comment by perry-mitchell** [comment]
This was done some time ago.
