### ISSUE TITLE
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by n8v8R** [buttercup/buttercup-browser-extension#274]
* BC 2.8.0
* FF 68 | 69 | 70 (all x_64)
* W10 Pro x_64 1903 b18362.295
____
browser console log is spammed with

![Annotation 2019-08-22 172552](https://user-images.githubusercontent.com/13611490/63527730-e9395a80-c501-11e9-986b-f57d60551fdb.png)

**Comment by perry-mitchell** [comment]
Seems to be update spam from the state sync engine we use. We sync state between tabs, the popup menu and the background script. Updates that wrench the background demon away and disconnect the tab/menu connections can cause errors like this.

If we could perform some kind of clean up by detecting an update, that would solve this issue.

**Comment by perry-mitchell** [comment]
Found it - this would provide a way to do better cleanup, at least in FF: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onSuspend

**Comment by perry-mitchell** [comment]
Closing in favour of #292
