### ISSUE TITLE
When dropbox archive path contains non-ascii characters, request will fail with "Value is not a valid ByteString"

### ISSUE THREAD

**Issue by bitmori** [buttercup/buttercup-browser-extension#275]
How to reproduce:
create an archive in dropbox, under path `/秘密`, such error will appear:

<img width="526" alt="Screen Shot 2019-08-22 at 9 40 18 AM" src="https://user-images.githubusercontent.com/2584204/63533048-e10cfb00-c4c0-11e9-9b9b-0ec31d70b71c.png">

Looks like this extension doesn't support Unicode in 2019? /s

Version
  2.8.0
Browser
  name: Chrome
  version: 76
  fullVersion: 76.0.3809.100
  os: OS X

**Comment by perry-mitchell** [comment]
@neonmori It seems so :( - We recently updated our Dropbox client, so I'll file a bug over there. Apologies for the inconveniece!

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
