### ISSUE TITLE
Failed to connect to file host: Use a better error message when unable to connect to file host

### ISSUE THREAD

**Issue by Peppeo** [buttercup/buttercup-browser-extension#277]
Hi,
I have installed Buttercup; exported and imported from Lastpass and created the new archive. When starting the extension (2.8.0) on either Brave or Chrome I am presented with this blank page. Any idea what this might be? Running a Macbook Pro; Brave and Chrome have both been updated to the latest version. Added the extension from the Chrome webstore: 
Version and info
Version 2.8.0
Browser name: Chrome
version: 76
fullVersion: 76.0.3809.100
os: OS X 
Tonight I will check it with Brave on Linux Mint 19.2. Will try Firefox there also. Will update this post accordingly.
Update: indeed, the same result in Firefox and Brave on Linux Mint. 
Any help or clarification would be appreciated. Thanks, Mark
<img width="1440" alt="Screen Shot 2019-08-28 at 14 07 02" src="https://user-images.githubusercontent.com/53419266/63833636-b679e100-c99d-11e9-88a6-ed31ef615f95.png">

**Comment by Peppeo** [comment]
I will close this issue, since it is closely related to the various Nextcloud/WebDAV issues (on their side). 
Solution: Install Buttercup Desktop client (one time process)- Let that create an archive in your **local** Nextcloud folder - Import Lastpass data - instruct browser extension to look for a local .bcup file and fill in credentials - working! Can also save new entries.

**Comment by perry-mitchell** [comment]
@Peppeo When that screen appeared, had you ever added a vault to the extension prior? Seems weird that it'd show like that. There might still be an issue there..

**Comment by Peppeo** [comment]
@perry-mitchell : you might be right. I had added a vault prior indeed. Now I have encountered the following issue (perhaps it is a new one, not sure):
- when starting Brave I am presented with the tab where I fill in my Bcup credentials. I do so, only to get an error message (see below)
<img width="1340" alt="Screen Shot 2019-09-06 at 08 31 39" src="https://user-images.githubusercontent.com/53419266/64394726-b8b8fb00-d081-11e9-8ae2-bf52440f03a4.png">
- Then I open the Buttercup application; close Brave and reopen. After filling in etc. the extension starts as expected (see picture).
- After that I close both Buttercup as well as Brave; restart Brave; fill in credentials and everything is fine. Apologies, the green confirmation notice disappers too quickly for me to make a screenshot :-(

<img width="1415" alt="Screen Shot 2019-09-06 at 08 33 36" src="https://user-images.githubusercontent.com/53419266/64394772-e7cf6c80-d081-11e9-9abb-600a6267d7a9.png">

**Comment by Peppeo** [comment]
Well, back again. On MacOs / Firefox i have the same error. Also on the latest Edge beta.
<img width="1391" alt="Screen Shot 2019-09-18 at 14 55 34" src="https://user-images.githubusercontent.com/53419266/65128972-a4331600-da24-11e9-94f4-f8880f12a89c.png">
Also when I put the .bcup in a local directory, or on Onedrive: the same issue. So I'll reopen. Also wonder if anyone else has this issue. It only runs error-free when the Buttercup application is open at the same time as when opening a browser window. After entering the pasword the extension works fine.

**Comment by perry-mitchell** [comment]
@Peppeo What type of connection did you set up in the latest test? If you're using the local file type then you **need** to have the desktop application running, at least in the background, with local file access enabled.

**Comment by Peppeo** [comment]
@perry-mitchell Apologies for my late response. It must have been something like that, the issue. Of course the .bcup file was on OneDrive, Nextcloud and Drive, but then on the 'local mirror' i.c. my own HD and then in one of those folders. I cannot fully recall but I am certain i did **not** have the application running every time i tried to connect. Back to the drawing board for me; I will run some tests in Chrome today.

**Comment by Peppeo** [comment]
Let's first run a test or three before i close this issue.

**Comment by Peppeo** [comment]
@perry-mitchell that turned out to be the issue indeed. Of course I opened the application at first to make a link. But I did not have the application open after restarting Chrome and typing in the master PWD.
<img width="1210" alt="Screen Shot 2019-10-10 at 15 10 24" src="https://user-images.githubusercontent.com/53419266/66550698-23bd8c00-eb70-11e9-9231-b4fb739a3537.png">
Running the application in the background whilst starting the browser fixed the issue. Another case of RTFM ;-)
<img width="1210" alt="Screen Shot 2019-10-10 at 15 15 12" src="https://user-images.githubusercontent.com/53419266/66551073-eefe0480-eb70-11e9-9f16-ae1af6214574.png">

**Comment by perry-mitchell** [comment]
Thanks for following up! This could be improved with a better error message, perhaps along the lines of “Failed to connect to file host: Check that Buttercup is running and local file access is enabled”..

**Comment by Peppeo** [comment]
Hi Perry, fully agree and changed the title accordingly. Keep up the good work!

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
