### ISSUE TITLE
Generate password pop-up - buttons not visible in Firefox

### ISSUE THREAD

**Issue by pestrickland** [buttercup/buttercup-browser-extension#280]
When trying to generate a new password with buttercup, I cannot easily use the dialog box because the controls are not visible:

![Screenshot from 2019-09-07 12-10-17](https://user-images.githubusercontent.com/4771367/64474169-e6c53a80-d168-11e9-97ce-ef5d8d57e31a.png)

**Comment by perry-mitchell** [comment]
This seems to work on same pages on 2.11.0:

![image](https://user-images.githubusercontent.com/3869469/71992344-ea172280-323d-11ea-9471-9bbef9898d2c.png)

Will keep checking but not sure if it's still an issue.

**Comment by perry-mitchell** [comment]
I'll close for now. If it appears again, please attach a URL/domain where the issue persists.
