### ISSUE TITLE
possible issue with saving non-login entry types, e.g. note

### ISSUE THREAD

**Issue by jokeyrhyme** [buttercup/buttercup-browser-extension#281]
Howdie,

Love your work, thanks!

I just tried out the alternative entry types today, and I got an error toast and the following console entries when I tried to save a "Note" entry:

```
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). setup-buttercup.js:418:2578587
Init call. Do not call onUpdate setup-buttercup.js:214:6096
Debug: Running on Update function. Yay! setup-buttercup.js:214:6162
Error: "Failed applying vault facade: Failed consuming entry data: Expected type "login" but received "note""
    b moz-extension://<UUID>/setup-index.js:1
setup-index.js:74:758307
    saveVaultFacade moz-extension://<UUID>/setup-index.js:74
```

I'm using Firefox 69.0 (64-bit) with Buttercup extension 2.8.2

**Comment by perry-mitchell** [comment]
Thanks @jokeyrhyme! I don't have time to investigate this immediately but we'll be able to look at it over the weekend at the latest.

**Comment by perry-mitchell** [comment]
Closing as I believe this has been solved. Will happily reopen if it's still reproducible.
