### ISSUE TITLE
Failed adding new entry: Failed writing remote file

### ISSUE THREAD

**Issue by eandersons** [buttercup/buttercup-browser-extension#282]
Error message "Failed adding new entry: Failed writing remote file: /path/to/archive.bcup" is displayed when a new entry is added in Chromium browser on Windows 10. Archive file is stored in Nextcloud folder.
Console output:
```
setup-index.js:98
VError {jse_shortmsg: "Failed adding new entry: Failed writing remote fil…trimmed/path/to/archive.bcup", jse_info: {…}, message: "Failed adding new entry: Failed writing remote fil…trimmed/path/to/archive.bcup", stack: "VError: Failed adding new entry: Failed writing re…ieckodmcppbnembejjmabajjjj/setup-index.js:1:70791"}
    jse_info: {authFailure: undefined}
    jse_shortmsg: "Failed adding new entry: Failed writing remote file: /path/to/archive.bcup"
    message: "Failed adding new entry: Failed writing remote file: /path/to/archive.bcup"
    stack: "VError: Failed adding new entry: Failed writing remote file: /path/to/archive.bcup↵    at chrome-extension://heflipieckodmcppbnembejjmabajjjj/setup-index.js:1:70791"
    __proto__: Error
```
Tried to lock and unlock vault in the browser extension, but still the error was shown. Tried to remove and re-add the vault - the same outcome.

It seems like permissions related error, but I have no idea what permissions should be granted as the logged in user has full access to the archive file.

**Comment by perry-mitchell** [comment]
Hi @eandersons - are you able to see the network request in the developer tools? Not sure for your case if you should see it in the open windows’s Console or the background script’s console. If we could get more details on what the actual request/response from your Nextcloud server is, that’d probably help.

**Comment by perry-mitchell** [comment]
It’s important to note that Nextcloud and ownCloud have many issues in how they implement WebDAV - and this is primarily the reason we have issues with these platforms. These platforms don’t perform well when the client is a web application, like our browser extension.

**Comment by eandersons** [comment]
I forgot to mention that vault was added to Buttercup browser extension from a local archive file that is stored in Nextcloud folder therefore I do not think that Nextcloud's WebDAV is involved in this error.

Some additional information:
- OS: Windows 10 (1903);
- browsers where this error was observed  (I guess that this happens in other browsers too):
  - Chromium (75.0.3770.142);
  - Firefox Developer Edition (70.0b5 (64-bit));

Step by step actions:
- submit login information on a web page;
- Buttercup browser extension asks to save information;
- select archive and group and press button "Save New Entry";
- after a short while error is displayed:
  > Failed saving credentials
  > Failed adding new entry: Failed writing remote file: /Users/######/Nextcloud/##žā##/#āļ#/####### ##ū##.bcup

Console output:
- Firefox Developer Edition:
```
Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src"). setup-buttercup.js:418:2578587
setup-index.js:98:4157
{…}
    jse_info: {…}
    authFailure: undefined
    <prototype>: Object { … }
    jse_shortmsg: "Failed adding new entry: Failed writing remote file: /Users/######/Nextcloud/##žā##/#āļ#/####### ##ū##.bcup"
    message: "Failed adding new entry: Failed writing remote file: /Users/######/Nextcloud/##žā##/#āļ#/####### ##ū##.bcup"
    stack: ""
    <prototype>: {…}
        cause: function cause()
        constructor: function VError()
        name: "VError"
        stack: ""
        toString: function toString()
        <prototype>: Object { … }
    saveNewCredentials moz-extension://89a15c48-49b9-49bd-9fd7-2741f390daf7/setup-index.js:98
```
- Chromium:
```
setup-index.js:98 VError {jse_shortmsg: "Failed adding new entry: Failed writing remote fil…s/######/Nextcloud/##žā##/#āļ#/####### ##ū##.bcup", jse_info: {…}, message: "Failed adding new entry: Failed writing remote fil…s/######/Nextcloud/##žā##/#āļ#/####### ##ū##.bcup", stack: "VError: Failed adding new entry: Failed writing re…ieckodmcppbnembejjmabajjjj/setup-index.js:1:70791"}
    jse_info: 
        authFailure: undefined__proto__: Object
        jse_shortmsg: "Failed adding new entry: Failed writing remote file: /Users/######/Nextcloud/##žā##/#āļ#/####### ##ū##.bcup"
        message: "Failed adding new entry: Failed writing remote file: /Users/######/Nextcloud/##žā##/#āļ#/####### ##ū##.bcup"
        stack: "VError: Failed adding new entry: Failed writing remote file: /Users/######/Nextcloud/##žā##/#āļ#/####### ##ū##.bcup↵    at chrome-extension://heflipieckodmcppbnembejjmabajjjj/setup-index.js:1:70791"
        __proto__: Error
            cause: ƒ ()
            name: "VError"
            toString: ƒ ()
            constructor: ƒ VError()
            __proto__: Object
(anonymous) @ setup-index.js:98
Promise.catch (async)
(anonymous) @ setup-index.js:98
(anonymous) @ setup-index.js:45
(anonymous) @ setup-vendor.js:1
handleSaveClicked @ setup-index.js:108
(anonymous) @ setup-buttercup.js:418
ja @ setup-buttercup.js:418
(anonymous) @ setup-buttercup.js:418
wa @ setup-buttercup.js:418
Aa @ setup-buttercup.js:418
ya @ setup-buttercup.js:418
Da @ setup-buttercup.js:418
Ad @ setup-buttercup.js:418
Gi @ setup-buttercup.js:418
Kb @ setup-buttercup.js:418
Dd @ setup-buttercup.js:418
(anonymous) @ setup-buttercup.js:418
exports.unstable_runWithPriority @ setup-buttercup.js:418
Ii @ setup-buttercup.js:418
Cd @ setup-buttercup.js:418

```
Similar error is thrown when vault is opened in browser (click on Buttercup icon in browser's toolbar > click on dropdown "Vaults" > select vault) and entry is added or deleted, but in this case changes seem to be saved, but they are not visible when opened from incognito window, in other browsers or desktop app:
> Failed updating archive
> Unable to update archive (61702dc4-c0f6-46be-8e66-237708e64ad3): Failed applying vault facade: 
> Failed writing remote file: /Users/######/Nextcloud/##žā##/#āļ#/####### ##ū##.bcup"

Console output:
- Firefox Developer Edition:
```
Content Security Policy: The page's settings blocked the loading of a resource at no eval ("script-src"). setup-buttercup.js:418:2578587
Init call. Do not call onUpdate setup-buttercup.js:214:6096
Debug: Running on Update function. Yay! setup-buttercup.js:214:6162
Error: "Failed applying vault facade: Failed writing remote file: /Users/######/Nextcloud/##žā##/#āļ#/####### ##ū##.bcup"
    b moz-extension://89a15c48-49b9-49bd-9fd7-2741f390daf7/setup-index.js:1
setup-index.js:74:758307
    saveVaultFacade moz-extension://89a15c48-49b9-49bd-9fd7-2741f390daf7/setup-index.js:74
```
- Chromium:
```
setup-index.js:74 [info] Making request to background to unlock archive source: f178623e-5332-473c-a122-3b4cdea0f505
setup-buttercup.js:214 Init call. Do not call onUpdate
setup-buttercup.js:214 Debug: Running on Update function. Yay!
setup-index.js:74 Error: Failed applying vault facade: Failed writing remote file: /Users/######/Nextcloud/##žā##/#āļ#/####### ##ū##.bcup
    at setup-index.js:1
(anonymous) @ setup-index.js:74
Promise.catch (async)
(anonymous) @ setup-index.js:74
(anonymous) @ setup-index.js:45
(anonymous) @ setup-vendor.js:1
onUpdate @ setup-index.js:80
(anonymous) @ setup-buttercup.js:214
th @ setup-buttercup.js:418
(anonymous) @ setup-buttercup.js:418
of @ setup-buttercup.js:418
ci @ setup-buttercup.js:418
Di @ setup-buttercup.js:418
Yh @ setup-buttercup.js:418
Ii @ setup-buttercup.js:418
Cd @ setup-buttercup.js:418
```
Could it be that this is because of diacritical characters or space in the Buttercup archive path and file name?
Well, after writing the previous sentence I decided to play with archive file name and location, and the outcome is still the same no matter where the .bcup file is located (I tried C:\Users\######\Downloads, C:\Users\######, C:\Windows) and if it is renamed to a simpler name.
I will later try this on work computer to see if the error occurs on other machines as well.

**Comment by eandersons** [comment]
After I observed the same error in Chromium on macOS, I created a new test archive in the same location as the one in which new entries cannot be added from browser extension and there was no error when I tried to add a new entry from Chromium.
I decided to export passwords from the existing archive, create a new one and import data from .csv. That did not help - still the same error. I imported the exported data also in the test archive - now I could not save new entries from browser in the test archive as well. So it seems that there is something in the initial archive's content that prevents adding new entries from browser extension.
Is there anything I could provide to help find a cause for this behaviour?

By the way, this error occurred quite recently as I remember that previously I could successfully add new password entries.

**Comment by perry-mitchell** [comment]
Thanks for the write up! This will help. I suspect then that the issue is to do with the secure-file-host daemon that is run by the desktop application. Have you got the desktop application running while you try this? It needs to be running, with the local access feature enabled, for local file access to work.

**Comment by eandersons** [comment]
Yes, Buttercup desktop application was running all the time. That usually is the first thing I check when I encounter any error message in Buttercup browser extension.

**Comment by ErdeFB** [comment]
I'm getting this same error when I tried saving to my db that I exported from LastPass in the CVS format. As stated above, when using a newly created vault this error does not occur. It is weird since I can read the vault trough the extension, but not save to it.

**Comment by Doctor-Who** [comment]
Same error too with a local file.
Try with buttercup desktop app open or close
Try with Firefox and Brave (Chromium base
OS : Linux openSUSE

**Comment by perry-mitchell** [comment]
Testing on windows 10, browser ext 2.8.2, desktop 1.17.2 - and I can't reproduce. A new vault file saves fine, and repeated locking/unlocking/saving all works without a hitch.

@Doctor-Who @ErdeFB @eandersons Can you please confirm the location of your vault is **writeable** for Buttercup? I'm saving in my `/Users/xxxx/` directory which is owned by me.

**Comment by eandersons** [comment]
@perry-mitchell As I mentioned in this [comment](#issuecomment-536272053), the error can be observed in specific cases. If I create a new archive, everything works. If I import entries from the archive where this error occurs, then I cannot add new entries in the new archive as well. I guess that there is something with the stored entries/passwords.
I coud try to duplicate the problematic archive and then delete entries from it one by one to see if that changes anything.

**Comment by eandersons** [comment]
Today I did what I said I could try to do in my previous comment, but error persisted also when there was no entries left in the archive. So I embraced the task to manually copy all password entries one by one to a new archive. When I did that, I checked if the error still can be observed, and luckily it did not occur.

So for me the problem is solved, but the question why the aforementioned error did occur still is open. Seems that it could be with the archive content itself, but I have no idea how to debug it.

**Comment by perry-mitchell** [comment]
> If I import entries from the archive where this error occurs, then I cannot add new entries in the new archive as well

If I understand you correctly, you're suggesting that the import procedure corrupts the vault some how? How are you actually importing? It's a bit confusing, sorry.

Would you be able to clarify, both vaults, in terms of:
 * What app were you using (desktop/browser)
 * When reading/writing from the desktop app, if used, was it a local file you were accessing?
 * When using the browser, could you confirm that it was attached to a local file via the desktop app?

One thing to mention here is sync'ing, in case this helps.. Both the extension and the desktop app aren't _always_ showing the live contents of the vault in their interfaces, and only reload from disk/remote every few minutes (if I recall correctly). If you're working on the same vault in more than one place, this can cause some issues with sync'ing in some cases.

**Comment by eandersons** [comment]
No, I did not suggest that the import procedure corrupts the archive as the initial vault seems to be somehow corrupted itself.
I just did a little test, and now I am suggesting that export and/or import somehow corrupts the archive. I exported entries from a healthy vault (quite a lot of documents and multilevel groups) and imported everything into a new archive (all subgroups were added to the root level, see [this issue](https://github.com/buttercup/buttercup-exporter/issues/2)), added it to the browser extension and tried to save a new entry using "Save in Buttercup?" popup. Unsuccessfully - the same error occured.
Yesterday I played a little with import - I manually changed the count of password entries in a .csv file and I found out that if there was no more than about 44 or 45 entries everything was fine, but when I added more then the archive got somehow corrupted and the error was displayed when I tried to add a new entry from a browser.

Answers to your questions:
- Export and import was done using desktop application, and new entries I tried to add using the "Save in Buttercup?" popup in a browser.
- In all cases local archive file was used.
- In both desktop app and browser extension a local file was added.

Yes, I noticed that changes were synced with a delay. It seems that changes that were made in desktop app appears in the browser extension after locking and unlocking archive (usually after one or two tries), and changes that were made in browser extension appeared in the desktop app after I deleted some entries and cleared the trash (I guess that locking and unlocking valut should have the same effect).

**Comment by Doctor-Who** [comment]
> Testing on windows 10, browser ext 2.8.2, desktop 1.17.2 - and I can't reproduce. A new vault file saves fine, and repeated locking/unlocking/saving all works without a hitch.
> @Doctor-Who @ErdeFB @eandersons Can you please confirm the location of your vault is **writeable** for Buttercup? I'm saving in my `/Users/xxxx/` directory which is owned by me.
It's my home directory, I can successfully create an archive and lock/unlock it. From the desktop app, I can edit/add/delete entry but not save from my browser from the extension (Firefox and Brave)

**Comment by eandersons** [comment]
Well, I just started to get this error again. Previously I could add new entries using browser extension, but not anymore. I have no idea what caused this error/behavior.

**Comment by perry-mitchell** [comment]
@eandersons @Doctor-Who By any chance are you using multiple browsers on the computer at the same time? I think the key in the desktop app might change. If so, could you try with just one browser, close down everything, open it all up and try re-connecting and saving an entry?

**Comment by eandersons** [comment]
@perry-mitchell Multiple browsers with Buttercup extension open might be the cause as at some point I was using two browsers at the same time with added local vault in extension. I removed local vault from browser extension, quit all browsers and Buttercup desktop application, reopened Buttercup and one of browsers, added local archive in broser extension, but the error is still there. I could not check this in Vivaldi because of #316 as the latest extension version is not yet available in Chrome Web Store.

**Comment by perry-mitchell** [comment]
@eandersons That almost sounds as though it’s not the cause for you- if you only tried with one browser at a time. Please correct me if I misunderstand.

If we change it so that the code does not remove previous ones, it might actually work. I’ll look into it today.

**Comment by perry-mitchell** [comment]
Just tested this now, 2 browsers and the desktop app - I was not able to reproduce the issue (Mac Catalina, Chrome + FF latest).

It seems that we do not regenerate the code for encryption between browser and desktop - it is generated once and written to config storage. Each time the app restarts, it is re-read. It did not change for me no matter how many times I restarted the extension and desktop app.

@eandersons You could help us test, if you might! I think the config file for Bcup is located here: `%APPDATA%\Buttercup\config.js` (I'm using Mac so I can't confirm this right now). If you open that, there'll be JSON contents like so:

```json
{
	"window": {
		"position": [
			565,
			108
		],
		"size": [
			1134,
			819
		]
	},
	"fileHost": {
		"encryptionKey": "4%yKWm:aWRLq;"
	}
}
```

Notice the `encryptionKey` property. This is what's used to encrypt communications between the browser and the desktop app. Take note of this and then perform the same actions you did to reproduce the failure. Check the file again and see if the key matches - Letting us know this would help a lot!

**Comment by eandersons** [comment]
@perry-mitchell Well, that is the problem that I have no idea how to reproduce this error. All I know is that everything was working, and after a while (it could be days, so I do not know the exact point or action that caused the error) I could not save new entries.
Just a reminder - everything is working in Buttercup desktop application and if the same vault is added to the browser extension using DAV (I am using Nextcloud).

Additionally I checked if this error can be observed on macOS as well, and it does occur on Mac too and on other Windows machines as well.

I also did this - I removed vault from the browser extension, closed Buttercup desktop application, deleted `config.json`, reopened Buttercup (`config.json` was regenerated with a new encryption key), in the browser extension added previously removed local archive, and the error is still there.

**Comment by Doctor-Who** [comment]
> @eandersons @Doctor-Who By any chance are you using multiple browsers on the computer at the same time? I think the key in the desktop app might change. If so, could you try with just one browser, close down everything, open it all up and try re-connecting and saving an entry?

Tested with only firefox on Linux openSUSE without Brave same thing unable to save any password into buttercup

**Comment by eandersons** [comment]
@perry-mitchell I copied the problematic vault, renamed it, removed all the entries except one sample entry for testing. [Here is the test archive](https://nextcloud.gaitenis.id.lv/s/Hsr7CWFgm7HD4cR) (this link may not be available during nights in EET). Password is `testpassword`. I hope this will help to debug on your side.

**Comment by xunxky** [comment]
having a similar (probably the same) problem here ubuntu 18, chrome 83 with the local file. locking and unlocking works. after having a quick glance into the background process and the associated code i utterly cringed. the response is  "Payload Too Large", because it seems the whole archive is resubmitted. this is a bad behaviour, as only the new entry should be sent having the bc-server doing the heavy lifting of incorporating the entry into the archive.

**Comment by koenr** [comment]
I have the same problem saving passwords using the browser plugin (ubuntu 20.04) Only saving is a problem. The size might be the problem indeed. I have 782 passwords in the vault in one folder. My .bcup file is 1.7 MB

**Comment by perry-mitchell** [comment]
> only the new entry should be sent having the bc-server doing the heavy lifting of incorporating the entry into the archive

You assume this without understanding how Buttercup works, and how it keeps your vault contents secure. Updating items individually would require a whole different vault structure and would result in terrible performance on many environments.

**Comment by perry-mitchell** [comment]
@koenr Have you checked to see if this is still the case with the latest browser extension version? We fixed a huge issue with vault sizes. Please upgrade and save your vault at least once - the size should be reduced on the new versions.

**Comment by perry-mitchell** [comment]
Since there are now several issues referencing this problem, or other issues with the file host, I'm making a consolidated issue thread: #282 - Let's move the conversation there. Please do not restate existing issues, I'll do my best to link to the relevant portions. If you can help debug this further by running up desktop and browser development environments it'd be greatly appreciated.

**Comment by Claywd** [comment]
So I had this exact problem today with the browser extension in chrome. Tried to save something my logins directory and it worked the first time but errors everytime afterwards

**Comment by xunxky** [comment]
> > only the new entry should be sent having the bc-server doing the heavy lifting of incorporating the entry into the archive
> 
> You assume this without understanding how Buttercup works, and how it keeps your vault contents secure. Updating items individually would require a whole different vault structure and would result in terrible performance on many environments.

Sorry for getting back this late 
I actually have explained how it currently works is not what I would like and yes I am aware that it would require a completely different setup. which is why BC is not an option for me

**Comment by Cydroz** [comment]
> No, I did not suggest that the import procedure corrupts the archive as the initial vault seems to be somehow corrupted itself. I just did a little test, and now I am suggesting that export and/or import somehow corrupts the archive. I exported entries from a healthy vault (quite a lot of documents and multilevel groups) and imported everything into a new archive (all subgroups were added to the root level, see [this issue](https://github.com/buttercup/buttercup-exporter/issues/2)), added it to the browser extension and tried to save a new entry using "Save in Buttercup?" popup. Unsuccessfully - the same error occured. Yesterday I played a little with import - I manually changed the count of password entries in a .csv file and I found out that if there was no more than about 44 or 45 entries everything was fine, but when I added more then the archive got somehow corrupted and the error was displayed when I tried to add a new entry from a browser.
> 
> Answers to your questions:
> 
> * Export and import was done using desktop application, and new entries I tried to add using the "Save in Buttercup?" popup in a browser.
> * In all cases local archive file was used.
> * In both desktop app and browser extension a local file was added.
> 
> Yes, I noticed that changes were synced with a delay. It seems that changes that were made in desktop app appears in the browser extension after locking and unlocking archive (usually after one or two tries), and changes that were made in browser extension appeared in the desktop app after I deleted some entries and cleared the trash (I guess that locking and unlocking valut should have the same effect).

I'm experiencing similar behaviour to this. I'll also add:

* With a smaller import file of about that size (~40 records), if I imported it twice, I can still save via browser extension
* After importing the same file a few more times (i.e. duplicating passwords/folders more than once/twice), I encounter the error when saving via browser.

As for syncing changes, I've found that it's best to create an entry on the desktop app and save it to force a refresh.

It seems like if the archive file has too many passwords then the error occurs.
