### ISSUE TITLE
Disappearing Buttercup form buttons when logging in to Dropbox

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-browser-extension#285]
Helllooo,

Hope you're well

Thanks for software

As title

# Steps to reproduce issue

See screen cast

# Unexpected behaviour

Visit http://dropbox.com/login and Buttercup (BC) form buttons disappear

# Expected behaviour

Visit http://dropbox.com/login and BC form buttons stay accessible/visible

Screen shot/cast: https://www.dropbox.com/sh/mzegb4oum11a0fd/AAATJyiiHW-zeU7yspBRO5f_a

Is it possible XHR CSS/JS from dropboxstatic.com are overriding BC functionality?

NB reproduced in latest Firefox

If you're reading and:

* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

Welcome feedback/input

If you have any issues (e.g. questions/queries) then happy to help

Hope to hear back

Keep up great work!

Yours faithfully

software - operating system: Apple, macOS, 10.14.6 (18G95)
software - application: Vivaldi, 2.8.1664.43 (Stable channel) (64-bit)

**Comment by perry-mitchell** [comment]
Really interesting! Seems that they’re maybe pulling the inputs forward or possibly destroying the inputs and recreating them. This would be quite strange though as it’d most likely break user text input - so perhaps it’s the first option? Or the second providing they keep the input and reset focus.

Either way it’s a pain, means we’ll need to add detection for disappearing forms and elements. Maybe MutationObserver would help here. With regards to the buttons I’ve always thought that it’s tricky and would maybe be better to use another approach.. it’s difficult to conceive of a generic approach that’d work on all websites.

**Comment by perry-mitchell** [comment]
I’m not at a machine so I’ll try to do some testing soon.

**Comment by perry-mitchell** [comment]
Confirmed here as well - Seems they're deleting them somehow. I'll look into it soon if no one else beats me.

**Comment by ldexterldesign** [comment]
So much stupid complexity for a simple login

https://alternativeto.net/software/dropbox/ - recommendations if you please folks, I'll be attending to this after I've de-Googled

Yours hopefully
