### ISSUE TITLE
Unlock-vaults page won't open from dialog button

### ISSUE THREAD

**Issue by bigalgeorge** [buttercup/buttercup-browser-extension#286]
Firefox 69.0.2/Ubuntu [Unlock Vault] button inoperative (prior click padlock button when padlocks shown next to fields).
Expected behaviour instantiate browser login.
![Selection_388](https://user-images.githubusercontent.com/6935387/66719971-2ca1ac80-ee53-11e9-893f-253d3735c696.jpg)

**Comment by perry-mitchell** [comment]
Does it work after you refresh the page? Wondering if it's an extension-disconnect error that occurs after an update..

**Comment by flohw** [comment]
Hi,

Is there any update? I have the same issue with Firefox 72.0.2 (and probably previous version) on archlinux.

Thank you

**Comment by perry-mitchell** [comment]
Released in 2.14.0

**Comment by flohw** [comment]
Thank you @perry-mitchell !
