### ISSUE TITLE
Suggest optional 'Save New Credentials' dialogue

### ISSUE THREAD

**Issue by bigalgeorge** [buttercup/buttercup-browser-extension#287]
When there is already a (single) vault open, the selection of vault is superfluous IMHO.
I'm not sure if you even allow opening more than one vault at same time?
Also to help automate entry there could be additional flags settings as radiobuttons:
[o] New Entry/NO Dialog
[ ] New Entry/Dialog
Where 'General' is default Group, and if New Entry/NO checked items are stored without dialog, otherwise dialog shows with fields preset in current vault and General.

BTW Perry, if you have the time I should PM you? otherwise thanks for support regardless.

**Comment by perry-mitchell** [comment]
Hi @bigalgeorge - You can indeed have multiple vaults open at the same time.

This whole section (saving credentials after a new login) needs a revamp. We need basically the following things:

 - Better detection of whether or not to show the save dialog
 - Option to never show it on a site - #272
 - Option to save credentials **if** the dialog never appeared (memory)
 - Automatic addition without the need for content entry
 - Updating existing credentials with the new data (good for password resets)

But this is an enormous amount of work of course 😅.

I might be misunderstanding what you're suggesting here - but you're just suggesting a setting in the extension menu to allow for enabling/disabling the dialog entirely, right?

> if you have the time I should PM you

I can certainly make time if you want to chat more. [Keybase](https://keybase.io/perrymitchell) is best, but if you don't have an account there [twitter](https://twitter.com/perry_mitchell) also works fine (DM). I'm also present on [reddit](https://www.reddit.com/user/perry_mitchell). Do any of those work?

**Comment by bigalgeorge** [comment]
Hi Ill look at twitter next week; think I have an old account. 
//you're just suggesting a setting in the extension menu to allow for enabling/disabling the dialog entirely, right?
Correct.

**Comment by bigalgeorge** [comment]
//I can certainly make time if you want to chat more. Keybase is best, but if you don't have an account there twitter also works fine (DM).
Perry I dont use Twitter usually, but have left a message for you some time back. Cheers, Al.

**Comment by perry-mitchell** [comment]
I've updated my previous comment with more issue numbers, as this post was discussing quite a number of features. Please follow those IDs for more info/progress :)
