### ISSUE TITLE
Feature Request: Password save queue

### ISSUE THREAD

**Issue by Kyu** [buttercup/buttercup-browser-extension#291]
Please tell me if this is a bad idea for security, but I hate the "enter your master password" prompt every time I restart my browser session. 

Personally, I use this program to save passwords more than I do recalling them.

This feature I'm proposing would allow you to disable that prompt, but also adds this:
If after "disabling" the prompt, you start your browser session and later happen to need to create a password, the extension prompts you saying "save password to queue?"

If you select No, nothing happens.
If you select Yes, it saves the username, password, website name to a queue linked to the open browser session.

You can then later choose to unlock your archive(s) and select which passwords you want to add to which archives in bulk.

I've never done much with browser extension dev before, but I wouldn't mind trying my hand at this.

**Comment by perry-mitchell** [comment]
Hi! Very interesting proposition. This is going to cause a bit of conjecture I'm sure, but let's go over this situation you're experiencing as a whole.

Right away your comment regarding disliking the login prompt raises a bit of a red flag - Logging in is a basic security requirement to ensure your vault contents are protected. There's no way to ever get rid of that requirement - but perhaps there are ways to reduce its frequency. #292

Regardless of our feelings towards logging in - your point on saving items in a queue is interesting. I might understand your use case, but eventually you'll have to log in, right? Are you really saving any time by just delaying the log in?

Needless to say storing website credentials in local storage is definite a security issue, and unfortunately for this idea one that we won't be considering I'm afraid. It's simply not good practise.

**Comment by Kyu** [comment]
I don't dislike entering my password, that's obviously a critical requirement. I just don't like being prompted to enter it every time I open my browser because I don't use buttercup all the time(I'm usually already logged in to the services I use). 

For that issue, I'd just like a way to disable the prompt, until I click the buttercup extension button and open an Archive myself. By prompt I mean the "select an archive" page that shows up every time you open the browser.

As for the local storage security issue, I didn't think of that, but it would indeed be bad.


Thank you for your response, and I hope you consider maybe a "disable login page" setting.

It wouldn't remove logging in, but instead, wait until the user asks for buttercup to open an Archive, in which case they enter their master password and continue using buttercup as usual.

**Comment by bigalgeorge** [comment]
Perry is absolutely right. Negating need for password when you are going to use the extension would open a Pandoras Box. But what Im reading is your system is asking for your password each time a new browser session is started? This should only happen when you click on the extension icon, as an option. Unless you are talking about instantiating the Buttercup application which of course will prompt for a password.

**Comment by julianpoemp** [comment]
@Kyu Do you use the buttercup client application? If so, you could open your vault there and let the client application open. Just add an entry with the vault's password. When you want to unlock the vault in the browser extension all you need to do is to copy & paste the password from the client to the browser extension. If you use a long password this would speed up the unlock.

I think the most user-friendly workflow would be a client that is in synchronization with the browser extension. So we would only need to unlock one time (in the client app) and the vaults in the browser extension are unlocked automatically. I already made a feature request some time ago, but because of security considerations that idea was postponed. See #215

**Comment by perry-mitchell** [comment]
> For that issue, I'd just like a way to disable the prompt, until I click the buttercup extension button and open an Archive myself. By prompt I mean the "select an archive" page that shows up every time you open the browser.

Ah, the auto unlock feature? If you mean that, it can be disabled via settings:

![image](https://user-images.githubusercontent.com/3869469/68322701-8866fa80-00cc-11ea-9425-a4742be45407.png)

**Comment by Kyu** [comment]
@perry-mitchell thanks for that, I should've done more digging first.

**Comment by perry-mitchell** [comment]
@Kyu No worries! :)
