### ISSUE TITLE
Graceful reload / update (no lock on update)

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-browser-extension#292]
There are methods to use when the extension updates to ensure state continuity. Perhaps we can prevent vaults being locked when this occurs.

https://developer.chrome.com/extensions/runtime#event-onSuspend
https://developer.chrome.com/apps/app_lifecycle

**Comment by perry-mitchell** [comment]
Might be an idea to look into ways of storing the user's password or key in a secure manner during the update process..

**Comment by arnnis** [comment]
I'm not sure if this is same scenario, Bitwarden allows storing key unsecure on storage with a warning to user.
![image](https://user-images.githubusercontent.com/61647712/218383129-3e3ee135-b63b-48c6-af05-ca1a92578494.png)

**Comment by perry-mitchell** [comment]
No longer needed in V3. State is persistent due to desktop app reliance.
