### ISSUE TITLE
A way to donate to make you feel needed?

### ISSUE THREAD

**Issue by ondrej-karlik** [buttercup/buttercup-browser-extension#301]
Hi  Perry & Sallar, how can I fully appreciate your work?
I'd like to say "here you have some €'s to buy some coffee".  I'm a daily user of the extension, can make some Opera bug reports.. thanks!

**Comment by perry-mitchell** [comment]
Hi @ondrej-karlik - That's incredibly kind of you! While we have an [open collective](https://opencollective.com/buttercup) account for donations, we'd really be happy if you just shared the word and told someone about Buttercup! Just being here and having a chat is pretty awesome for the community. Thanks for that!

**Comment by ondrej-karlik** [comment]
Thanks for your reply. I hope this issue will raise awareness of the way to donate. I will do my best, keep up the good work.
