### ISSUE TITLE
Focus on search field

### ISSUE THREAD

**Issue by eandersons** [buttercup/buttercup-browser-extension#302]
I would like to request a little but handy feature - focus on search field in Buttercup dialog when a Buttercup button in an input field is pressed as not allways the relevant entry is displayed. Well, the search field can be focused by pressing `Tab` key, but those are four strokes.
For instance, the search field has focus when the Buttercup extension icon is clicked in browser toolbar.

**Comment by perry-mitchell** [comment]
Hi @eandersons - apologies for not seeing this earlier.

![image](https://user-images.githubusercontent.com/3869469/71991044-2dbd5c80-323d-11ea-90d5-cec61536cfb8.png)

It focuses for me just fine in Chrome. Still having this issue?

**Comment by eandersons** [comment]
Sorry, I forgot to mention that I am using Firefox Developer Edition.
I just checked Buttercup extension in Vivaldi browser, and focus in search field is working indeed. So it seems that this is Firefox specific issue.

**Comment by eandersons** [comment]
Sorry, focus on search field is working in Firefox Developer Edition as well.
