### ISSUE TITLE
First attempt not correct credentials

### ISSUE THREAD

**Issue by christianschneider89** [buttercup/buttercup-browser-extension#305]
For me it is often the case that the wrong login data appears on the first time.
On the second time the correct suggestion appears.

First attempt with wrong suggestion:
![image](https://user-images.githubusercontent.com/15085873/69721203-a1375e80-1114-11ea-83f6-cec9eb7c32aa.png)

Second attempt with correct suggestion:
![image](https://user-images.githubusercontent.com/15085873/69721254-bd3b0000-1114-11ea-9eb8-445f7e8d138d.png)

Best regards
Chris

**Comment by perry-mitchell** [comment]
This is a dupe of #283 - closing in favour
