### ISSUE TITLE
buttercup-browser-extension - unable to unlock the vault - NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by Krikegard** [buttercup/buttercup-browser-extension#306]
Hi, I am unable to unlock the vault (localfile) under firefox with the following messages:

Failed unlocking archive
Unable to unlock archive (53234a78-9bff-4779-b4a1-08cac21751f0): Unlocking archive source (53234a78-9bff-4779-b4a1-08cac21751f0) failed: Failed unlocking source: 53234a78-9bff-4779-b4a1-08cac21751f0: Failed mapping credentials to a source: NetworkError when attempting to fetch resource.

My vault is saved on hardrive (localfile)
Firefox version: Firefox Quantum - ESR - 68.2.0esr (64-bit)
OS: Microsoft Windows 10 Enterprise - Version 10.0.17134

I have tried some stuffs:
I have the same error with and without the option Vaults Auto Unlock
Firefox console gives same messages that reported above
Restarting Firefox does not fix the issue
Setting Vaults Auto Lock to off does not fix neither

Any idea?
Thanks in advance (quite a "blocking" issue!)

**Comment by Krikegard** [comment]
ok, my mistake - buttercup desktop was not running...
I close the issue, they are maybe few but some other peoples like me, without a functional brain by morning...

**Comment by perry-mitchell** [comment]
We definitely need to improve this, perhaps by adding a **ping** function - notifying the user early on that a connection is not possible and that the desktop app may not be running would probably be helpful here. Good you got it sorted :)
