### ISSUE TITLE
No login box available Firefox 71.0 and Buttercup 2.10.0 

### ISSUE THREAD

**Issue by Peppeo** [buttercup/buttercup-browser-extension#312]
I don't know if this is the same as #286 but for some days now in Firefox I don't get the 'open vault' dialog anymore ? I just replayed it here on my Macbook; at home the same issue on Manjaro and Firefox. It happens with 2.10.0; extension on Chrome (v2.9.0 ) is working okay.
<img width="977" alt="Screen Shot 2019-12-26 at 08 44 44" src="https://user-images.githubusercontent.com/53419266/71453320-42b9da80-27bd-11ea-912b-dbb189057cc1.png">

**Comment by houdini69** [comment]
Same behaviour in my case with the 2.10.0 update. I think the "What's New" window hides the "open vault" dialog.

**Comment by perry-mitchell** [comment]
Ok, thanks for posting - I'll try to get a fix right away!

**Comment by perry-mitchell** [comment]
Released in 2.10.1. Very sorry for the inconvenience.. Happy holidays!

**Comment by Peppeo** [comment]
Thanks for the updated version; I can confirm it's working in Firefox again. Thanks for the quick response and have happy holidays!

**Comment by houdini69** [comment]
Yes, it's working for me too in Firefox. Happy holidays!

**Comment by Peppeo** [comment]
@perry-mitchell : That was too quick or Google is late with updating the extensions ;-)
![Screen Shot 2019-12-27 at 08 35 04](https://user-images.githubusercontent.com/53419266/71496303-2e411500-2885-11ea-94a4-e93ea554c137.png)
![Screen Shot 2019-12-27 at 08 36 43](https://user-images.githubusercontent.com/53419266/71496304-2e411500-2885-11ea-9e49-c08e673295cd.png)
Firefox Ok, now also the error on Chrome/MacOS.

**Comment by tourtools** [comment]
Chrome hasn't yet update the version, it's still the 2.10.0
Chrome version 79.0.3945.88 for MacOS

**Comment by perry-mitchell** [comment]
Our apologies, this has now been patched in Chrome too, pending their review.

**Comment by Peppeo** [comment]
Can confirm it showed up correctly this morning in Chrome 78.0.3904.108 and is working . @perry-mitchell : thanks for fixing this!
