### ISSUE TITLE
Cannot add local vault to Firefox: createSession is not defined

### ISSUE THREAD

**Issue by disjunction** [buttercup/buttercup-browser-extension#316]
When adding a local vault after successfully connecting to desktop app I get the following error:
`Failed fetching the remote contents of '/': createSession is not defined`
 (see screenshot)

I see the error in JS console of the browser and in the UI itself. There is no error in the desktop app console output

The same workflow works fine in Chrome, so it looks like a Firefox specific issue.

<img width="720" alt="Screenshot 2020-01-06 at 15 15 26" src="https://user-images.githubusercontent.com/679693/71824798-a89a4200-309a-11ea-89a8-87c4003e72ed.png">

OS: macOS Mojave 10.14.6
Firefox: 71.0
Desktop Buttercup: 1.18.2
Buttercup Browser Extension: v2.11.0

**Comment by Choco02** [comment]
Same error on Windows 7 x64
Firefox 71.0 (64 bits)
Desktop Buttercup 1.18.2
Firefox extension v2.11.0

![image](https://user-images.githubusercontent.com/41271075/71826039-d8861d00-307b-11ea-9ed8-d4c5f51194b1.png)

**Comment by eandersons** [comment]
`createSession` error also occurs when trying to unlock already added local vault in Firefox Developer Edition.
Full error message:
>    Failed unlocking archive
Unable to unlock archive (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx): Unlocking archive source (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) failed: Failed unlocking source: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx: Failed mapping credentials to a source: createSession is not defined

The same vault added using DAV is working fine.

**Comment by Krikegard** [comment]
Similar error than reported just above: (trying to unlock already added local vault in Firefox)
Failed unlocking archive
Unable to unlock archive: Unlocking archive source (53234a78-9bff-4779-b4a1-08cac21751f0) failed: 
Failed unlocking source: 53234a78-9bff-4779-b4a1-08cac21751f0: 
Failed mapping credentials to a source: createSession is not defined

OS: Windows 10 Enterprise
Buttercup browser extension: Version     2.11.0
Browser name: Firefox  version: 68 fullVersion: 68.0
 
Error took place a couple of days ago
Updated Buttercup desktop to v1.18.2 -> same error
Updated Buttercup Firefox extension to the last one (just did it) -> same error

**Comment by igorvolnyi** [comment]
Confirm. Buttercup 2.11.0 fails to unlock local vault.

![Buttercup 2 11 0 bug 2020-01-08_19-16](https://user-images.githubusercontent.com/11294353/71984860-80057a00-324b-11ea-8b34-05349a40101c.png)

**Comment by llcoolju** [comment]
Exact same error here, but on Chromium browser.

OS : Mac OS High Sierra 10.13.6
Buttercup browser extension: Version 2.11.0
Buttercup desktop app : version 1.18.1
Browser name: Chromium Version 75.0.3738.0

**Comment by perry-mitchell** [comment]
We missed this - we'll have a patch out for this today! Sorry everyone.

**Comment by perry-mitchell** [comment]
Released in 2.11.1

**Comment by andgar2010** [comment]
Hello
I can't find the latest version of chrome extensions. Because similar error version v2.11.0

Exact same error here, but on Chromium browser.

OS : Windows 10 Home x64
Buttercup browser extension: Version 2.11.0
Buttercup desktop app : version 1.18.1
Browser name: Edge Chromium Version 79.0.309.58

![image](https://user-images.githubusercontent.com/19521054/72003424-56326000-3217-11ea-93a0-108d958703e5.png)

**Comment by smxsm** [comment]
Same here, Chrome Plugin is broken for local archives with 2.11.0, but no 2.11.1 version available yet in the Chrome Store ...
