### ISSUE TITLE
Failed fetching directory contents 

### ISSUE THREAD

**Issue by Huxell** [buttercup/buttercup-browser-extension#318]
I am trying to connect the browser extension to the desktop App but it always gives me the following  error message:

Failed fetching directory contents
Failed fetching the remote contents of '/': createSession is not defined

i tried on my mac and my linux machine. 

I am using brave browser with chrome extension.

**Comment by perry-mitchell** [comment]
This is related to #316, which was fixed in 2.11.1. Can you confirm which version you're using?

I'll close this for now as it should be resolved. We can reopen if we find that there's another bug.
