### ISSUE TITLE
[MS Edge] Auth information not updated - Google Drive not working correctly 

### ISSUE THREAD

**Issue by Peppeo** [buttercup/buttercup-browser-extension#319]
Also related to issue #317. Testdriving the new Edge browser on Mac. Installed Buttercup extension from the Chrome store. Adding my vault:
1.Choose Google Drive:
![Screen Shot 2020-01-17 at 08 56 36](https://user-images.githubusercontent.com/53419266/72578664-4c8cb480-3909-11ea-94f9-1fec0b1a839b.png)
2.Connect Google account:
![Screen Shot 2020-01-17 at 08 56 46](https://user-images.githubusercontent.com/53419266/72578762-983f5e00-3909-11ea-96e8-b72e21268152.png)
3. Grant access to Buttercup:
![Screen Shot 2020-01-17 at 08 57 01](https://user-images.githubusercontent.com/53419266/72578803-c45adf00-3909-11ea-9149-f2dc58eff0d5.png)
4. Get thrown back to the selection screen:
![Screen Shot 2020-01-17 at 08 57 12](https://user-images.githubusercontent.com/53419266/72578833-dd639000-3909-11ea-8e02-9a51f480a7ef.png)
**N.B.** This did **not** happen to me when using Chrome or Firefox but there I could not browse the Drive itself.
5. Follow exactly the same procedure on Dropbox and can a. browse the contents of the drive and b. add the vault to Buttercup.
![Screen Shot 2020-01-17 at 09 02 10](https://user-images.githubusercontent.com/53419266/72579165-d7ba7a00-390a-11ea-9dff-3a59f696f9ea.png)

**Comment by perry-mitchell** [comment]
We don't test regularly on Edge, so this is probably something to do with how Edge manages browser events. It _may_ require changes to our build system, which I'd prefer to delay as long as possible. But would be happy to see a PR or some discussion surrounding this.

We definitely DO want to support the new Edge as a first-party browser.

**Comment by perry-mitchell** [comment]
Confirmed, there seems to be some issue in Edge:

![image](https://user-images.githubusercontent.com/3869469/72668397-ea2dd400-3a2e-11ea-9190-8bc8f9095be3.png)

**Comment by perry-mitchell** [comment]
Found the issue! It was a decoding error which somehow only appeared in Edge. I've fixed it:

![image](https://user-images.githubusercontent.com/3869469/72668443-9d96c880-3a2f-11ea-89ca-244490e961e1.png)

Expect it in 2.12.0.

**Comment by Peppeo** [comment]
Ok @perry-mitchell thanks for the heads-up and the time (as ever)
