### ISSUE TITLE
Google Drive - option for open permissions whilst adding

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-browser-extension#320]
Add an option to allow using the original, more open permissions whilst adding a google drive vault.

**Comment by perry-mitchell** [comment]
It'll look something like this:

![image](https://user-images.githubusercontent.com/3869469/72666832-7f749c80-3a1e-11ea-9826-30b8a616adfd.png)

**Comment by Peppeo** [comment]
@perry-mitchell : i understand the reasoning behind it now, but i am also happy to confirm it is working within Chrome and with version number 2.12.
