### ISSUE TITLE
cannot add vault in browser (drive and dropbox)

### ISSUE THREAD

**Issue by purplesrl** [buttercup/buttercup-browser-extension#325]
Version: v2.13.0

I have authorized both drive and dropbox but I am getting the following errors when I am trying to add a vault:

Failed selecting Dropbox vault
An error occurred when adding the vault: Adding archive failed: Failed unlocking source: 48bbf479-bfce-403f-932c-d2f0c6xxxxx: Failed mapping credentials to a source: Request failed: 409 path/not_found/

Google Drive:

Failed selecting Google Drive vault
An error occurred when adding the vault: Adding archive failed: Failed unlocking source: c5eb908d-dd1e-43ea-8b4b-xxxxxxxxx: Failed mapping credentials to a source: Failed fetching Google Drive vault: No valid signature in archive

.bcup files are created, applications are authorized

Chromium Browser

Firefox Browser

**Comment by perry-mitchell** [comment]
Hello! Sorry to hear you're having troubles.

I'm using Chrome and the vaults add just fine there, for Dropbox and Google Drive:

![image](https://user-images.githubusercontent.com/3869469/73095327-ff9d7500-3eea-11ea-8983-4982eb7633d4.png)

What version of Firefox are you using? And can you try on Chrome?

**Comment by purplesrl** [comment]
Hello,

I use Chromium on Ubuntu 18.04 -> 

Version 79.0.3945.79 (Official Build) Built on Ubuntu , running on LinuxMint 19.3 (64-bit)

And Firefox 73.0b9 (64-bit)

The same errors are experienced on both browsers so I have no idea what could be wrong, I did authorized both apps (Dropbox and Drive), the only other plugin I have installed is Ghostery and I paused it

**Comment by purplesrl** [comment]
@perry-mitchell maybe there is some link with the steps I need to take to add a vault, but they seem pretty basic, I just installed the extension, then clicked on that + to add a new Vault, the filename is created on Google Drive (.bcup extension) but after I hit save I get that error

Note that I do not have the Desktop app installed

**Comment by Dark-Vex** [comment]
I have exactly the same problem with Chrome Version 79.0.3945.130 on macOS Catalina

**Comment by perry-mitchell** [comment]
@purplesrl @Dark-Vex Any special characters in your file paths?

**Comment by Dark-Vex** [comment]
@perry-mitchell no special characters in my case, I've made a video of the issue if it can help  https://youtu.be/sfbTLR3pwWQ

**Comment by purplesrl** [comment]
@perry-mitchell no, also I would like to mention that the file created in google drive is empty, i checked in Apps with access to your account and Buttercup is listed

I attached more information with the errors I get, I think the one on the first line could be why the process is not correct

![buttercup_details](https://user-images.githubusercontent.com/19906540/73117887-0d87e000-3f55-11ea-898e-da0042be0094.png)

**Comment by perry-mitchell** [comment]
I'm sorry for the delay. I was able to reproduce - in process of fixing it now.

**Comment by perry-mitchell** [comment]
The issue was due to regression from the core - I was able to create new dropbox and google drive vaults after I fixed the problem. Releasing shortly.

**Comment by perry-mitchell** [comment]
Released in 2.14.0
