### ISSUE TITLE
Offline unlock support

### ISSUE THREAD

**Issue by ocomsoft** [buttercup/buttercup-browser-extension#327]
Using Chrome extension.

Nearly every morning when I come in the office Network has no internet connection. When I put my password in to unlock buttercup it fails. When I wait for the internet access to be online and use the same password (ie don't change the password input - just press the button) it works. 

Is there some way of detecting if the browser is "offline" and not authenticate if that is the case? 

Thanks for a great project by the way.

**Comment by perry-mitchell** [comment]
@ocomsoft The mobile app supports offline access, and this is something we might consider for the browser extension. The vault is opened in ready-only mode in this scenario.

We could potentially detect internet connectivity and re-enable write mode. This might be a larger task, however.

**Comment by perry-mitchell** [comment]
Not appropriate post V3 release. Offline mode isn't possible in the extension anymore. It _may_ be via the Desktop application however.
