### ISSUE TITLE
Listing for Microsoft Edge (chromium version)?

### ISSUE THREAD

**Issue by superusercode** [buttercup/buttercup-browser-extension#329]
There is no work to port the extensions since the new edge is based on chrome. All users on Windows/macOS (and Linux in the near future) are already able to install it from the chrome web store when prompted to enable downloads from the CWS. The extension submission process is detailed at https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension

**Comment by perry-mitchell** [comment]
We've been trying to get the listing working for some time, but Microsoft simply doesn't want to help us there:

![image](https://user-images.githubusercontent.com/3869469/75789589-98d56c00-5d72-11ea-91d3-26397563468e.png)

It's been like this for days.

**Comment by perry-mitchell** [comment]
Closing as Microsoft doesn't seem to give a crap that we're stuck with this. Edge is off the books until something changes there.
