### ISSUE TITLE
Input icon/button: Minimal / Hidden modes

### ISSUE THREAD

**Issue by divyanshu013** [buttercup/buttercup-browser-extension#334]
Hi, sometimes the buttercup icon doesn't match well with the styles of a site or breaks the styling of input fields. Would it be possible to have an alternate minimal icon that shows up in the input field?

For reference on github login:

1. last pass

<img width="307" alt="image" src="https://user-images.githubusercontent.com/6682655/76819563-8eb17400-682e-11ea-9620-bbac5d5b6e64.png">

2. buttercup

<img width="291" alt="image" src="https://user-images.githubusercontent.com/6682655/76819627-baccf500-682e-11ea-86e8-73e868f7d302.png">

Happy to send a PR if you also feel the same.

**Comment by perry-mitchell** [comment]
This is a good point, but I personally like the buttercup icon being outside the input. Placing a button _inside_ the input isn't safe, for clicks etc. - it's also not how inputs were designed to be used.

That being said, yes, the buttercup button does break some forms. We've been considering our options here for some time, and would love more opinions on the matter. Any and all suggestions here will be considered.

I'd place the following restrictions on an update here:
 1. Only one button style (we don't want a setting for multiple, or different buttons per site)
 2. Ideally not a button inside the input
 3. Ideally doesn't conflict with other password managers (like lastpass)

I've seen several people using multiple PW managers, like lastpass and buttercup, for instance, and this makes it difficult as I'd like to avoid button conflicts with them. Placement inside but on the left side of the input is also tricky as lots of inputs have icons in them these days..

**Comment by nerdCopter** [comment]
The extension really needs an option to disable the in-field icons altogether.
Agree with @kimus ' idea of contect menu as well.

**Comment by perry-mitchell** [comment]
Continued in #464
