### ISSUE TITLE
Enhance save login details detection #Enhancement

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-browser-extension#337]
Hi!

Hope you're well

Thanks for amazingly useful software

Leading on from #287 (the only list item without it's own issue 😏):

> Better detection of whether or not to show the save dialog 

... I, too, think the save login details prompt should be more intelligent (i.e. if a vault entry/login match already exists then don't prompt me to re-save it)

The prompt is pretty annoying to the point where I've considered manually disabling it for every entry/login in my vault(s) but really this should be automated with some intelligence

Screen shot/cast:

<img width="385" alt="Screenshot 2020-05-02 at 06 08 25" src="https://user-images.githubusercontent.com/1715809/80854949-a1480700-8c3c-11ea-980f-3d9250baa58b.png">

<img width="401" alt="Screenshot 2020-05-02 at 06 09 13" src="https://user-images.githubusercontent.com/1715809/80854950-a311ca80-8c3c-11ea-9361-886f6f6e7b38.png">

<img width="1792" alt="Screenshot 2020-05-02 at 06 09 38" src="https://user-images.githubusercontent.com/1715809/80854955-a60cbb00-8c3c-11ea-8f4f-fe2e7dbfe566.png">

This begs the question of intelligence...

I imagine the logic for this has already been solved elsewhere in the codebase, and I'm massively trivialising it here, but some match on a hostname (i.e. `(local.)domain.com`) will NOT trigger a prompt

If you're reading and:

* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

Welcome feedback/input

If you have any issues (e.g. questions/queries) then happy to help

Keep up sterling work!

Hope this helps & to hear back

Sincerely

PS [Related] but distinct enough to warrant it's own issue here

[related]: https://github.com/buttercup/buttercup-browser-extension/issues/272

**Comment by swanknight** [comment]
I agree. I thought it was a bug, why is it asking me to ask me to save a password it just entered? It should only prompt if the credentials are NOT saved already. 
It's a shame, but I'll remove it until this issue fixed.

**Comment by perry-mitchell** [comment]
Sorry for the long delay on this one - I completely agree with the reasoning here. It is annoying.

I've made an update so that if you log in using an existing entry, the prompt will not show. It will only show for manual input. It's set using a simple flag, to identify if it was from an entry or manual. There are 3 ways this flag can be set:
 * When clicking the entry in the search results dialog
 * When clicking the auto-login button in the search results dialog **on-page**
 * When clicking the auto-login button in the extension menu search results

Once the flag is set, it cannot be unset without refreshing or changing pages. This is purely to reduce development effort and potential bugs.

Please expect this in the 2.18.0 release.

**Comment by nerdCopter** [comment]
new user of BC Sept 2022 ... i thought the behavior i'm experiencing was was a bug and intended to submit issue, but it seems already addressed (in 2.18 as commented above); however, it's not working as intended for me.
I've imported my lastpass data to migrate to BC.  I can use the BC Firefox Extension to login to almost all my usual logins; However, it also asks to save new entry each and every time.  i don't necessarily want to disable for domains, but rather it not ask for existing saved entries.

BC FF extension version 2.25.2
Linux Firefox ESR version 91.13.0esr

**Comment by ldexterldesign** [comment]
> Recommend maybe enabling Github Discussions or Discord server for "support"

FYI There's a GitHub discussions feature (e.g. [foo]), which could be used for support

Hope this is useful

Regards

[foo]: https://github.com/dgtlmoon/changedetection.io/discussions
