### ISSUE TITLE
Fix form popup copy button #Bug

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-browser-extension#338]
Hi!

Hope you're well

Thanks for wonderful software

As title

Experiencing this in latest vivaldi and brave but not in firefox which makes me think perhaps it's a chromium issue?

# Unexpected behaviour

Unable to copy username/password

# Expected behaviour

Able to copy username/password

Screen shot:

<img width="647" alt="Screenshot 2020-05-06 at 12 21 19" src="https://user-images.githubusercontent.com/1715809/81166980-bacab500-8f94-11ea-83d1-caacaa996c84.png">

FYI highlighting/selecting the field value manually and copying functions OK so it's something to do with the button click event I imagine

If you're reading and:

* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

If you have any issues (e.g. questions/queries) then happy to help

Keep up great work!

Hope this helps & to hear back

Sincerely

hardware: Apple, MacBook Pro (16-inch, 2019)
software - operating system: Apple, macOS, 10.15.4 (19E287)
software - application:
brave, 1.8.86 Chromium: 81.0.4044.129 (Official Build) (64-bit)
firefox, 76.0 (64-bit)
vivaldi, 3.0.1874.33 (Stable channel) (64-bit)

**Comment by ldexterldesign** [comment]
FYI the address bar popup (i.e. off the extension button/icon) copy button seems to work OK:

 <img width="435" alt="Screenshot 2020-05-06 at 20 02 43" src="https://user-images.githubusercontent.com/1715809/81212041-91317e00-8fd4-11ea-9524-bd937b3a9f42.png">

**Comment by perry-mitchell** [comment]
Hi @ldexterldesign - Apologies for not getting back earlier. Are you still able to reproduce this issue? I cannot on the current build.

**Comment by ldexterldesign** [comment]
2.17.0 yes

**Comment by perry-mitchell** [comment]
Is it possible that it's an issue with Vivaldi? Haven't seen any other reports like this for Chrome/Firefox.

**Comment by ldexterldesign** [comment]
Yes, I guess it's possible

I will wait to see if the issue exists in 2.18.0 before investigating with Vivaldi

Cheers

**Comment by ldexterldesign** [comment]
Yes, issue exists in 2.18.0, both latest Vivaldi and Brave so, again, looks like a chromium issue

Anyone else verify this?

Sincerely

**Comment by perry-mitchell** [comment]
Not reproducible on my Mac nor Linux machine, in Chrome. Haven't yet tested in Brave.

@ldexterldesign Any chance you could try this on another **computer**?

**Comment by ldexterldesign** [comment]
Sorry, don't have access to another machine

I broke my policy and installed some Google products for you though, where I can still reproduce the issue

I still think it's a Chromium issue but it could be a quirk concerning my OS install. Still, weird it works in Firefox 😕.

I guess wait and see if anyone else can reproduce...

Sincerely

software - operating system: Apple, macOS, 10.15.5 (19F101)
software - application:
brave, 1.11.97
vivaldi, 3.1.1929.45
chromium, 86.0.4207.0
chrome, 84.0.4147.89

**Comment by perry-mitchell** [comment]
Hmm. I have a feeling it’s an OS thing, as I can’t reproduce it on any machine, and we haven’t seen another report. That being said, I’m happy to leave this open until we find what the cause. You could open the inspector in the pop up menu to see if there’s an error when you click the copy button.

**Comment by ldexterldesign** [comment]
When I load the [iframe src] in a new tab the button copies as expected:
<img width="1904" alt="Screenshot 2020-07-21 at 00 19 17" src="https://user-images.githubusercontent.com/1715809/87995593-d9e2d880-cae7-11ea-8b93-ab46f8ca0314.png">

[iframe src]: chrome-extension://heflipieckodmcppbnembejjmabajjjj/dialog.html#/

**Comment by ldexterldesign** [comment]
FYI I plan to reinstall [macOS] fresh ~Oct/Nov so will follow up then regardless 

[macOS]: https://en.wikipedia.org/wiki/MacOS_Big_Sur

**Comment by perry-mitchell** [comment]
@ldexterldesign Hmm, but we don't use `execCommand` to my knowledge: https://github.com/buttercup/buttercup-browser-extension/search?q=execCommand&unscoped_q=execCommand

We use the [`navigator.clipboard` API](https://github.com/buttercup/buttercup-browser-extension/blob/4c920b83a7d8f67d70e208f9907f03a7e0e1e057/source/shared/library/browser.js#L23-L25).

Upon looking further into this, I can see that we actually have a _permissions_ issue: 

![image](https://user-images.githubusercontent.com/3869469/88452625-fa54bf00-ce68-11ea-83ce-582ff3e331d0.png)

And we [don't have that permission set](https://github.com/buttercup/buttercup-browser-extension/blob/4c920b83a7d8f67d70e208f9907f03a7e0e1e057/resources/manifest.json#L42-L50), so that's most certainly an issue - if not _the_ issue. 

Thanks for looking into this! Seems we have something we can try at least.

**Comment by perry-mitchell** [comment]
Ok, so I tested in Brave (1.11.101) on Ubuntu 18 and could not reproduce. I'll still add the permission, but I doubt it'll fix the issue for you.

At this stage I think the issue might be a local one, and not something other users are experiencing (due to the fact that I can't reproduce it across multiple computers and browsers, across multiple vaults). I'll leave it open for you to test on Mac, however.

**Comment by ldexterldesign** [comment]
> I'll still add the permission, but I doubt it'll fix the issue for you.

Is this fix in 2.23.0?:
* If yes then that hasn't fixed it for me
* If no then I'll check back later

Sincerely

**Comment by perry-mitchell** [comment]
> Is this change in 2.23.0
 @ldexterldesign yes - [here](https://github.com/buttercup/buttercup-browser-extension/blob/master/resources/manifest.json#L42)

Happy to try more hands-on tactic's, as well. If you're able to reproduce in a secure machine, I'd be more than happy to use team viewer or something to debug on the fly. Or if you find some way for us to reproduce the issue, I'll do my best to jump on fixing it immediately.

**Comment by ldexterldesign** [comment]
FYI

> I have a feeling it’s an OS thing, as I can’t reproduce it on any machine, and we haven’t seen another report.

Created a fresh macOS account, which shares browser installs but generates new browser profiles - as close as I can get to a macOS reinstall - and same issue so, yes, can only think it's OS specific

Also tested a local vault, in addition to my dropbox one, and same issue

I'll close this issue for now and reopen if it's still an issue after I reinstall macOS

Thank for help offer(s)

Sincerely
