### ISSUE TITLE
Search doesn't find any results on 2.16

### ISSUE THREAD

**Issue by ttamminen** [buttercup/buttercup-browser-extension#342]
I was able to get the Buttercup Browser Extension to a state where the search doesn't find anything even though the Vault is unlocked. The Buttercup version is 2.16 and I'm using Brave (Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)).

![buttercup](https://user-images.githubusercontent.com/1038081/86210175-cf828e00-bb7c-11ea-8fee-1b7d7ebedaa0.gif)

Yesterday, everything worked correctly so I am assuming it is the latest release that broke the search.

**Comment by morojgovany** [comment]
Same thing,
I think this il related to #197 with CORS restrictions, I added the header `'Access-Control-Allow-Origin' '*' always` on my webdav and i'm still blocked, with the error in console `net::ERR_BLOCKED_BY_CLIENT` in chrome and `Reason: CORS request not HTTP` in firefox.
Any advice would be welcome !
Thanks

**Comment by ldexterldesign** [comment]
Related:
https://github.com/buttercup/buttercup-browser-extension/issues/150
https://github.com/buttercup/buttercup-browser-extension/issues/157
https://github.com/buttercup/buttercup-browser-extension/issues/283

Would be amazing to get these issues done

Sincerely

**Comment by moussaclarke** [comment]
Possibly related - login inputs don't see that vault is unlocked since 2.16 update. Also have the same behaviour with search.

Chrome 83.0.4103.116

<img width="867" alt="Screenshot 2020-07-01 at 17 58 52" src="https://user-images.githubusercontent.com/13017858/86271443-c4535080-bbc4-11ea-8e0e-71fb6f626ca6.png">

**Comment by moussaclarke** [comment]
https://github.com/buttercup/buttercup-browser-extension/issues/343

**Comment by bulbil** [comment]
Wow, thanks for addressing this so quickly @perry-mitchell ! Browser Extension release 2.16.1 resolves my issue (FF 76.0.1 / MacOS 10.14.6)

**Comment by moussaclarke** [comment]
2.16.1 resolves 👍 Think this can be closed!

**Comment by ldexterldesign** [comment]
Fixed in latest Firefox but not in latest Brave/Vivaldi so needs testing

Regards

**Comment by ldexterldesign** [comment]
Sorry, just seen Firefox has 2.16.2 while Brave/Vivaldi still has 2.16.1

Ignore me, presuming y'all are on it and waiting for Chrome store to update...

Apologies

**Comment by perry-mitchell** [comment]
We're about to release (today) a new version with brand new searching. It uses fuse fuzzy searching for terms, and a domain-scoring search for URLs. It should hopefully prove better than the previous implementation. The version will be 2.17.0.
