### ISSUE TITLE
2.16.0 with all archives unlocked the buttercup modal states "no unlocked vaults"

### ISSUE THREAD

**Issue by tourtools** [buttercup/buttercup-browser-extension#343]
on Brave 1.10.97 (Chromium 83.0.4103.116)

<img width="652" alt="Schermata 2020-07-01 alle 20 53 30" src="https://user-images.githubusercontent.com/3681112/86280889-eeb10800-bbdc-11ea-9066-19ac089656e8.png">

<img width="1522" alt="Schermata 2020-07-01 alle 20 52 51" src="https://user-images.githubusercontent.com/3681112/86281060-33d53a00-bbdd-11ea-92e8-7ab5e8f856e6.png">

**Comment by eandersons** [comment]
Same using Firefox Developer Edition 79.0b2.

**Comment by Kryszak** [comment]
Same goes for Chrome 83.0.4103.116

**Comment by eandersons** [comment]
Just got the browser extension updated to 2.16.1, and the problem seems to be fixed.

**Comment by tourtools** [comment]
with the 12.16.1 it works, thanks
