### ISSUE TITLE
Firefox 2.16.1

### ISSUE THREAD

**Issue by aesthicc** [buttercup/buttercup-browser-extension#344]
Filling fields using buttercup is broken with the Firefox extension version 2.16.1. I can search and select entries, but fields don't get filled. Reverted to 2.15.1 for now.

**Comment by manzing** [comment]
Unfortunately, I have exactly the same issue, filling and autosignin are broken using 2.16.1.

**Comment by perry-mitchell** [comment]
Yes, sorry for the issue! It's been fixed in [2.16.1](https://github.com/buttercup/buttercup-browser-extension/blob/master/CHANGELOG.md#v2162).
