### ISSUE TITLE
Can't login to Dropbox archive since 2.18.0 update

### ISSUE THREAD

**Issue by liloumuloup** [buttercup/buttercup-browser-extension#348]
Hi !
As said in the title, since the update 2.18.0, i can't login to my Dropbox archive. Fortunately, the desktop app still works like a charm.

- Firefox : 78.0.1 (64 bits)
- OS : Ubuntu 18.04.4 LTS
- Buttercup desktop : 1.10.1

Error when login : 

```
Failed unlocking archive
Unable to unlock archive (30def91b-7ffc-4c6b-a7a8-9022e4683131): Unlocking archive source (30def91b-7ffc-4c6b-a7a8-9022e4683131) failed: Failed unlocking source: Invalid credentials content (unknown signature)
```

Do not estimate if there is some missing information. :-)

King regards.

**Comment by perry-mitchell** [comment]
Hi @liloumuloup - I'm unable to reproduce the issue on 2.17 or 2.18 on Chrome/Firefox. Can you please try removing and re-adding it?

**Comment by liloumuloup** [comment]
Thank you for your very fast answer.

Removing the archive and re-adding it worked. 

Thanks a lot for your help and sorry for the disturbance.

**Comment by perry-mitchell** [comment]
Hey no worries! Sorry for the trouble. It’s possible that during some update some data became corrupted in the local entry stored in browser memory. Glad that helped 👍
