### ISSUE TITLE
Fix form input resizing when entering text (e.g. ebay.com) #Bug

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-browser-extension#349]
Hey,

Hope you're well

Thanks for software

As title

# Steps to reproduce issue

1. Visit http://ebay.com
2. Enter text into form input

# Unexpected behaviour

Form input resizes with each character entered

# Expected behaviour

Form input does not resize

Screen cast: https://www.dropbox.com/s/u472hcsmidjzlsv/foo.webm

FYI tested in latest Firefox with same issue and will try remember to report back if I find the same issue with other websites

If you're reading and:
* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

If you have any issues (e.g. questions/queries) then happy to help

Keep up good work

Hope this helps

Sincerely

hardware: Apple, MacBook Pro (16-inch, 2019)
software - operating system: Apple, macOS, 10.15.5 (19F101)
software - application: Vivaldi, 3.1.1929.45 (Stable channel) (64-bit)
software - application: Buttercup, 2.18.0

**Comment by perry-mitchell** [comment]
That's... not a good thing. Indeed a bug. Thanks for reporting!

This is most likely part of a larger issue, which is what should we do if the Buttercup button breaks the input? I think moving to having an icon/button inside the input is a better idea, but this will conflict with some other password managers.

**Comment by ldexterldesign** [comment]
FYI not experiencing this issue any more

**Comment by perry-mitchell** [comment]
We updated how the icon is created and positioned in #354, and must have missed this issue sorry.
