### ISSUE TITLE
Browser/app crash while unlocking

### ISSUE THREAD

**Issue by toniobido** [buttercup/buttercup-browser-extension#356]
Hi, 

When I try to unlock my vault on Opera, Chrome, Windows (lastest stable versions), RAM grow up to 2500Mo and tab crash.

![image](https://user-images.githubusercontent.com/14336821/89110204-b1909d80-d448-11ea-922f-fdd21d0e283e.png)

I tried to uninstall and reinstall buttercup extension and when i try to add a new vault, it's almost the same but after tab crash the vault is well added nevertheless

On Android app I can only open vault on "read only" mode.
If you want more details, I will gladly give you some.

Thank for your job

edit : reading the issues #355 , i notice that my vault size just exceed 100Mo

**Comment by perry-mitchell** [comment]
Thanks @toniobido - This seems to be entirely related to #355. I'll close in favour of that issue - please use it to track progress.
