### ISSUE TITLE
Can't save generated password...

### ISSUE THREAD

**Issue by saadfarooq** [buttercup/buttercup-browser-extension#360]
I got through the forgot password flow on a website. Use the generate password context menu, insert generated password in the password verification field. Everything works fine. But don't get any popups to update the password, so I just go the vault to update, but the insert generated password field is not available there. So I have to generate the password, copy it manually, then save it.

**Comment by perry-mitchell** [comment]
@saadfarooq Sometimes Buttercup fails to detect when a form (login) has been submitted. In these cases, simply open the stored logins:

![image](https://user-images.githubusercontent.com/3869469/90984534-3bcaae00-e57e-11ea-87b4-73d12850e97d.png)

![image](https://user-images.githubusercontent.com/3869469/90984559-5735b900-e57e-11ea-8d4e-9a295417c073.png)

It's not ideal but it should present any logins that might not have been seen by Buttercup.
