### ISSUE TITLE
Error when adding vault on webdav nextcloud

### ISSUE THREAD

**Issue by rmccullagh99** [buttercup/buttercup-browser-extension#361]
When I attempt to do so, I get this error:

Failed connecting to 'webdav' resource
A connection attempt to 'http://192.168.0.40:8000/remote.php/dav/files/rmccullagh/.pass/Main.bcup' has failed: Cannot read property 'getDirectoryContents' of null

I got the same error with and without specifying the location of the vault on the server (/.pass/Main.bcup)

**Comment by perry-mitchell** [comment]
Although this error is indeed ugly and not terribly insightful, it's simply indicative of a connection error, and a problem with your server. We don't actively debug Nextcloud/ownCloud issues as they're normally a problem with the server config (and the fact that neither properly support CORS, and this conflicts with web access).

I'm also not sure that Buttercup should work when accessing local insecure URLs, but I can't be certain.

WebDAV is currently working fine for me on my own ownCloud (modified to allow CORS) and on Yandex (Disk webdav service), so I don't think that there's an issue with our WebDAV client.

I'll close this issue for now as I don't think there's anything we can fix on our side. If you find an issue with our implementation or a bug in our [connection logic](https://github.com/perry-mitchell/webdav-client), I'd happily reopen this.
