### ISSUE TITLE
Popup / Dialog very slow to open

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-browser-extension#368]
After running for some time, the popup menus are very slow to open.

**Comment by perry-mitchell** [comment]
Closing in favour of #370

**Comment by perry-mitchell** [comment]
Re-opening due to continual slowness that gets worse after some time. Memory and CPU are not growing for me, but might be for some other users. I suspect the issue is with the search system, which might be slow to populate. Need to run some timer checks in development to see where the slow part is.

**Comment by ldexterldesign** [comment]
FYI

My browser's been open for 24 hours and popup won't appear at all today

Had to restart browser

Hope it helps

Sincerely

<img width="1904" alt="Screenshot 2020-11-06 at 19 19 41" src="https://user-images.githubusercontent.com/1715809/98405975-0c97e900-2065-11eb-9f7c-385c8cacd954.png">

**Comment by perry-mitchell** [comment]
Issue was with search performance, which has been improved in core and now in the extension.

**Comment by ldexterldesign** [comment]
Feel free to close issue

I'll come reopen if I don't see an improvement in the next week

❤️

**Comment by perry-mitchell** [comment]
Will be released as 2.23.1 :+1:

**Comment by ldexterldesign** [comment]
No, still not fixed for me

If I can be any further help then please let me know

I suggest to reopen this issue

Sincerely

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
Managed to catch activity in task manager, looks to be CPU spikes causing the interaction delays..?

<img width="1440" alt="Screenshot 2021-04-12 at 00 08 56" src="https://user-images.githubusercontent.com/1715809/114324702-73916080-9b23-11eb-88ec-2b34138236f7.png">

Hope this helps

Sincerely

**Comment by ldexterldesign** [comment]
So when I experience the delay...

Idle the extension is ~25-33% CPU:
<img width="1792" alt="Screenshot 2021-04-20 at 17 45 00" src="https://user-images.githubusercontent.com/1715809/115434220-5da92d00-a200-11eb-8636-d099e27ae3c7.png">

... but if I click the extension button repeatedly then I can get CPU to ~125%:
<img width="1792" alt="Screenshot 2021-04-20 at 17 44 38" src="https://user-images.githubusercontent.com/1715809/115434360-84fffa00-a200-11eb-9b7f-25f093b04136.png">

Hope this helps

Sincerely

PS thank you for v2! 🥰

**Comment by ldexterldesign** [comment]
👋

I think this issue should be reopened 🤔

After clicking extension icon/button it still takes ages for it to open (i.e. sometimes 10 or 20 seconds)

It doesn't appear to be CPU related judging from task manager..?

Is anyone else experiencing this on macOS/Vivaldi?

Regards

**Comment by ldexterldesign** [comment]
@perry-mitchell 👋

Pretty sure this is the cause:
<img width="381" alt="Screenshot 2022-04-20 at 05 21 29" src="https://user-images.githubusercontent.com/1715809/164149906-f3a8fee1-b178-4cd2-a916-00d13ca856e0.png">

I've turned the feature off and popup is reliable to activate and much more responsive

I suggest this is the default setting unless performance can be improved. Atleast if new users turn the feature on and see a UX hit they'll know to turn it off again. I simply don't mess around in settings much.

I wish I'd have known 1.5 years ago as it would have saved me so much time!

Hope this helps
