### ISSUE TITLE
Vaults disappear

### ISSUE THREAD

**Issue by eandersons** [buttercup/buttercup-browser-extension#369]
Vaults disappear after a Firefox (Developer Edition) browser is restarted or the extesion is disabled and reenabled.
Everything is fine in Chromium.

OS: Windows 10 and macOS Catalina
Browser: Firefox Developer Edition 81.0b5 (64-bit)
Extension version: 2.21.0

**Comment by jokeyrhyme** [comment]
Happening for me, too
OS: Archlinux
Firefox: 80.0.1 (64-bit)
Extension: 2.21.0

**Comment by perry-mitchell** [comment]
Maybe something to do with how FF manages **sync storage**? Buttercup stores all settings there, including the vaults that have been added. If FF clears that, then the extension will lose its state. Someone could easily confirm this by checking the storage areas before and after disabling the extension.

I don't have time right now to look at this but please let me know if you find something - we can try to find a work around.

**Comment by frederic-klein** [comment]
@eandersons @jokeyrhyme try https://github.com/buttercup/buttercup-browser-extension/issues/367#issuecomment-687204818

**Comment by eandersons** [comment]
@frederic-klein, it seems that it solved this issue on Windows 10 and macOS. Thank you!

**Comment by perry-mitchell** [comment]
Great news! Thanks for the help @frederic-klein :)

I'll close this in favour of #371 which should address the quota issue.
