### ISSUE TITLE
CPU usage on Mac OS Catalina, Brave: 1.13.82, Chromium: 85.0.4183.83

### ISSUE THREAD

**Issue by tourtools** [buttercup/buttercup-browser-extension#370]
after about 5 minutes Buttercup extension became unaccessible, its process sucks 100% of CPU:

<img width="937" alt="Schermata 2020-09-03 alle 22 16 18" src="https://user-images.githubusercontent.com/3681112/92163004-4ebd6800-ee33-11ea-885f-f4140c9f9c3e.png">

after killing the process and reloading the extension it follows the same behavior again and again:

<img width="470" alt="Schermata 2020-09-03 alle 22 16 33" src="https://user-images.githubusercontent.com/3681112/92163035-5846d000-ee33-11ea-9b52-f0625c072413.png">

**Comment by perry-mitchell** [comment]
Thanks @tourtools - The reason for this is the fact that Buttercup core (5.2.1) has a very dramatic memory leak in its auto-update function, which causes large amounts of objects to be addressed and tied-up in permanent references of each other, so GC never takes care of them.

I'm currently addressing this in the core..

**Comment by perry-mitchell** [comment]
The base issue will be dealt with here: buttercup/buttercup-core#282

**Comment by tourtools** [comment]
thanks @perry-mitchell for the prompt response, I'll follow the core issue 282

**Comment by perry-mitchell** [comment]
So it seems like the issue is solved for me, though I haven't tested for many hours. The memory and CPU consumption is far better than it was, and I've fixed a number of poorly-performing vault item lookups in the core library. I'm about to do a release - v2.22.0.

**Comment by tourtools** [comment]
tested with Brave with the new plugin/core v 2.23.0 and the results are quite the same, maybe it takes a little bit more time to get stuck but after a while the process reach the 100% of CPU and the plugin became anavailable:

<img width="1148" alt="Schermata 2020-09-08 alle 19 40 56" src="https://user-images.githubusercontent.com/3681112/92510100-9bc28500-f20b-11ea-80e7-a28bbc71f38e.png">

**Comment by ldexterldesign** [comment]
FYI performance still bad for me in 2.23.0

**Comment by ldexterldesign** [comment]
I think this issue or https://github.com/buttercup/buttercup-browser-extension/issues/368 should be reopened

When CPU is high (i.e. >10%) the popup is delayed:
<img width="1904" alt="Screenshot 2020-10-03 at 20 40 14" src="https://user-images.githubusercontent.com/1715809/95000544-aa594d80-05b9-11eb-9379-1d71bd04692f.png">

Hope this helps

Sincerely

software - OS: Apple, macOS, 10.15.7 (19H2)
software - application: Vivaldi, 3.3.2022.47 (Stable channel) (64-bit)
software - extension: Buttercup, 2.23.0

**Comment by perry-mitchell** [comment]
@ldexterldesign Good point, I've reopened that issue.
