### ISSUE TITLE
Failed Saving Credentials

### ISSUE THREAD

**Issue by denali1** [buttercup/buttercup-browser-extension#372]
Failed saving credentials
Failed adding new entry: Cannot read property 'secondary' of null

This is on Microsoft Edge Chromium Version 86.0.622.3 (Official build) dev (64-bit)

**Comment by perry-mitchell** [comment]
What datasource type? On saving of credentials or unlocking a vault perhaps?

**Comment by denali1** [comment]
Saving credentials from the dialog that opens when Buttercup encounters a new site.

**Comment by denali1** [comment]
Suddenly it's started working.  Same version of Buttercup extension and Edge.
