### ISSUE TITLE
Fix login - transferwise.com #Bug

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-browser-extension#373]
Hey,

Hope you're well

Thanks for software and sterling updates

As title

Login is failing with Buttercup extension installed

With extension installed, before (i.e. form submission submit) and after (i.e. form submission submit with error) DOM diffs reveal an `input type` has (unexpectedly) changed (see screenshot, line 45) - could Buttercup be responsible for this?

Without the extension installed it's tricky to get an after diff as the form submission is successful so I can't be sure the input type change issue is Buttercup specific

Screen shot:
<img width="1904" alt="Screenshot 2020-09-07 at 23 37 22" src="https://user-images.githubusercontent.com/1715809/92419094-4763ca80-f163-11ea-9369-eb8af145620a.png">

Screen cast:: https://www.dropbox.com/s/9rin1lgvdbsrmlv/foo.webm?dl=0

If you're reading and:
* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

If you have any issues (e.g. questions/queries) then happy to help

Keep up good work!

Hope this helps & to hear back

Sincerely

software - OS: Apple, macOS, 10.15.6 (19G2021)
software - application: Vivaldi, 3.2.1967.47 (Stable channel) (64-bit)
software - extension: Buttercup, 2.23.0

**Comment by perry-mitchell** [comment]
Buttercup doesn't change the input type, it simply attaches to it. [This](https://github.com/buttercup/buttercup-browser-extension/blob/master/source/tab/launch.js#L28) is the area of interest, and you can see that it simply sets a dataset value, not an attribute. It does modify padding but this is simply for aesthetics (when placing the button).

**Comment by ldexterldesign** [comment]
Thanks for reply

Forget whether I did before but just tested with Firefox and Brave and confirmed the same issue

Very weird, I can only think there's some script conflict between TW and BC, otherwise why would their login function with BC disabled?

I've already spent a bunch of [time] trying to diagnose this

[time]: https://twitter.com/ldexterldesign/status/1302069962216017922

**Comment by ldexterldesign** [comment]
Also, TW error is a bit sh#tty (i.e. both technically and non-technically)!

**Comment by ldexterldesign** [comment]
Read through the module

Long shot but could the ‘.stopPropagation’ be the conflict here?

Sincerely
