### ISSUE TITLE
Enhance form login detection #Enhancement

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-browser-extension#374]
Hi!

No Buttercup form interaction (i.e. login buttons) with [Notion]

<img width="1904" alt="Screenshot 2020-09-09 at 00 52 46" src="https://user-images.githubusercontent.com/1715809/92538561-e6a5c200-f236-11ea-8ce5-1161c7b98c74.png">

Tested in the following, so doubtful it's browser incompatibility:
* Firefox, v80.0.1 (64-bit)
* Vivaldi, v3.3.2022.36 (Stable channel) (64-bit)

Sorry for brevity

Hope this helps!

Sincerely

[Notion]: http://notion.so

**Comment by perry-mitchell** [comment]
Notion isn't using a `<form>` component, which is bad practice. This makes it hard for buttercup to find where/if a login button should appear. Ideally we wouldn't need a form, but my fear is that this will create many false-positives. Notion should ideally fix their markup.

**Comment by perry-mitchell** [comment]
Let's keep this open, as we might find a way arounnd it.

**Comment by ldexterldesign** [comment]
FYI https://twitter.com/ldexterldesign/status/1309682673007419394

**Comment by perry-mitchell** [comment]
@ldexterldesign Ha, thanks! Fixing the web one tweet+site at a time :smile: 

I doubt they'll change it, and it simply means that we, the consumer, need to update how we detect login forms.

**Comment by ldexterldesign** [comment]
To be fair I've requested a bunch of features since I started using their app' and they've been responsive. Only time will tell how many requests make it into production and whether I stay using the app'.

Wow, thanks for adding bug status - harsh!

Sincerely

**Comment by ldexterldesign** [comment]
Same issue with http://reddit.com

<img width="1904" alt="Screenshot 2020-09-30 at 03 35 23" src="https://user-images.githubusercontent.com/1715809/94636847-0f692680-02ce-11eb-8057-0ad831e8c4d8.png">
<img width="1904" alt="Screenshot 2020-09-30 at 03 35 12" src="https://user-images.githubusercontent.com/1715809/94636840-08daaf00-02ce-11eb-83d8-c25090ae01fb.png">

> [...] we, the consumer, need to update how we detect login forms

Mmm, think you're right

TBH Injecting BC buttons in every form input would be better than nothing

Sincerely

Sincerely

**Comment by ldexterldesign** [comment]
🧹 https://github.com/jellyfin/jellyfin-web/issues/1964

**Comment by ldexterldesign** [comment]
@perry-mitchell what do you make of [Buttercup not ignoring hidden form inputs]?

Hope to hear back

Sincerely

[Buttercup not ignoring hidden form inputs]: https://github.com/jellyfin/jellyfin-web/issues/1964

**Comment by perry-mitchell** [comment]
> Is all the BC form input button injection functionality in launch.js?

Actually no, it comes from the index here: https://github.com/buttercup/buttercup-browser-extension/blob/master/source/tab/index.js#L37-L76

And the engine to run that is [locust](https://github.com/buttercup/locust), our login form scraper.

> TBH injecting BC buttons in every form input would be better than nothing

This is actually a nice idea for a setting, however the issue lies in the ability to detect _login_ forms, as Buttercup would not know how to fill a regular form. It only knows that usernames go in username fields and so on, so there'd be no point in adding buttons to other forms.

I think that Buttercup already adds them to all login forms it finds, too. 

The remaining issues in my eyes for improved login form detection are:

 * Iframe support (this repo + locust)
 * No-form-element support (locust)

**Comment by ldexterldesign** [comment]
Same issue with http://giffgaff.com

<img width="1904" alt="Screenshot 2020-10-06 at 12 58 31" src="https://user-images.githubusercontent.com/1715809/95200018-9b4ee700-07d5-11eb-8bca-ee96faa6b8d4.png">

Sincerely

**Comment by ldexterldesign** [comment]
> This is actually a nice idea for a setting, however the issue lies in the ability to detect login forms, as Buttercup would not know how to fill a regular form. It only knows that usernames go in username fields and so on, so there'd be no point in adding buttons to other forms.

Yes, I realised it was a stupid comment after I wrote it, doh!

**Comment by ldexterldesign** [comment]
> @perry-mitchell what do you make of Buttercup not ignoring hidden form inputs?

BUMP

**Comment by perry-mitchell** [comment]
> what do you make of Buttercup not ignoring hidden form inputs?

Yeah, buttercup doesn't ignore hidden inputs. It should fetch all forms but the inputs that are used to deter autocompletion probably break it. This functionality would need to be handled [here](https://github.com/buttercup/locust/blob/master/source/inputs.js).

I've created an issue for the hidden inputs: buttercup/locust#37, and there was an existing one for the `<form>`less logins: buttercup/locust#20

**Comment by perry-mitchell** [comment]
> if some form input(s) exist/detected then don't show individual input buttons just show one generic call to action (e.g. located top right)

This is a great idea! I'd entertain a separate issue for this. Would be great under a setting, too, so users can choose what they prefer.

> The only use case I can think of where users (i.e. me) may want to be selective about the inputs entered

There are some arguments I can think of for having them on-form:

 * Multiple forms, which I see often (login vs register, are often on the same page and both get recognised)
 * More eye-catching for some users - exactly like a CTA but in situ
 * Doesn't accidentally cover something somewhere else on the page, if we show a floating button in some corner (I have a lot of experience putting floating buttons on sites, it's a HUGE pain haha)
 * Easy to find - The controls are exactly where you expect them to be, on the login

And buttercup has auto-login functionality, so often times you don't even need to find the login, you can do this from the browser menu.

**Comment by ldexterldesign** [comment]
You've unconvinced me this is a good idea but I'll play devils advocate for a bit...

> Multiple forms, which I see often (login vs register, are often on the same page and both get recognised)

Yes, this is what I mentioned above:
> The only use case I can think of where users (i.e. me) may want to be selective about the inputs entered would be order forms where (trivially) I want to populate the first name input but not the last name input. I don't currently use BC for this (but I would like to à la new BC features).

We could potentially solve this more eloquently by having a bunch of selects in the CTA:
[x] first name
[ ] last name

or:
# register
[ ] name
> Lewis
[ ] username
> ldexterldesign
[ ] email
> foo@foo.com

# log in
[ ] username

**Comment by ldexterldesign** [comment]
Hi @perry-mitchell,

I hope you're well

> Notion isn't using a <form> component

Did something change in the codebase because Notion auto login now functions (although it does now seem to use `<form>`)?

Aside, reddit login now functions too (always used `<form>`)

Aisde, giffgaff still not detecting `username`

Hope to hear back

Sincerely

**Comment by danline** [comment]
Hi @perry-mitchell! This is a great library and it works amazing in most scenarios. I've been following this thread. Twitter login and Apple (appstoreconnect.apple.com) also don't use forms so autofill doesn't work. I worry that since Apple is going in this direction too that it might become the norm eventually. Any plans to support autofill where there is no login form on the page?

**Comment by perry-mitchell** [comment]
Yes, there's a refactoring of our login form detection on the horizon.. it won't require any particular elements like <form>. It'll also supported nested iframes which is a huge problem for logging in as well.

**Comment by danline** [comment]
@perry-mitchell that's awesome! Can't wait!

**Comment by perry-mitchell** [comment]
The future is looking promising:

![image](https://user-images.githubusercontent.com/3869469/190496248-f1cdffa1-7f22-440a-980b-afdef44afbf0.png)
(Reddit)

![image](https://user-images.githubusercontent.com/3869469/190496322-95bc5995-3ed6-45c9-9cd3-a1208e21ecbd.png)

![image](https://user-images.githubusercontent.com/3869469/190496411-e50c924e-e19d-446e-a5a8-daac6831c1e0.png)
(DigitalOcean)

Doing some testing and updates to the detection logic in prep for the new manifest v3 support. It should be vastly improved once out.

**Comment by ldexterldesign** [comment]
My god, I am so looking forward to this

**Comment by ldexterldesign** [comment]
https://www.youtube.com/watch?v=T1GBbcnwOHs

**Comment by perry-mitchell** [comment]
Login form detection etc. has been improved in V3, but not all issues here have been addressed. Still need to check the hidden inputs and double-check the input button type. Right now V3 uses the old button type, and supports the new type, but doesn't provide an option to change it. That can be added in an upcoming issue.

#464 for the login button customisation.
