### ISSUE TITLE
Ebay.de payments fail with extension enabled

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-browser-extension#376]
Post-robot fails when attempting to make payments on pay.ebay.de, seems to be some kind of conflict.

**Comment by adamturcsan** [comment]
Ebay uses PayPal AFAIK. I also had issues with PayPal on https://donate.mozilla.org/ as an example to test the issue.

**Comment by perry-mitchell** [comment]
The issue is because both systems use PostRobot, and ours is conflicting with eBay's. We use it, as they do, to communicate between iframes easily. We simply need to move to a personalised postMessage handler to avoid using the same message formats as post-robot.

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
