### ISSUE TITLE
Failed adding new entry: NetworkError when attempting to fetch resource

### ISSUE THREAD

**Issue by Tim-Erwin** [buttercup/buttercup-browser-extension#377]
My vault is a local file. When I try to add a new entry from the browser extension, I get this error:

    Failed saving credentials
    Failed adding new entry: NetworkError when attempting to fetch resource.

If you tell me how, I'm willing to help with any further debugging.

**Comment by perry-mitchell** [comment]
@Tim-Erwin is this via the local-file datasource type? Do you have the desktop app running with the browser access enabled?

![image](https://user-images.githubusercontent.com/3869469/95015422-792e5b00-0655-11eb-88a4-956050633dcd.png)

**Comment by Tim-Erwin** [comment]
It is the local file datasource type, yes. I didn't know, that desktop app has to be running all the time. So I started it, unlocked the vault in Firefox, was able to add credentials. Wonderful. So in principle it works, I better error message might be useful.

The new entry did not show up in the desktop app, however, so I restarted it, and then I could see the entry. However, when I then added another set of credentials in Firefox, I got
<img width="346" src="https://user-images.githubusercontent.com/802148/97079593-ac7d5d80-15f5-11eb-8e8d-c4d20997408f.png">

In the vault view in Firefox, the entry was listed anyway, in the desktop app, it wasn't. After closing and opening the vault in Firefox, the entry was gone there as well.

So, overall, I'd say, the process is quite fragile. Probably, there's a reason for that, but as a user it's a bit cumbersome to make sure to have done things in the right order, especially if you don't know / understand it.

Thanks for the hint, anyway.

**Comment by perry-mitchell** [comment]
Yes, the desktop app is undergoing an upgrade - once @sallar finishes that it'll automatically handle updating in the background. The process isn't quick due to the nature of some other datasources (webdav etc), so we poll for changes and don't live-update the vaults. That's coming soon.

> However, when I then added another set of credentials in Firefox, I got

Are you still seeing this `r is null` error repeatedly? That definitely sounds like a bug.

**Comment by Tim-Erwin** [comment]
I cannot reproduce this error right now. Maybe that's because I have internalized the correct order and cannot imagine any other way any more :) So, all that remains is a better error message.

**Comment by perry-mitchell** [comment]
Closing for now. Let's re-open if you see it again.
