### ISSUE TITLE
Adding local vault to extension using Buttercup AppImage

### ISSUE THREAD

**Issue by eandersons** [buttercup/buttercup-browser-extension#378]
Is it possible to add a local vault file to the browser extension if the Buttercup AppImage is used on the desktop?
I tried to, but unsuccessfully.

OS: Arch Linux
Extension version: 2.23.0
Browsers:

- Firefox Developer Edition (82.0b9);
- Chromium (86.0.4240.75);

Errors when trying to connect to the desktop application:

- Firefox Developer Edition:
  > Failed connecting local vault
  > An error occurred when connecting: NetworkError when attempting to fetch resource.
- Chromium:
  > Failed connecting local vault
  > An error occurred when connecting: Failed to fetch

**Comment by perry-mitchell** [comment]
@eandersons Have to ask - but did you have the Enable-browser-access setting enabled on the desktop? Could you do like a `netstat -plutn` and check for port `12821`?

**Comment by eandersons** [comment]
I did not enable browser access before in System > Enable Browser Access. I just did it now, and everything is fine.
Thank you for your response and sorry for the inconvenience from my side!
