### ISSUE TITLE
Vaults gone after restarting system (using WebDav with OwnCloud on Firefox)

### ISSUE THREAD

**Issue by CSparn** [buttercup/buttercup-browser-extension#380]
Hi,
I'm using buttercup a very long time now and I really like it!
But since the direct support for owncloud was migrated to WebDav I have a weird problem:

I'm connecting my vault in owncloud over WebDav with my firefox browser. When it's done, everything is 
working fine. But when I restart my system and start firefox again, the connection to my vault is gone and
I have to add it again in the browser addon. I checked every option in firefox and all the addons I use, but 
none of them seems to cause the problem.

Does anyone have an idea why this is happening?

Greetings
c.sparn

**Comment by julianpoemp** [comment]
perhaps a duplicate of #369 . The solution could be: https://github.com/buttercup/buttercup-browser-extension/issues/367#issuecomment-687204818

**Comment by perry-mitchell** [comment]
Agreed with @julianpoemp - Closing in favour of #384
