### ISSUE TITLE
Buttercup suggests last entry used instead of the correct one (first time only)

### ISSUE THREAD

**Issue by swanknight** [buttercup/buttercup-browser-extension#381]
1. Go to a website, use Buttercup to login.
2. Go to a different, click on Buttercup icon (in field).

It will show the entry for the first website for the first time only, if you click away and click again it will then show the correct one.

Tested on Firefox 82

**Comment by andradei** [comment]
I can confirm that's happening consistently for me.

1. Go to Github.com, buttercup offers me my github autofill credentials
2. Go to Gitlab.com, buttercup offers me my **github** autofill credentials
3. I click away and click back on the _buttercup_ icon and it offer me the correct **gitlab** credentials

**Comment by badstreff** [comment]
Still an issue for me as well

Version and info

Buttercup Version
    2.24.1
Browser
    name: Firefox
    version: 88
    fullVersion: 88.0
    os: Windows
