### ISSUE TITLE
Buttercup does not recognize subdomains as the same website

### ISSUE THREAD

**Issue by swanknight** [buttercup/buttercup-browser-extension#382]
Example: entries stored for https://reddit.com will not work for https://old.reddit.com even though they are the same website.

**Comment by perry-mitchell** [comment]
Mine works fine (reddit account). It appears normally for me on old.reddit.com. Saved as:

![image](https://user-images.githubusercontent.com/3869469/99730466-2bff2f00-2ac5-11eb-8f50-6e1f16fa741e.png)
