### ISSUE TITLE
Minified React error #185 on editing entries using Firefox extension

### ISSUE THREAD

**Issue by ronaldodecampos** [buttercup/buttercup-browser-extension#385]
On editing entries using Firefox Extension -  version v2.23.0,  I got this message: 
Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.  in Blueprint3.EditableText
![image](https://user-images.githubusercontent.com/19539843/100274220-d4394b80-2f3c-11eb-919f-f265caab342a.png)

**Comment by perry-mitchell** [comment]
I'm not able to reproduce this, sorry. Current production versions work fine when editing entries.

Please verify that you're using the production version, on the current version of Firefox. This error sounds like a development issue and not something to do with the production extension.
