### ISSUE TITLE
It is not possible to enter diacritic characters in name and password field

### ISSUE THREAD

**Issue by eandersons** [buttercup/buttercup-browser-extension#389]
It is not possible to enter diacritic characters (for example, `ā`, `ļ`, `ņ`, `ū` and others) in name and password field (pressing single quote (apostrophe) key (`'`) followed by a letter key when Latvian keyboard input source is being used) when adding new vault or trying to unlock existing one on macOS using Firefox. Diacritic symbols must be copied from somewhere else and pasted in extension's input fields. Desktop application works fine with passwords that contain diacritic characters and there are no problems with them in other Firefox tabs. It seems that this is macOS and Firefox specific issue as in Chromium on macOS everything is fine, but I have to check other operating system and browser combinations.

Details:

- extension version: 2.23.1;
- browser: Firefox (Developer Edition; 84.0);
- OS: macOS Catalina.

**Comment by perry-mitchell** [comment]
This sounds entirely like a browser/configuration issue to me - Buttercup doesn't exactly control the inputs in terms of what text can be entered. We _do_ use React, a front-end web framework, that controls the inputs - but I'd be very surprised if they had an i18n bug of this type.

**Comment by perry-mitchell** [comment]
@eandersons Do other extensions, in the same browser, allow for entering such characters?

**Comment by eandersons** [comment]
@perry-mitchell, yes, it is possible to enter diacritic characters in other Firefox extensions on macOS computer.

**Comment by perry-mitchell** [comment]
I'm not sure how test this myself.. It sounds weird that it'd be just a browser issue as the desktop app is _also_ using React to manage inputs. I'll mark this as a bug and would hope that someone might be able to contribute a fix or provide an easy way to reproduce on another keyboard, such as my US-english layout. I'm on Linux, so not sure if the OS makes a difference.

**Comment by eandersons** [comment]
This issue seems to be macOS + Firefox (or at least Developer Edition; I will try to check if this behaviour can be observed with regular Firefox) specific (I checked this on three Apple computers). I have not encountered problems with diacritic characters in vault name and password fields in other combinations — macOS + other browsers and other operating systems (Arch and Windows) + all browsers.

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
