### ISSUE TITLE
Storage option when adding new vault

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-browser-extension#390]
Allow the user to specify which storage type they want, when adding a vault:

 * Synchronised (if available) - Sync the vault alongside the user account
 * Local only - Store the vault in local browser storage

This would be useful for local files accessed via the desktop application.

**Comment by Logeshdas** [comment]
@perry-mitchell Is it possible to add Microsoft OneDrive vault option? If yes please let me know how to achieve it.

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
