### ISSUE TITLE
Authentication failed while decrypting content

### ISSUE THREAD

**Issue by K4mey** [buttercup/buttercup-browser-extension#392]
```
Failed selecting Google Drive vault
An error occurred when adding the vault: Adding archive failed: Failed unlocking source: Failed fetching Google Drive vault: Authentication failed while decrypting content
```
I have got this error and i can't access my vault but i know that I'm entering the wrong password, i need help since all my main social networks and logins are there..

**Comment by perry-mitchell** [comment]
> i know that I'm entering the wrong password

Unfortunately we can't help retrieve forgotten/lost passwords.
