### ISSUE TITLE
popup: copy to clipboard not working

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-browser-extension#393]
<div align="center">

![Bildschirmfoto 2020-12-16 um 09 46 13](https://user-images.githubusercontent.com/25926588/102325813-e6c70380-3f83-11eb-9bff-42330512340e.jpg)

</div>

1. Open the popup on an input element.
2. Click on one of the clipboard buttons, nothing will be copied to clipboard.

It does not work with Chrome and Brave, but it works with Firefox.

### Browser information

OS: MacOS 10.15.7
Browser: Google Chrome Version 87.0.4280.88 (Offizieller Build) (x86_64)
Browser: Brave Version 1.17.73 Chromium: 87.0.4280.67 (Offizieller Build) (x86_64)
Browser: Firefox 83
Buttercup Extension: 2.24.0

**Comment by perry-mitchell** [comment]
I haven't yet seen this issue, and I use the Copy button from this popup quite often. I'm using Chrome 87.0.4280.88. I just tested it again and it worked immediately. Can you try a different machine? Perhaps there's some issue with your clipboard?

**Comment by julianpoemp** [comment]
strange... I tested it with Windows 10 and I have the same problem, too. Perhaps my explanation wasn't as clear as it should be: I was reffering to the popup menu you can open next to the username text input on a website. I wasn't referring to the popup on the right top corner.

**Comment by perry-mitchell** [comment]
Ok, I finally reproduced this issue. Google actually contacted us for the purpose of removing a couple of unused permissions in our extension manifest, one of which was `clipboardWrite`. We were using another method of copying text, using the `navigator`, which seems to fail when trying to copy in the popup dialog **in-page**. The browser menu always worked for me at least.

After upgrading to the `clipboardWrite` method, copy seems to work in both places for me now. I'll release a fix momentarily.

**Comment by julianpoemp** [comment]
@perry-mitchell thank you very much for fixing this issue! I wish you a happy new year!

**Comment by perry-mitchell** [comment]
@julianpoemp Thanks for the patience! Happy new year mate!

Btw, it was released in 2.24.1.
