### ISSUE TITLE
Need to add Google drive vault each time after browser restart

### ISSUE THREAD

**Issue by romasochilov** [buttercup/buttercup-browser-extension#394]
Each time, when I restarting Mozilla Firefox browser, I need to add Google Drive access from the beginning. Tried to reinstall addon, but it didn't help. Have somebody similar issue?

**Comment by perry-mitchell** [comment]
What is the error you're seeing? Is it simply not there or does it fail to unlock? Can you look at the extension console logs to see if there's a failure?

**Comment by situplastik** [comment]
Same issue with WebDAV vault. I work with Firefox Developer Edition

FF: 93.0
Buttercup extension: 2.24.3
os: OS X 11.5.2

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
