### ISSUE TITLE
[Edge] Latest Version not working with buttercup extension

### ISSUE THREAD

**Issue by claywd** [buttercup/buttercup-browser-extension#398]
The latest version of edge has the exact same issue as #336 when trying to connect to nextcloud server. I've confirmed the browser extension is working in both Chrome and Firefox. Maybe a chromium problem?

**Comment by perry-mitchell** [comment]
@Claywd Did you install from the Edge store? If so that version is hideously out of date, due to a failure on Microsoft's part to help us get our account fixed. Please install the Chrome version in edge.

**Comment by Claywd** [comment]
tried that. broken there as well. works in chrome and firefox though.

**Comment by theuser17** [comment]
This problem has happened to me too.
I tested with browsers: Google Chrome, Mozilla Firefox but it did not work.
The plugin suggests previous passwords, but can not save the new password and gives an error.

OS: Windows 10 Enterprise 64-bit (Version: 21H2)
Browser1: Mozilla Firefox v96.0.2 (64-bit)
Browser2: Google Chrome v97.0.4692.99 (Official Build) (64-bit)

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
