### ISSUE TITLE
Disable Login Prompts not work on Firefox

### ISSUE THREAD

**Issue by situplastik** [buttercup/buttercup-browser-extension#401]
Adding domains into "Disabled Save-Details Prompts" is not showing on the list, but it works (I guess)

Version
2.24.1

Browser
name: Firefox
version: 85
fullVersion: 85.0
os: OS X

**Comment by perry-mitchell** [comment]
I just checked in FF 86 on OSX, and it works perfectly. When logging in to a new domain you can press the "cancel" icon on the dialog to disable for that domain. Domains will be saved like `test.com`. If you have an example domain that this is reproducible on, please share it so I can test this further..

**Comment by situplastik** [comment]
Sorry for the delay...

Here you have a recorded video showing the "Disabled Save-Details Prompts" tab on FF 89 (Developer edition). I tried to add `test.com` domain and the list doesn't update... I've tried in "private window" with only that addon active (to avoid possible problems with other addons)and the problem persist.

https://user-images.githubusercontent.com/19546264/117673367-07019400-b1ab-11eb-85db-268088b8b4b2.mov

**Comment by rvtb** [comment]
Same issue for me.

Vers 2.24.3
On Firefox 92.0

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
