### ISSUE TITLE
Unable to update archive

### ISSUE THREAD

**Issue by neldog2** [buttercup/buttercup-browser-extension#403]
I get this error when trying to create a group, rename a group, or add password entries.  For reference I am working with a google drive vault and am only using the browser extension on a few different machines.   I did previously import a keepass xml on the desktop but that is no longer in use.

Version 2.24.1

**Unable to update archive (<uuid>): Failed applying vault facade: Cannot read property 'secondary' of null**

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
