### ISSUE TITLE
Auto login doesnt'work

### ISSUE THREAD

**Issue by SuperDexter23** [buttercup/buttercup-browser-extension#406]
Hi i have install firefox extension but if i reopen the browser every time ask me to unlock the vaults, is possible to unlock automacally?

Thanks

**Comment by catcake** [comment]
Not possible, if this is what you're describing:

> Do you mean that between browser/computer restarts, that the vault would stay unlocked? If so, that's not possible as it'd require writing the password to browser storage, which would be insecure.

_Originally posted by @perry-mitchell in https://github.com/buttercup/buttercup-browser-extension/issues/397#issuecomment-798967942_

**Comment by perry-mitchell** [comment]
As mentioned above - there's no way to handle this safely right now. I too want this functionality, but not at the cost of exposing primary passwords in plain text, _anywhere_ on a user's computer. See #397 for more details.
