### ISSUE TITLE
BUG Passwords still gets auto filled even after vault is locked.

### ISSUE THREAD

**Issue by nikunjkumarnakum** [buttercup/buttercup-browser-extension#407]
Passwords still get auto filled even after the vault is locked, I tried clearing browser cache but it is the same. I am using v2.24.1 of browser extension for firefox v87.0 on my windows.

**Comment by perry-mitchell** [comment]
Buttercup does not autofill passwords without you telling it to. This is most likely your browser that is auto-filling.
