### ISSUE TITLE
Cannot save passwords to database from extension

### ISSUE THREAD

**Issue by hankster112** [buttercup/buttercup-browser-extension#411]
OS: Devuan GNU/Linux x64 (Debian fork)
Browser: Ungoogled Chromium
Buttercup Desktop Version: 2.6.0
Buttercup Extension Version: 2.24.3

**Issue**
Buttercup is unable to save logins to the local database. When attempting to save it will error out with:
Failed saving credentials
Failed adding new entry: Failed writing remote file: /path/to/buttercup/database.bcup
This happens whether or not the vault is locked or unlocked locally.

If you need more information I can provide it.

**Comment by yaoyi2008** [comment]
me tooooo.
help

**Comment by perry-mitchell** [comment]
Are you using the local database option? Is buttercup desktop running if so? It does not matter whether the vault exists or is unlocked/locked in the desktop - the desktop app simply transfers the locked vault file _to_ the extension when using this local mode - sending it back to the desktop app for writing when its updated.

**Comment by hankster112** [comment]
I am using a local database kept on my PC. The desktop application is running and unlocked. Where would the logs be located that are relevant to this issue?

**Comment by hankster112** [comment]
Still having the same issue with latest AppImage release and latest extension release (from May).

**Comment by perry-mitchell** [comment]
Hi @hankster112 - I'm sorry you're still seeing issues. Logs would indeed help as there should be some items logged when you try to connect. [For example](https://github.com/buttercup/buttercup-desktop/blob/master/source/main/services/fileHost.ts#L26). Please see [here](https://github.com/buttercup/buttercup-desktop#logs) for instructions on finding the logs.

**Comment by hankster112** [comment]
That only tells me where the logs are for the desktop application when the issue is with the Chrome extension. Where are the logs for that stored?

**Comment by hankster112** [comment]
After some more testing it seems that it is actually saving the login info but still displays an error prompt.

**Comment by perry-mitchell** [comment]
Closing for now. Without the logs there's not much to do here. Please investigate where to find them and attach them if the issue persists.

**Comment by perry-mitchell** [comment]
Apologies, logs are stored in both the console on the current window, and the developer console for the background script. [This SO answer](https://stackoverflow.com/a/10258029/966338) shows how you might find such logs.

Without those I cannot do much, so if you attach them I can reopen.
