### ISSUE TITLE
[Feature request] Add option to edit item right from the displayed result

### ISSUE THREAD

**Issue by testsetse** [buttercup/buttercup-browser-extension#414]
Currently, to edit an item, it requires an unnecessarily long effort. It would be way more helpful to have a context menu (or something) that allows editing the item right from displayed results or opens the editor in the vault.

Say I'm already on flickr.com already and it shows me multiple logins. Since it doesn't show any information to distinguish multiple logins, I want to edit a login to add my username to the title. Now, even when my vault's already unlocked, it requires the following steps;
1. Notice where the item resides (Groups > Documents)
2. Click on the Buttercup icon from the extensions
3. Open your vault (which already requires multiple clicks)
4. Select the appropriate group
5. Select the appropriate documents (which requires filtering if there are too many creds in the selected Group)
6. Click the item
7. Click the Edit
8. Make changes & Save
![Screenshot_select-area_20210725063956](https://user-images.githubusercontent.com/24672231/126884630-3c99eb96-0c28-4133-8891-ed34281cfbdb.png)

If we had a context menu (or something) that allows editing the item right from the displayed results as in LastPass (refer to screenshots)., it would have saved a lot of effort.

![image](https://user-images.githubusercontent.com/24672231/126884616-59dd457c-a7e4-40fa-808c-1e7e4df2f183.png)
![Screenshot_select-area_20210725065604](https://user-images.githubusercontent.com/24672231/126884622-94c0264a-cece-4d78-97e0-d2073061943f.png)

**Comment by perry-mitchell** [comment]
Great idea!

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
