### ISSUE TITLE
[Bug] Items not found on the context menu

### ISSUE THREAD

**Issue by testsetse** [buttercup/buttercup-browser-extension#417]
Buttercup's context menus "Enter login details" and "Login with" both do not show any items even though it should. For example, in the screenshot, you can see I've an item saved for flickr.com and is showing up when clicked on Buttercup icon next to email. The same is not shown in the context menu which makes `Custom Fields` unusable.
![image](https://user-images.githubusercontent.com/24672231/126885043-4641c809-cf20-40b6-8c41-ab0554957a80.png)

**Comment by perry-mitchell** [comment]
Context menu has been removed for now. It'll be added back in an upcoming release.
