### ISSUE TITLE
extension cannot recognize open archive

### ISSUE THREAD

**Issue by edblak** [buttercup/buttercup-browser-extension#418]
macos::brave::local bcup file::enable browser is on::archive is unlocked::browser unlock page indicates no open archives::same for saving credentials in same environment::message indicates need to open an archive first

update: some hours later user realised need to _add a vault to the extension_, despite having added it into the desktop app:: did so and it worked fine:: opportunity for better feedback, and maybe add some automation to assist new install/users

**Comment by perry-mitchell** [comment]
#420
