### ISSUE TITLE
[BUG ?] - Renaming group with same name

### ISSUE THREAD

**Issue by Pouasson** [buttercup/buttercup-browser-extension#421]
I just renamed a group with the same name than the previous one and I am sutck on an infinite "Saving Vault" loop. I can't lock the vault either. Still accessible from mobile but no idea how to get out of this..

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
