### ISSUE TITLE
buttercup extension can't save new password

### ISSUE THREAD

**Issue by theuser17** [buttercup/buttercup-browser-extension#423]
The plugin suggests previous passwords, but can not save the new password and gives an error.
I tested with browsers: Google Chrome, Mozilla Firefox but it did not work.

OS: Windows 10 Enterprise 64-bit (Version: 21H2)
Browser1: Mozilla Firefox v96.0.2 (64-bit)
Browser2: Google Chrome v97.0.4692.99 (Official Build) (64-bit)
note: this browser download and installed from official website.

**Comment by sriramsundhar** [comment]
I see the same behaviour
OS: Mac BigSur 11.5
Browser: Crome Version 99.0.4828.0 (Official Build) canary (x86_64)
Tried: Chrome, Firefox, Edge as well 😄

**Comment by W055** [comment]
Same, 
OS : Ubuntu 20.04 LTS 64bits
Browser : Brave Browser Version 1.36.116 Chromium: 99.0.4844.74 (Official Build (64 bits)

Error message is : Failed adding new entry: Failed writing remote file: [PATH]

Tried with a path containing diacritics and one without, same result.

Checked permissions of the file and folders above, all are at 766.

**Comment by hankster112** [comment]
Also the same issue, I opened an issue a while ago but I can't seem to find it again.
OS: Devuan Linux x64 (fork of Debian)
Browser: Ungoogled Chromium 90.0.4430.212
Error: Failed adding new entry: Failed writing remote file: [PATH]
Checked paths, permissions, etc. No fix.

**Comment by hankster112** [comment]
> Please always mention the datasource you're using, it's super important.
> 
> I'd appreciate some help on this one, I can't reproduce it myself currently.

Local database file.

**Comment by hankster112** [comment]
Still having the same issue, updating Buttercup and the browser addon to v6 has not fixed it.

**Comment by hankster112** [comment]
Anyone?

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
