### ISSUE TITLE
[BUG] Network Error unlocking source 

### ISSUE THREAD

**Issue by SirOMGitsYOU** [buttercup/buttercup-browser-extension#426]
![image](https://user-images.githubusercontent.com/20475516/158058250-95af158e-37c9-4095-854a-54b95fc8e7ca.png)

Getting this error message when trying to unlock my vault on the browser extension only happens on the browser the desktop and mobile app work fine

**Comment by jakemoote** [comment]
Similar issue here, trying to add a new vault and getting a "Network Error"

Using Mac OS 11.5.2 (20G95), Chrome Version 101.0.4951.41

Desktop app (Desktop @ v2.14.2 Core @ v6.7.0) is working fine.

![Buttercup Browser Extension Error](https://user-images.githubusercontent.com/35157896/165581847-e79dec41-d967-4ba8-91af-9e4c5d8ad6bd.png)

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
