### ISSUE TITLE
Option to unlock vault while saving new credentials

### ISSUE THREAD

**Issue by Pragati-02** [buttercup/buttercup-browser-extension#437]
Currently, when the buttercup vault is locked, when I try to save new credentials the "Save New Credentials" page requires the vault to be open or it will throw: "No unlocked archives were found. You must unlock at least one archive to be able to save new credentials." warning.
The only option (in chrome) to save your credentials at this point is to go to the browser extension icon and unlock your vault and return to this page to save your new credentials.
Can we instead have an option to unlock the vault on this page ("Save New Credentials") itself? Maybe somewhere where we are showing the warning that no unlocked archives were found?

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
