### ISSUE TITLE
Auto-fill with Google return 400 error

### ISSUE THREAD

**Issue by gerrygralton** [buttercup/buttercup-browser-extension#439]
If logging into Google account using the autofill browser function I get the following error message. Copying and pasting the details avoids this issue. 

```
400. That’s an error.

The server cannot process the request because it is malformed. It should not be retried. That’s all we know.
```

Browser: Firefox 104.0.2
OS: Ubuntu 22.04

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
