### ISSUE TITLE
Feature Request: Support One Drive / SharePoint Online as cloud storage

### ISSUE THREAD

**Issue by achimismaili** [buttercup/buttercup-browser-extension#444]
It would be great if you support Microsoft OneDrive and/or SharePoint Online as cloud storage.
These services are also accessible via dedicated apps on Mac, Android and iOS.

I think, this would also be attractive for using buttercup in a business context in many companies.
Also, to me, this would be a good workaround for issue #206.

I am an architect for Microsoft 365 and Azure services and I am willing to help with that by discussing technical details for an implementation.

![SharePointOnline](https://user-images.githubusercontent.com/19372423/211205461-9c56c61d-4bd4-42f1-8030-096caf6f1412.svg)

Technically, this would mean 3 types of connections:

1. Support adding **Microsoft personal accounts** (e.g. outlook.com, hotmail.com, live.com ...) and connect to personal **OneDrive** storage
2. Support adding **Microsoft Azure Active Directory (AAD) accounts** and connect to **OneDrive** storage via MS Graph API
3. Support adding **Microsoft Azure Active Directory (AAD) accounts** and connect to **SharePoint Online** storage via MS Graph API

https://eu-browse.startpage.com/av/anon-image?piurl=https%3A%2F%2Fdevblogs.microsoft.com%2Fmicrosoft365dev%2Fwp-content%2Fuploads%2Fsites%2F73%2F2021%2F08%2Fsharepoint_48x1.svg&sp=1673192172Td4aff89666ae9a96081583fff9a052c05bd76a91e2f362fc62555d61aae499dd

**Comment by perry-mitchell** [comment]
Hi! Yes I agree supporting one drive would be a good idea, and it simply requires someone to implement it: https://github.com/buttercup/buttercup-core/issues/302

I don't have the time currently to do so but would happily guide someone through the process of integrating it if they were so inclined 😁

I'll close this in favour of the core issue, which is required for all other apps. Thanks for the detailed write up.
