### ISSUE TITLE
[Feature request] Support for Single Sign-On SSO

### ISSUE THREAD

**Issue by marcovidero** [buttercup/buttercup-browser-extension#448]
We have multiple subdomains in our organization. Each one serving different systems/services. But all accessible with the same _username/password_.

In Buttercup, we have to create one entry for each subdomain.

I want to create only one entry, so we can use a single entry for all subdomains. Ex:

- **Entry**: `domain.com`
- **Username**: `username`
- **Password**: `password`
- **URL**: `https://[*].domain.com`

---

**Maybe related with**:  Do not ignore subdomains when filtering credentials #157

**Comment by perry-mitchell** [comment]
Hmm, yes we definitely need to rethink our search result filtering.. but for this, wouldn't you just create one entry with domain.com in the URL field? This should appear on all subdomains in the search results.

**Comment by marcovidero** [comment]
> Hmm, yes we definitely need to rethink our search result filtering.. but for this, wouldn't you just create one entry with domain.com in the URL field? This should appear on all subdomains in the search results.

It worked. Thanks!
