### ISSUE TITLE
OTP field impossible to delete

### ISSUE THREAD

**Issue by masterjg** [buttercup/buttercup-browser-extension#450]
Whenever I try to remove OTP field and press save, Buttercup leaves the field. What is even more strange is that if I rename the field then after pressing save I end up with TWO OTP fields.

**Comment by perry-mitchell** [comment]
This is a known bug, by the sounds of it, that was recently fixed on desktop. An upgrade to the browser extension is on its way that will potentially solve such an issue.

Do note that in the upcoming release the browser extension will no longer store vaults and will instead rely on the desktop application for all vault access.

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
