### ISSUE TITLE
Impossible to add a Dropbox vault

### ISSUE THREAD

**Issue by CMaxence** [buttercup/buttercup-browser-extension#452]
Hi,

I changed my PC recently, so I reinstalled the Buttercup browser extension on Firefox.
I'm trying to add a Dropbox vault to my extension but I'm getting an error.

Steps : Add Vault -> Choose Vault Type: Dropbox -> login to Dropbox  -> error
![image](https://github.com/buttercup/buttercup-browser-extension/assets/25408877/a8c61fcd-fcb2-4244-b81c-fe2720b74f10)

Can you help me ? I use the Windows application in the meantime but it is less practical.

Thanks

**Comment by jyelland** [comment]
Hi, I am having the same issue in Firefox 114.0.2 on Ubuntu. Can create new vaults in Dropbox but not access any existing.

**Comment by pailey** [comment]
I have also been encountering this problem with Chromium on Windows 10. A workaround is to create a new dropbox vault in the extension, then upload your vault to dropbox using the same name (replacing the new empty vault).

**Comment by iaintshootinmis** [comment]
I am receiving this error on Firefox for Debian using KDE Plasma as well. using Debian app until in-browser support is restored.

**Comment by avagraphique** [comment]
Also experiencing this on Chrome for Windows Version 116.0.5845.188 (Official Build) (64-bit)
and Waterfox (FireFox) for Windows v G6.0b5 (64-bit)

**Comment by avagraphique** [comment]
> I have also been encountering this problem with Chromium on Windows 10. A workaround is to create a new dropbox vault in the extension, then upload your vault to dropbox using the same name (replacing the new empty vault).

How do you add a Dropbox vault via the extension, if the extension will not connect to Dropbox?

**Comment by hacker1221** [comment]
I am having the same issue on Ubuntu 20.04.6 LTS with Chrome version Version 116.0.5845.187

but I was able to add Dropbox via Linux desktop application

**Comment by mmuyakwa** [comment]
Same problem! I can't add an existing vault from my Dropbox.
**This issue has been open since June!**
There seems to be no progress, which is sad.

![image](https://github.com/buttercup/buttercup-browser-extension/assets/34812005/d6d6932d-881c-423f-938e-804ef0101b1a)

**Comment by mmuyakwa** [comment]
**Possible Solution**
Take a look at:
[Solved: Error in call to API function "files/list_folder":... - Dropbox Community](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Error-in-call-to-API-function-quot-files-list-folder-quot/td-p/422457) 

> Dropbox API v2 parameter names are case-sensitive. The parameter you're trying to use on [/2/files/list_folder](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder) is named "path", so you'll need to specify "path" instead of "Path".

> Thanks, Greg, I have changed the path from "Path" to "path" and it is returning the list of files from the folder. Really appreciate your quick response and spotting the error. Will remember that parameters are case-sensitive.

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
