### ISSUE TITLE
Failed selecting Google Drive vault An error occurred when adding the vault: Adding archive failed: Failed unlocking source: Failed fetching Google Drive vault: Authentication failed while decrypting content

### ISSUE THREAD

**Issue by psabljic** [buttercup/buttercup-browser-extension#453]
Hi all,
I have my vault on my google drive and I'm unable to access it. I've tried
a) Downloading vault file and adding vault via Desktop app
b) Adding vault from google drive
c) Using chrome extension and adding vault from there

Message from Chrome:
Failed selecting Google Drive vault
An error occurred when adding the vault: Adding archive failed: Failed unlocking source: Failed fetching Google Drive vault: Authentication failed while decrypting content

Message from app:
![image](https://github.com/buttercup/buttercup-browser-extension/assets/137648766/7245bfa4-55d1-4d55-a287-16273184e197)

Anything I can do to resolve it?

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
