### ISSUE TITLE
Feature request: Ability to remove saved credentials directly from drop down list

### ISSUE THREAD

**Issue by manzing** [buttercup/buttercup-browser-extension#455]
Hi,

This is about browser extension, Edge, Chrome and Firefox.

I am regularily annoyed by multiple entries as sometimes Buttercup ask to save credentials even if they already exists in database.
Would it be difficult to be able to remove some credentials from the database directly from the dropdown menu on a website?
It's not easy to do it directly in database using desktop app as my base is on a cloud drive.

Here is an exemple of what the feature could be with Github (you can notice the duplicate btw): 

![buttercup](https://github.com/buttercup/buttercup-browser-extension/assets/2737265/0f940225-cc28-4ed2-b6be-6f98258bcf54)

By clicking on the three dots we can see, an option to delete the entry (or move to trash) would be really useful, like on this demo screenshot.

![buttercup remove](https://github.com/buttercup/buttercup-browser-extension/assets/2737265/20416873-674e-47f2-ad55-2100d8ca483c)

Thanks for reading, I hope it's a good and easy-to-do idea :)

**Comment by perry-mitchell** [comment]
I think for now we'll leave the vault management for the desktop application. V3 removes the vault editing functionality, save for adding new credentials.
