### ISSUE TITLE
frustration: when opening Firefox Buttercup always opens new tab

### ISSUE THREAD

**Issue by georglauterbach** [buttercup/buttercup-browser-extension#456]
When opening the browser, the Buttercup extension will always open a new tab to unlock vaults. Can this be disabled somehow?

**Comment by manzing** [comment]
Hi,
I guess if you disable "Vaults Auto Unlock" in settings it will do the trick.
But you will have to click Buttercup icon when you need to unlock it.

**Comment by georglauterbach** [comment]
Oh, I see. Sorry for the noise 🙈
