### ISSUE TITLE
Desktop Version Displays Nothing When Trying to Open Vault (MacOS)

### ISSUE THREAD

**Issue by boobiesmoothie** [buttercup/buttercup-browser-extension#458]
Am I missing something here? This application was working fantastic yesterday and now when I try to open my vault, I get no splash screen, no...anything.

I've also tried installing the Firefox extension to see if I can just migrate my passwords back to the browser instead but I cannot for the life of me figure out how to do anything with the extension at all other than set permissions.

Please tell me if I'm being stupid and missing something obvious - I just want to be able to get my passwords back and not go through the absolute hell of having to reset everything.

**Comment by perry-mitchell** [comment]
Wrong repo.

There's not enough information here to do anything with, either. Logs might help. Check out the desktop readme for where the config is stored, and try deleting that and then re-opening.
