### ISSUE TITLE
Review/fix `vaults auto unlock`

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-browser-extension#461]
Sorry for brevity

Does this feature function for anyone else because it doesn't seem to function for me - perhaps I'm missing something or another browser function is affecting things (e.g. I gut my browser of as many settings as possible for security reasons every time it closes):

<div>
<img width="375" alt="Screenshot 2024-02-27 at 20 52 30" src="https://github.com/buttercup/buttercup-browser-extension/assets/1715809/dd012571-abc5-4f68-b0fe-24c720dc07d8">
</div>

<div>
<img width="386" alt="Screenshot 2024-02-27 at 20 52 35" src="https://github.com/buttercup/buttercup-browser-extension/assets/1715809/7c056bd6-7df4-4aed-a617-35b6b9059ead">
</div>

🤞

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
