### ISSUE TITLE
Unable to unlock vault in Brave web browser

### ISSUE THREAD

**Issue by barju6693** [buttercup/buttercup-browser-extension#462]
In Brave web browser, when I try to enter the password to unlock the vault, the field to introduce the password is not visible and can't be unlocked.

![image](https://github.com/buttercup/buttercup-browser-extension/assets/17111636/c338cb62-1a91-43d9-9a17-b0ca81f94fe2)

In the console I get this message:
```
Error handling response: Error: Redux state sync failed: The message port closed before a response was received.
    at handleSendMessageResponse (chrome-extension://heflipieckodmcppbnembejjmabajjjj/vendors.js:531:481034)
```

**Comment by perry-mitchell** [comment]
There's a new release coming out now. Would you kindly mind checking it in Brave when it's out? It's version 3.0.0. Being a rewrite I imagine it stands a good chance of working.

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
