### ISSUE TITLE
Connection failed to vault

### ISSUE THREAD

**Issue by joaolamas** [buttercup/buttercup-browser-extension#465]
With most recent buttercup extension, it fails to connect to computer vault:
![Screenshot from 2024-03-26 14-05-12](https://github.com/buttercup/buttercup-browser-extension/assets/8986040/c20cc769-2c40-4752-8559-00b6aab6a5dd)

"""Failed starting connection: Background task failed: NetworkError when attempting to fetch resource."""

When selecting to add a new vault nothing happens too
![Screenshot from 2024-03-26 14-07-11](https://github.com/buttercup/buttercup-browser-extension/assets/8986040/f04a42d9-65e4-47ed-ac53-14533a0564a4)

I have confirmed that local computer application has enabled connection to browser
![enabled](https://github.com/buttercup/buttercup-browser-extension/assets/8986040/501e406f-b70b-491d-8760-fabded5a9034)
and running the old extension version in another browser (chrome), I was able to connect to my vault, so application is correctly configured

**Browser**:
Firefox browser
123.0.1 (64-bit)

**Extension Info:**
Buttercup Password Manager
Info |  
-- | --
Version | 3.0.0
Build Date | 2024-03-26

**buttercup-desktop** 
https://github.com/buttercup/buttercup-desktop/releases/tag/v1.16.2

**Distribution**
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by alonsohn** [comment]
I have problem, Firefox send this error
parse@moz-extension://bf4b270d-58ad-4731-a667-bd143014f047/scripts/popup.js:747:29350
Ti/c<@moz-extension://bf4b270d-58ad-4731-a667-bd143014f047/scripts/popup.js:832:1538
Dl@moz-extension://bf4b270d-58ad-4731-a667-bd143014f047/scripts/popup.js:653:240947
7463/t.unstable_runWithPriority@moz-extension://bf4b270d-58ad-4731-a667-bd143014f047/scripts/popup.js:653:303569
Ga@moz-extension://bf4b270d-58ad-4731-a667-bd143014f047/scripts/popup.js:653:181800
Pl@moz-extension://bf4b270d-58ad-4731-a667-bd143014f047/scripts/popup.js:653:240415
2551/Ml/<@moz-extension://bf4b270d-58ad-4731-a667-bd143014f047/scripts/popup.js:653:240326
D@moz-extension://bf4b270d-58ad-4731-a667-bd143014f047/scripts/popup.js:653:302630
7463/w.port1.onmessage@moz-extension://bf4b270d-58ad-4731-a667-bd143014f047/scripts/popup.js:653:301353

**Comment by perry-mitchell** [comment]
> buttercup-desktop
> https://github.com/buttercup/buttercup-desktop/releases/tag/v1.16.2

Your desktop app is too old, latest is `2.26.2`.

> I have problem, Firefox send this error

> I have the same error as above.

If your errors are related, please update your desktop app version. If not, please create a new issue with relevant error messages + logs.

**Comment by alonsohn** [comment]
![image](https://github.com/buttercup/buttercup-browser-extension/assets/89086444/3e7e5c94-594c-448c-ae08-fc6959a63291)
I using V2.26.2

**Comment by stuartm** [comment]
I'm having the same or similar issue with v2.26.2 when I try to link to the desktop app.

`Failed starting connection: Background task failed: Failed to fetch`

Also seeing the following when clicking on settings tab in plugin:

`Background task failed: No configuration available`

**Comment by perry-mitchell** [comment]
@alonsohn Please see #466
