### ISSUE TITLE
Unexpected Application Error! Invalid URI format

### ISSUE THREAD

**Issue by gravistech412** [buttercup/buttercup-browser-extension#466]
Unexpected Application Error!
Invalid URI format

Firefox (updated) errors in the toolbar. Also errors in the U/P form fields. 

Once logged in, I can update and add a record. 

![TinyTake26-03-2024-10-23-11](https://github.com/buttercup/buttercup-browser-extension/assets/132407936/d3d489b4-f6a8-4411-acbd-d4b2227fc223)

![TinyTake26-03-2024-10-07-12](https://github.com/buttercup/buttercup-browser-extension/assets/132407936/69eff74a-47ae-46ef-a90f-d3fd57179ee4)

Buttercup Versions
- FF 3.0.0
- Chrome 3.0.0
- Win Desktop @ v2.26.2
  - Core @ v7.7.0

**Comment by perry-mitchell** [comment]
Weird, I haven't seen such an error. Are you on stable firefox, latest version? I can't reproduce this.

**Comment by gravistech412** [comment]
FF 124.0.1 (64-bit)
![TinyTake26-03-2024-03-09-54](https://github.com/buttercup/buttercup-browser-extension/assets/132407936/e1b39b0a-b06f-4680-81e0-f6cdbe1939f3)

Several others in my organization have the same error.

**Comment by gravistech412** [comment]
I have uninstalled all FF extensions. Reinstalled BC. It asks to connect. Then it errors as mentioned above. 
With all my vaults locked (win desktop) the FF Extension does not error. My vaults are Google Drive. 
I downloaded the vault and loaded it locally and got the error. I have tried unlocking a vault on all 4 storage locations. Each errors.

**Comment by gravistech412** [comment]
I have determined that it is one specific vault that when unlocked causes the error. This is our main vault.

**Comment by gravistech412** [comment]
I have converted all vaults to "Format B". This vault still errors. 
I have created a local backup of this vault. I have unlocked this backup. The FF ext. errors.

**Comment by perry-mitchell** [comment]
Any special characters in your vault names? Anything else you can share about your desktop configuration?

I've not been able to reproduce this yet, and I can't yet see a pattern as to when this occurs.

**Comment by jyelland** [comment]
@perry-mitchell I am seeing a similar issue. It *does* seem to be specific to a vault that has an underscore in its name. Specifically I see:
```
Unexpected Application Error!
Invalid URI format

parse@moz-extension://014f0866-a9d4-414b-b461-89fe034336ed/scripts/popup.js:747:29350
Ti/c<@moz-extension://014f0866-a9d4-414b-b461-89fe034336ed/scripts/popup.js:832:1538
Dl@moz-extension://014f0866-a9d4-414b-b461-89fe034336ed/scripts/popup.js:653:240947
7463/t.unstable_runWithPriority@moz-extension://014f0866-a9d4-414b-b461-89fe034336ed/scripts/popup.js:653:303569
Ga@moz-extension://014f0866-a9d4-414b-b461-89fe034336ed/scripts/popup.js:653:181800
Pl@moz-extension://014f0866-a9d4-414b-b461-89fe034336ed/scripts/popup.js:653:240415
2551/Ml/<@moz-extension://014f0866-a9d4-414b-b461-89fe034336ed/scripts/popup.js:653:240326
D@moz-extension://014f0866-a9d4-414b-b461-89fe034336ed/scripts/popup.js:653:302630
7463/w.port1.onmessage@moz-extension://014f0866-a9d4-414b-b461-89fe034336ed/scripts/popup.js:653:301353
```
Config is:

Firefox: 124.0.1 (64-bit)

Buttercup:
Desktop @ v2.24.4
Core @ v7.4.0
Flags: installed

MacOS 14.4

**Comment by jyelland** [comment]
I do not see this when only a vault without underscore (and no other special characters) is unlocked.

**Comment by perry-mitchell** [comment]
Ok, thanks for the clarification. I'll see if I can reproduce it..

**Comment by perry-mitchell** [comment]
No, that doesn't seem to trigger it. Not with a local file at least.

![Screenshot_20240327_083652](https://github.com/buttercup/buttercup-browser-extension/assets/3869469/d666fc8e-
338b-46fe-baf8-277bbb6dd2cc)

**Comment by perry-mitchell** [comment]
Ah! It's nothing to do with the vault name/path/type.. it's an **OTP URI parsing issue**. The vaults that are crashing the extension have an invalid OTP URI in them.

I'll get a patch out for this asap.

**Comment by goshander** [comment]
Also if you have bad OTP URL in Trash, just drop this record

**Comment by perry-mitchell** [comment]
Trash should already be ignored.. if not I should check that later.

**Comment by perry-mitchell** [comment]
ETA on this is some time today. Apologies for the inconvenience.

**Comment by adamturcsan** [comment]
> Trash should already be ignored.. if not I should check that later.

It is not. I only had one wrong OTP url, which was in the trash. After emptying it, the addon works properly.

**Comment by Gkupce** [comment]
It was the OTP, I had tested it once to see what it was and the trashed it.
Still, sitting in the trash it was crashing the extension until now.

**Comment by alonsohn** [comment]
Answering the question about special characters, since I can't configure it on GDrive either, I have it synchronized to my server and in the name of a folder it has @ as a special character

**Comment by alonsohn** [comment]
Now, all my problem is in Ubuntu 22.04, in the Windows version everything works, Windows is not the OS. What I use the most, on the contrary it is the exception, my main job is in Linux

**Comment by gravistech412** [comment]
@perry-mitchell thanks for the quick response. The new FF ext version work great now.
