### ISSUE TITLE
Copy credentials / show entry details

### ISSUE THREAD

**Issue by lstandifer** [buttercup/buttercup-browser-extension#467]
in the previous buttercup2 browser extension i could copy pasta usernames\passwords individually, this is extremely helpful for items without browser access. I don't always want to be reaching for the desktop app when I already have the browser extension. Clicking the 3 dots previously would let me access then copy and paste them individually.

Additionally there was a context menu on the browser that would allow me to generate passwords it was very handy,

Buttercup2:
![buttercup2](https://github.com/buttercup/buttercup-browser-extension/assets/24442643/e6d04c5f-4ad5-4072-820b-8f30373bf9b3)

Buttercup3:
![buttercup3](https://github.com/buttercup/buttercup-browser-extension/assets/24442643/a363cf9f-ae5b-44e9-9b09-28f41670af7e)

**Comment by perry-mitchell** [comment]
You're right, this was an oversight on my part. Sorry for the inconvenience!

It'll be added back shortly.
