### ISSUE TITLE
Browser Update Notice Pop-Up Toggle

### ISSUE THREAD

**Issue by denali1** [buttercup/buttercup-browser-extension#468]
Browser addon automatic updates are great!
Pop-over browser windows to tell me an addon has updated? Not so much.
Could we please have a toggle to turn this feature off?

**Comment by perry-mitchell** [comment]
It only shows once. And it's necessary as most people won't realise it's happened and what's required. This way no one can say they didn't realise the new requirements.

Sorry, but I think disabling this feature altogether would negatively affect the product overall. I appreciate that there's a few of us that don't need to be told these things, but I believe that we're in the minority.

Again: you shouldn't see it again. Its "viewed" status is also sync'd across your Mozilla profile.
