### ISSUE TITLE
Automatically adding passwords after update is very sensitive

### ISSUE THREAD

**Issue by Pandasdontfly** [buttercup/buttercup-browser-extension#469]
This is on Windows 11 Firefox. After the update  EVERYTHING makes the account feature popup. Pretty Much ANYTHING you can enter text into makes it think your making an account prior it was perfect and almost never made a mistake but now even watching a youtube video it thinks your making an account. Searching in forums too the actual password button appears and will always pop up to add the account even if your just searching something.

![image](https://github.com/buttercup/buttercup-browser-extension/assets/87935732/6f0e6a59-4849-4ab3-8918-c1b0ae4b846d)
![image](https://github.com/buttercup/buttercup-browser-extension/assets/87935732/972c24a9-3666-4ab2-a63a-cda30a3c00e6)
![image](https://github.com/buttercup/buttercup-browser-extension/assets/87935732/ce4a0deb-47d9-4b58-b4c6-5140ee3611ab)
![image](https://github.com/buttercup/buttercup-browser-extension/assets/87935732/5b40c8a0-6d3e-459a-839d-8d4061502fc6)

**Comment by perry-mitchell** [comment]
Known issue, a fix is coming later today.

**Comment by perry-mitchell** [comment]
Fixed in #470
