### ISSUE TITLE
Open Entry URL and Automatically Login regression

### ISSUE THREAD

**Issue by WizardOfWor1969** [buttercup/buttercup-browser-extension#471]
The only option now for a password from the web browser plugin is "Open Entry URL and Automatically Login". You used to be able to simply copy a password, now it forces you to open a URL as the only option. You can't actually copy or see the password from the web browser.

**Comment by lstandifer** [comment]
i let him know about that yesterday 

https://github.com/buttercup/buttercup-browser-extension/issues/467
