### ISSUE TITLE
desktop version - impossible to use

### ISSUE THREAD

**Issue by rodneyrick** [buttercup/buttercup-browser-extension#478]
Good afternoon,

Since I discovered Buttercup Password, I use it for everything, connecting via a Google Drive account, via browsers. And I think it's sensational!

However, in the new version, which requires installing the desktop application to synchronize, I can no longer use it.
This new version continues to be useful for personal computers and cell phones. But, for corporate use, which requires administrator access to install it on the Operating System of use, I do not have such permissions, as it is not authorized software.

I would like to request, if possible, a way to unlink the mandatory use of the desktop version with the browser extension, please.

Otherwise, unfortunately I will need to migrate all credentials to another type of application that allows use with fewer dependencies.

Thank you.

**Comment by perry-mitchell** [comment]
https://github.com/buttercup/buttercup-browser-extension/discussions/451#discussioncomment-8932731
