### ISSUE TITLE
Arch linux desktop browser connection error

### ISSUE THREAD

**Issue by JulienRaynal** [buttercup/buttercup-browser-extension#480]
Hello,
I have noted that on my arch linux, when going through the connection pipeline between the browser extension and the desktop application a 403 error appears in the browser extension after entering the connection code.
After this I get a 404 error in the browser extension: `Failed searching for entries: Background task failed: Desktop request failed: 404 Not Found`.

Is it somehow solvable ?
Have a great day

**Comment by perry-mitchell** [comment]
Are you using the latest desktop application version? 2.26.2?

**Comment by JulienRaynal** [comment]
It seems that the current version on the AUR package is: v2.24.4.
Guess I'll have to wait for an upgrade for it to work again with the desktop app.
Sorry for the bothering

**Comment by perry-mitchell** [comment]
Oh.. that's a pity.

I definitely need to familiarise myself with the AUR - I'd like releases there to be automatic and managed by this project, ideally.

No sweat - there's a lot of moving parts to this..

**Comment by heberuriegas** [comment]
I have 2.26.3 installed from the AppImage and have the same error.

**Comment by heberuriegas** [comment]
Ok I did solve it by enable the browser access in the desktop application

Connection -> Enable browser access

**Comment by Oxalin** [comment]
I was willing to help with this issue, but I'm glad it has been solved.

And yes, the buttercup-desktop package has not been updated yet (I flagged it as being outdated no later than yesterday).

Also, from the three buttercup-desktop packages available [bin|git], it is the only one that is correctly integrated for handling the buttercup protocol.

Maybe the extension error should be more "human understandable" or propose to look at the desktop application setting.

**Comment by perry-mitchell** [comment]
Agree on the error message. Perhaps we should link to the most up to date AUR item if we don't already.

**Comment by Oxalin** [comment]
> Perhaps we should link to the most up to date AUR item if we don't already.

We already do, we link to the package where it is always the latest version unless it hasn't been updated by the maintainer. The maintainer just need to update the package (PKGBUILD and .SRCINFO) and Arch users should be good to update/use the latest version.

**Comment by perry-mitchell** [comment]
Couldn't this be setup as a pipeline though? So when desktop is published the AUR copy is updated automatically?

**Comment by Oxalin** [comment]
Not in a direct way that I know of...

However, if you were to be the maintainer of the said package, you could change the PKGBUILD file (change the latest version in the file), build/test the package (_makepkg_ takes care of it for you according to the PKGBUILD file), update the .SRCINFO file (_makepkg --printsrcinfo > .SRCINFO_), commit PKGBUILD and .SRCINFO changes and push it in AUR, that would work.

**Comment by perry-mitchell** [comment]
Thanks for the info. Might have to try that some day.

It strikes me as strange that it's not automatic however. I don't see a reason why such a process should be manual. The build/test phase can be done by a pipeline (action) imo.

**Comment by perry-mitchell** [comment]
I'm going to close this for now. It's not relevant to the browser extension - it's more to do with the desktop app's AUR support.
