### ISSUE TITLE
V3 - Better inform the user about the minimal desktop app version

### ISSUE THREAD

**Issue by Oxalin** [buttercup/buttercup-browser-extension#483]
The new extension has been rolling out and I'd like to suggest some improvements in the way we are letting the user be aware of the desktop application requirement.

First, the "Notifications" raised when the new extension is installed should state the minimal desktop app version required (my understanding is 2.26.0 is the minimal version). Using a version prior to this one will not work properly. Also, a link could be provided to guide the user if they need to install or update the desktop app.

On the website's main page, under Buttercup for Browsers, it should be stated that the desktop application _must_ be installed and that it needs to be version _at least_ version 2.26.0.

Also, in the extension's GitHub repo, it should be indicated the minimal version required. As of now, the README states that the extension requires the desktop application to be running, but not about the minimal version.

Finally, the user should be informed about checking the desktop application firewall settings in case the extension is unable to connect to the desktop app. On my first try, the connection failed even though the desktop app was configured to _Enable browser access_. I quickly thought about the firewall setting and it fixed the issue, but mentionning it somewhere clearly visible is a must. I still haven't settled down y mind about where this should be stated, but I'm inclined to put it on the desktop app's side. Maybe in the README file. What do you think about it @perry-mitchell ?

I can take care of updating the different parts of the documentation.

**Comment by perry-mitchell** [comment]
All of this sounds fine. It's actually several issues, but I'm fine having it tracked centrally here. The notice in the extension should be updated along with the website and the browser repo's readme. 

We need to eventually have a central help site for Buttercup, on the main website, which we can start linking to for these things.

**Comment by Oxalin** [comment]
I'll create different PR that we can add here as a meta issue.

**Comment by Oxalin** [comment]
Website: https://github.com/buttercup/buttercup-website/pull/72
Extension: https://github.com/buttercup/buttercup-browser-extension/pull/484
