### ISSUE TITLE
Failed starting connection to Buttercup on Brave extension

### ISSUE THREAD

**Issue by aharlap** [buttercup/buttercup-browser-extension#496]
Cannot connect to Buttercup through Brave extension. Buttercup desktop app open and vault is unlocked.

Error message is:
Failed starting connection:
Background task failed: Failed to fetch

![image](https://github.com/buttercup/buttercup-browser-extension/assets/3870784/0f90d7b4-2cc8-46fe-aa78-687dc9b6b6d6)

Using Brave [Version 1.64.122 Chromium: 123.0.6312.122 (Official Build) (arm64)](https://brave.com/latest/)
Using Buttercup Desktop @ v2.27.0; Core @ v7.7.0
On Macbook Air M1, 2020
Extension Version 3.2.0; Build Date 2024-04-09

In devtools console in the browser, here is a screenshot of the log when I open the extension and click on Connect button:
![image](https://github.com/buttercup/buttercup-browser-extension/assets/3870784/46eab779-b5b3-40b7-83f8-3f7b32c98829)

**Comment by marcovidero** [comment]
**You need to enable secure file host in Desktop App.**

![image](https://github.com/buttercup/buttercup-browser-extension/assets/21201512/32056e6e-91f5-4195-b309-8d4a57e3733a)

Then, restart browser and desktop app.

Tested in:
1. **Firefox 118.0.1** (64-bit) with **Buttercup extension 3.2.0** in **Ubuntu 23.10**;
2. **Brave Version 1.65.114** Chromium: 124.0.6367.60 (Official Build) (64-bit) with **Buttercup extension 3.2.0** in **Ubuntu 23.10**; and
3. **Brave Version 1.64.122** Chromium: 123.0.6312.122 (Official Build) (64-bit) with **Buttercup extension 3.2.0** in **Fedora Linux 39** (Workstation Edition).

**Comment by aharlap** [comment]
Thank you, this fixed it. Would recommend improving the error message with these instructions.
