### ISSUE TITLE
ubuntu: custom field does not work

### ISSUE THREAD

**Issue by hanscees** [buttercup/buttercup-browser-extension#500]
Hi

I am using ubuntu bookworm. 
Downloaded the appimage. 

Run it with --no-sandbox, because appimagwe sais: 

```
 ./Buttercup-linux-x86_64.AppImage 
[103370:0703/230230.421340:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Butter0AA0DF/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

Then making a vault is ok. I can make documents fine. 

But when I try to add a custom filed I can't save the document. The ? sign sais " some fields are missing titles" but the custom field has no tittle files as far as I can see. 

![buttercup2024-07-03 23-06-05](https://github.com/buttercup/buttercup-browser-extension/assets/5273274/d61e7baa-5aed-4123-95b6-4660e0631817)

**Comment by hanscees** [comment]
Your page sais you need appimagelauncher, but that does not install on ubuntu bookworm. 

so please change your website stating it runs on ubuntu. 
Going to find another passwordmanager. Shame.

**Comment by perry-mitchell** [comment]
"Click to edit" on the left side, beside the custom field. Needs a title.

This isn't super clear but a redesign is needed.
