### ISSUE TITLE
Local archive through HTML5 Filesystem API 

### ISSUE THREAD

**Issue by xtrasmal** [buttercup/buttercup-browser-extension#51]
Can I add a local archive? Dropbox, Owncloud and Webdav do not satisfy my needs.

Right now I fixed it by using my local webserver. I created a Virtual Host. Then I selected WebDav, added the Virtual Host's domain as WebDav url. So now I do not need to move out of my LAN.

So what I think is missing, is a fourth option called Local. It should be possible to use HTML5's Filesystem API.

**Comment by xtrasmal** [comment]
@perry-mitchell I re-created the issue like @sallar suggested. Label this a feature-request?

**Comment by xtrasmal** [comment]
@sallar @perry-mitchell I wrote about how I set this up on the following page https://dev.to/xtrasmal/own-your-own-credentials-with-buttercup-password-manager
Hope you do not mind that I used the image on your homepage. If you do, please tell me and I will remove it.

**Comment by sallar** [comment]
@xtrasmal we don't mind at all :) Thanks for writing about us

**Comment by perry-mitchell** [comment]
This needs some minor research into the API and its browser support.

**Comment by sallar** [comment]
@perry-mitchell Seems like Chrome [has this](https://developer.chrome.com/apps/fileSystem), but I keep finding conflicting results about Firefox... So we need to look into that one.

**Comment by perry-mitchell** [comment]
@sallar Seems firefox has some API.. Wish they both shared the same however. Oh well, seems it's doable: https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/OSFile.jsm/OS.File_for_the_main_thread

**Comment by perry-mitchell** [comment]
It looks questionable that this might work in Chrome: https://developer.chrome.com/apps/app_storage

Due to that, I'm going to close this in favour of #91 - Proxying through the desktop would be more stable.
