### ISSUE TITLE
Unable to create Dropbox archive at root level

### ISSUE THREAD

**Issue by lukechilds** [buttercup/buttercup-browser-extension#69]
If I link my Dropbox account and check "Create new archive at path" I get the error:

`The value 'dropbox_path' must be set`

If I then put a random filename in the remote path input I get the error:

`There was an error processing the provided archive details: undefined`

If I click browse and then check "Create new archive" and then click select (with or without text in the filename input) I get the error:

`Please select a valid archive before continuing`

There are multiple references to creating a new archive but it doesn't seem possible. You don't seem to proceed with the form unless you select a pre-existing archive from dropbox.

**Comment by perry-mitchell** [comment]
Ah.. I just tried it and there seems to be a bug with creating at root level. If I try to create a new archive inside a directory, it works:

![image](https://cloud.githubusercontent.com/assets/3869469/26518322/1a789f4a-42b7-11e7-8224-eebb7c8c181f.png)

Thanks for reporting and sorry for the inconvenience.

**Comment by lukechilds** [comment]
Ahhh, I see. Just FYI, creating at root level in the Electron app works.

Sorry, unrelated question, but while I've got you, is the Gitter still active? I asked a question re LastPass import in there.

**Comment by perry-mitchell** [comment]
Yes Gitter is still used, but we have quite a number of channels so it's difficult to have them all open.. I had seen the notification but have not yet had time to get to Gitter sorry 😐 

It's been quiet for some time there so we haven't used it as a high priority form of communication..

**Comment by lukechilds** [comment]
Great, whenever you have time 👍
