### ISSUE TITLE
Wrong "Firefox extension" URL

### ISSUE THREAD

**Issue by fmommeja** [buttercup/buttercup-browser-extension#75]
On the Buttercup site, the actual URL associated to the **_Firefox extension_** menu item should be :
[https://addons.mozilla.org/en-US/firefox/addon/buttercup-pw/](url)
instead of :
[https://addons.mozilla.org/en-US/firefox/addon/buttercup/](url)
which leads to a Firefox theme with the same name…

**Comment by perry-mitchell** [comment]
Moved to the website: buttercup/buttercup-website#15
