### ISSUE TITLE
Generate new password feature

### ISSUE THREAD

**Issue by bagage** [buttercup/buttercup-browser-extension#76]
I may have missed it but it seems we cannot ask buttercup extension to generate a random password when creating a new online account.
It is available in the desktop application, would it be possible to have it available in the extension as well?

Would be super cool :)! I've tested with version 0.12.0.

**Comment by perry-mitchell** [comment]
Thanks @bagage that's a great idea. Would you imagine that it'd automatically place the password in say a registration form?

**Comment by bagage** [comment]
It would be the ideal solution - because sometimes, the registration form won't allow some passwords (too short, too simple, too long (!), unsupported characters in it (!)). 
So ideally, the password should be "tested" and ensured that it worked before saved within buttercup.

But I would be totally happy even if there is no such intelligence and user has to copy it from buttercup to the password field :).

**Comment by blimmo** [comment]
I think this has been added now?

**Comment by perry-mitchell** [comment]
Yes, thanks @blimmo ! 😄
