### ISSUE TITLE
[Lastpass] Import Parsing Error

### ISSUE THREAD

**Issue by doodlemania2** [buttercup/buttercup-browser-extension#79]
When performing a LastPass import (CSV) it appears as though the importer is not properly escaping out the commas that appear in different fields/entries. End up with a variety of misplaced/incorrect entries.

**Comment by perry-mitchell** [comment]
Hi Derek,

I guess this is actually related to the desktop app, as that's where the import occurs. Any way you could provide us a sample export with the offending punctuation? Obviously with no sensitive credentials of course..

**Comment by doodlemania2** [comment]
Was able to reproduce this on an import with a comma in the actual password field, title field or in the notes field. Is that helpful?

**Comment by perry-mitchell** [comment]
It helps to know.. but very confusing as to why that is. When exporting **from Lastpass** to CSV, the values that contain special characters like the comma should be escaped or surrounded with quotes presumably. If Lastpass is not doing that then it's a bug on their side - but I'd need to see an export from them to know if that's the case.

**Comment by perry-mitchell** [comment]
Closing this issue as I've moved it to the desktop application, where this is occurring.
