### ISSUE TITLE
Subfolders ignored on new ownCloud connection

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-browser-extension#80]
For some reason requesting URLs like https://demo.nextcloud.com/nai3saew/, which should point to https://demo.nextcloud.com/nai3saew/remote.php/webdav/, instead resolve to https://demo.nextcloud.com/remote.php/webdav/ (minus the subfolder).

**Comment by NicolaiOksen** [comment]
Experiencing the same issue.

**Comment by perry-mitchell** [comment]
@NicolaiOksen This should be fixed in the [latest Chrome release](https://chrome.google.com/webstore/detail/buttercup/heflipieckodmcppbnembejjmabajjjj). If you're a Firefox user the release will take a while longer as their review process is quite lengthy.
