### ISSUE TITLE
Using the extension with NextCloud

### ISSUE THREAD

**Issue by nourz02** [buttercup/buttercup-browser-extension#83]
Hello,

I have some issues to use my *.bcup store on my nextcloud (www.dummyurl.be/nextcloud). How can I achieve that ?
I tried to use WebDAV but I didn't succeed. Can anyone help me ?

Thanks in advance.

**Comment by morojgovany** [comment]
Same for me, I can add a new archive in plugin firefox but after closing the browser, the archive disappeared from the extension...
If I add an archive in vivaldi or chrome, I just get a 503 error (can't parse remote directory).
I have to copy / paste from the desktop app and it's not really useful !
Thx

**Comment by perry-mitchell** [comment]
Hey guys! Seems there might still be some issues with Nextcloud in the extension. As I don't have a Nextcloud installation right now, any PRs would be very welcome! I don't currently have so much time to devote to the extension until the mobile app goes live.

**Comment by nourz02** [comment]
Anyone want to do this PR ? I don't have time to do it but I can provide a NextCloud installation/account to anyone working on this PR.
Thx

**Comment by Stealthbird97** [comment]
Any progress on this? Lack of NextCloud in the Browser app is really the only thing stopping me from using Buttercup,

**Comment by perry-mitchell** [comment]
We're currently reworking the browser extension, and it's going well. Hopefully it should be ready some time in January. As for Nextcloud support, that depends largely on nextcloud/server#3131. I have a feeling that we won't be able to get it working from within the browser straight away due to their issues with CORS. If there was a clean way to access Nextcloud WebDAV endpoints from within the browser (Chrome extension), we'd have integrated it a while back.

**Comment by perry-mitchell** [comment]
If this is not immediately possible, it may require proxying requests through the desktop application. Using a Node application as a proxy would solve the CORS issues with Nextcloud.

**Comment by perry-mitchell** [comment]
Currently there are a number of open issues on the Nextcloud server repo: nextcloud/server#7365 nextcloud/server#3131 - Along with _many_ more WebDAV related issues. At this current stage, we are considering a more drastic option of removing official support for Nextcloud. If we are unable to get the help we need to connect to Nextcloud services from the browser, we won't be able to get a browser extension integration working. If we only support Nextcloud on _most_ of our services, it reflects badly on our product in terms of completeness. 

We've made some more requests (via Twitter, Spectrum and Github) to Nextcloud and the community for help.

**Comment by crankycaleb** [comment]
I wanted to post here that this works consistently for me, I just can't browse to the archive when trying to set it up. I have to type the path manually. Afterward the archive stays and works fine between browser sessions.
Firefox 57
Nextcloud 12.0.3
Extension archive setup as owncloud, manually specified path in the last box.

**Comment by crankycaleb** [comment]
Can I add that I would actually prefer the extension to be proxied through the application anyway? My .bcup archive is synced locally on the machine to my nextcloud sync folder anyway, and it just makes sense to not have that added network lag and separate setup process to sync the extension anyway. This is the way other software such as enpass handles it.

**Comment by perry-mitchell** [comment]
@crankycaleb Good point sir. It's a good idea, and would end up solving a lot of issues. I do prefer using my archives through the browser, however, but some users may want to install the desktop app and be done with the setup process. Having the ability to connect to archives in the desktop application rather than adding them in the browser would definitely be a cool/powerful feature. 

I've added a separate issue for that here: #91

**Comment by Stealthbird97** [comment]
Thanks for the reply. It would be a shame to lose NextCloud functionality entirely, and being able to connect to the Desktop application is something which would be useful on its own, and also helpful is circumventing this issue.

**Comment by mannp** [comment]
Is there a place we can add our support for nextcloud help in getting this sorted?

**Comment by perry-mitchell** [comment]
@mannp Nextcloud is currently working in the remaster (soon to be version 1.0). The eta for this is January, but there's no solid date just yet.
