### ISSUE TITLE
Using extension with Firefox 56.0 (Android)

### ISSUE THREAD

**Issue by robinwolny** [buttercup/buttercup-browser-extension#85]
Buttercup Firefox extension not working with Firefox 56.0 Android mobile devices.

**Comment by perry-mitchell** [comment]
Thanks for reporting @robinwolny. Could you please describe the problem? Does the extension simply not function at all or is there a specific symptom?

Also, I don't have the means to test this currently. Perhaps someone with a device that can reproduce this might be able to help?

**Comment by perry-mitchell** [comment]
Any more info on this @robinwolny? I'm not sure that mobile android devices are what we want to target with this extension. Our soon-to-be-released android app may better suit that area.

**Comment by tigermick** [comment]
Hi !
I have the same problem ... i use firefox android version and i'd rather buttercup fills automatically forms in websites.
But impossible to open buttercup in android firefox version to set bcup file.

**Comment by robinwolny** [comment]
@perry-mitchell thanks for info. It would be good to mention that in addon description. I look forward to Android app. Really like Buttercup for its multiplatform support! For long I have been using keepass but not supported on MacOSX.

**Comment by perry-mitchell** [comment]
Thanks for the kind words. I'm closing this as I've updated the readme to clear the current supported platforms up. We're definitely open to changing that in the future, but we don't have the bandwidth right now. I apologise for any inconvenience and I hope that the mobile android app helps to fill the gap.
