### ISSUE TITLE
Connect through desktop application (local vault files)

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-browser-extension#91]
Option to connect to archives available in the desktop application.

Once an encrypted channel is set up, access to the filesystem can be provided. Files read and written should be limited to `.bcup` files only.

**Comment by Stealthbird97** [comment]
This would be particularly useful as the browser app only allows connection to remote/cloud stored bcup archives, as current.
The alternative would be to have to specify the local file directly in the browser app - if they didn't want to install the desktop application. Of-course, they'd have to manage the sync themselves.

**Comment by xiorcal** [comment]
I really need this too; working on restricted network environnement I can't connect to external network...

**Comment by perry-mitchell** [comment]
I've completed the file host library that we'll use for this feature: [secure-file-host](https://github.com/buttercup/secure-file-host)

It needs to be implemented in the Desktop app, and then connected to from the extension: buttercup/buttercup-desktop#678

**Comment by perry-mitchell** [comment]
This is now complete in #193. It'll be released shortly.

**Comment by aleclarson** [comment]
I've enabled "Secure file host" in the desktop app. How do I make the Firefox browser extension use it?
