### ISSUE TITLE
Username field is not autofilled

### ISSUE THREAD

**Issue by reuterbal** [buttercup/buttercup-browser-extension#93]
On some pages, just the password field is auto-filled but not the username field (e.g., GitHub).

**Comment by perry-mitchell** [comment]
This may be addressed by the upcoming major version update.

**Comment by perry-mitchell** [comment]
Whoops wrong issue - This should be addressed in the next week hopefully.

To keep the issue specific, let's tie it to Github only. We can make issues for other sites easily but having a broad "many sites" scope means we probably could never close this.

**Comment by perry-mitchell** [comment]
Ok so it seems that this is still an issue. It's with detection, so I've opened the issue buttercup/locust#5
